## Background: Luppino 2020 Nat Genet states that "We found a significant enrichment of DEGs within 2.5 and 5.0 kb of a domain boundary (Fig. 5f)." after cohesin loss, and that "most DEGs with > 2-fold change in expression following cohesin loss were located within 50kb of a domain boundary". And CTCF had opposite effect on TAD boundary strength compared to cohesin loss.

## Goal in this script, I want to perform Fisher's exact test on DEG enrichment at TAD boundaries that became significantly weaker in ASD: 
#       TSS within x kb (eg. 50kb) of TAD boundary
#               Y              N
#       ------------------------------
# DEG Y |               |             |
#       ------------------------------
# DEG N |               |             |
#       ------------------------------
# background genes are all Jill_DEG genes

rm(list = ls())
options(stringsAsFactors = F, scipen = 999)

library(stringr)
library(Repitools)
library(GenomicRanges)
library(tidyverse)    
library(ggplot2)    

setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")

## Load diffIS results
# generated by 6_5_differential_ISnonsegdup_analysis_v4_afterGRC_TADbOnly.R
lnames = load("p_magnitude_Bulk_lmeDiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange_includingTechRepsAndOutliers.rda") # p, magnitude, diffIS 
rm(p, magnitude)

IS_FDR_threshold = 0.1
diffIS$Dysreg = ifelse(is.na(diffIS$FDR) | diffIS$FDR >= IS_FDR_threshold, "No significant change", ifelse(diffIS$FDR < IS_FDR_threshold & diffIS$Magnitude > 0, "Weaker in ASD", "Stronger in ASD"))
table(diffIS$Dysreg) # confirmed 754 Weaker in ASD, 297 Stronger in ASD

df = as.data.frame(str_split_fixed(rownames(diffIS), "_", 3))
df$V2 = as.integer(df$V2); df$V3 = as.integer(df$V3)
colnames(df) = c("chr", "start", "end")
diffIS = cbind(df, diffIS); rm(df)

# ## Load consensus TAD boundaries
# # according to 16_2_v2_caQTLBryois_plot_EffectOnATAC_vs_ASDgwasZ_ColorByPromDistUpDown.R NACC1 example
# ws = 5
# SampleName1 = "Batch1and2_CTL"
# SampleName2 = "Batch1and2_ASD"
# ASD_TopDom_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/TopDom/6_9_aggregated_matrix_Batch1and2/"
# load(paste0(ASD_TopDom_dir, SampleName1, "_TADcallsDomains_TopDom2GENOVA_windowsize",ws,".rda")); Domains_CTL = Domains # Domains
# load(paste0(ASD_TopDom_dir, SampleName2, "_TADcallsDomains_TopDom2GENOVA_windowsize",ws,".rda")); Domains_ASD = Domains # Domains
# 
# ## Only include 40kb bins adjacent to both CTL and ASD TAD boundaries
# Domains = unique(rbind(Domains_CTL, Domains_ASD)) # 6898 union of domains 
# Domains = Domains %>%
#   arrange(chrom, start, end)
# rm(Domains_ASD, Domains_CTL)
# Actually the IS_df already is restricted to 40kb bins at consensus TAD boundaries

## Load DEG
Jill_DEG = readxl::read_excel("~/Documents/Documents/Geschwind_lab/LAB/Database_download/31_Jill_ASD_pancortical_RNAseq_datasets/logFC_SupplementaryTable3.xlsx")

## Load gene locations
lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/10_3_8_v5_promoter_gr.rda") # promoter_gr geneAnno
rm(promoter_gr)

## Make gene dataframe
gene_df = Jill_DEG[,c("ensembl_gene_id","external_gene_name", "WholeCortex_ASD_logFC", "WholeCortex_ASD_FDR")]

geneAnno$start = geneAnno$end = geneAnno$TSS
geneAnno_gr = annoDF2GR(geneAnno)
diffIS_gr = annoDF2GR(diffIS)
hits = as.data.frame(findOverlaps(geneAnno_gr, diffIS_gr))
hits$ensembl_gene_id = geneAnno$ensembl_gene_id[hits$queryHits]
hits$IS_bin = rownames(diffIS)[hits$subjectHits]
hits = cbind(hits, diffIS[hits$subjectHits,c("Magnitude", "FDR", "Dysreg")])
colnames(hits)[(ncol(hits)-2):ncol(hits)] = paste0("IS_", colnames(hits)[(ncol(hits)-2):ncol(hits)])
hits = unique(hits[,-c(1:2)]) # 7593 rows

save(hits, file = paste0("5_v4_st2_geneTSS_inTADbBins_wISchange_FDR",IS_FDR_threshold,".rda"))
# These are all the genes within 40kb of TAD boundaries

## Fisher's Exact Test
DEG_FDRt = 0.05
A = n_DEG_within40kbOfSigWeakerTADb = length(which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR < DEG_FDRt)) # DEG_FDR < 0.05 -> 0.1: 179 -> 296 genes
B = n_nonDEG_within40kbOfSigWeakerTADb = length(which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR >= DEG_FDRt)) # DEG_FDR < 0.05 -> 0.1: 587 -> 996 genes
C = n_DEG_outside40kbOfSigWeakerTADb = length(which(! Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR < DEG_FDRt)) #  DEG_FDR < 0.05 -> 0.1: 4040 -> 3923 genes
D = n_nonDEG_outside40kbOfSigWeakerTADb = length(which(! Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR > DEG_FDRt)) #  DEG_FDR < 0.05 -> 0.1: 20026 -> 19617 genes

Fisher_tbl = matrix(c(A, B, C, D), nrow = 2)
Fisher_res = fisher.test(Fisher_tbl)
formatC((Fisher_p = Fisher_res$p.value), digits = 2) # DEG_FDR < 0.05
(Fisher_OD = Fisher_res$estimate) # OD = 1.5
# Conclusion: ASD-associated DEGs (FDR < 0.05) are enriched within 40kb of TAD boundaries that become weaker in ASD (FDR < 0.05 or FDR < 0.1)

## Are there SFARI genes among DEG within 40kb of weaker TAD boundaries? (DEG FDR < 0.05,  diffIS FDR < 0.05 -> 0.1)
SFARI = read.csv("~/Documents/Documents/Geschwind_lab/LAB/Database_download/SFARI_human_genes/SFARI-Gene_genes_01-11-2022release_03-03-2022export.csv")
SFARI = SFARI[SFARI$gene.score %in% c("S","1","2"),]

GOI = Jill_DEG$ensembl_gene_id[which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR < DEG_FDRt)]  
SFARI$gene.symbol[SFARI$ensembl.id %in% GOI] # 12 SFARI genes: "ANK2" "APBB1" "ATP2B2" "BRAF" "DLGAP1"   "DYNC1H1"  "INTS6" "NCKAP1" "PRICKLE1" "UBR5" "TRIM23" "USP7" (same as diffIS FDR < 0.1 when cis_longRange is not in the linear model) -> 15 SFARI genes: added "ANK3" "RAI1" "TRAPPC9"
GOI_SFARI = GOI[GOI %in% SFARI$ensembl.id]
colnames(Jill_DEG)[1:15]
(GOI_DEGlogFC = Jill_DEG[Jill_DEG$ensembl_gene_id %in% GOI_SFARI,c(1:13)]) # except for INTS6 and UBR5, all SFARI genes at weaker TADb were down-reg.

## How many genes were up v. down at weaker TADb?
length(which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR < DEG_FDRt & Jill_DEG$WholeCortex_ASD_logFC < 0)) # 101 -> 167 down-reg
length(which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR < DEG_FDRt & Jill_DEG$WholeCortex_ASD_logFC > 0)) # 78 -> 129 up-reg

# Are more DEGs being down-reg at TADb that become weaker & A subset of them are SFARI genes.
# Statistical test: Randomly select the same number of TADb bins, intersect with DEGs, quantify the ratio of down/up-reg genes. 

load("../ISdf40kb_nonsegdupAutosome.rda") # IS_df copied to MAC
df = as.data.frame(str_split_fixed(rownames(IS_df), "_", 3))
df$V2 = as.integer(df$V2); df$V3 = as.integer(df$V3)
colnames(df) = c("chr", "start", "end")
IS = cbind(df, IS_df); rm(df)

set.seed(702)
nDEG_atTADb = as.data.frame(matrix(nrow = 0, ncol = 2))
for (B in 1:100) {
  idx = sample(1:nrow(IS), length(which(diffIS$FDR < 0.05 & diffIS$Magnitude > 0))) # 534 with FDR < 0.05
  IS_subset = IS[idx,]
  IS_subset_gr = annoDF2GR(IS_subset)
  
  hits = as.data.frame(findOverlaps(geneAnno_gr, IS_subset_gr))
  hits$ensembl_gene_id = geneAnno$ensembl_gene_id[hits$queryHits]
  hits$IS_bin = rownames(IS_subset)[hits$subjectHits] # 1025 rows
  
  DEG_FDRt = 0.05
  nDEG_down = length(which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id & Jill_DEG$WholeCortex_ASD_FDR < DEG_FDRt & Jill_DEG$WholeCortex_ASD_logFC < 0))
  nDEG_up = length(which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id & Jill_DEG$WholeCortex_ASD_FDR < DEG_FDRt & Jill_DEG$WholeCortex_ASD_logFC > 0))
  nDEG_atTADb = rbind(nDEG_atTADb, c(nDEG_down, nDEG_up))
}

colnames(nDEG_atTADb) = c("nDEG_down", "nDEG_up")
nDEG_atTADb$ratio = nDEG_atTADb$nDEG_down/nDEG_atTADb$nDEG_up
p = length(which(nDEG_atTADb$ratio > 101/78))/B # p = 0.47
#nDEG_atTADb$ratio = nDEG_atTADb$nDEG_down/(nDEG_atTADb$nDEG_up + nDEG_atTADb$nDEG_down)
#p = length(which(nDEG_atTADb$ratio > 101/(78 + 101)))/B
#nDEG_atTADb$ratio = (nDEG_atTADb$nDEG_down-nDEG_atTADb$nDEG_up)/(nDEG_atTADb$nDEG_down+nDEG_atTADb$nDEG_up)
#p = length(which(nDEG_atTADb$ratio > (101-78)/(101+78)))/B # p = 0.47

pdf(paste0("5_v4_st2_Histogram_ratio_nDEGupVSdown_atTADbWeakerInASDfdr",IS_FDR_threshold,".pdf"), width = 8, height = 5)
hist(nDEG_atTADb$ratio, breaks = 30, main = paste0("p = ", p, " at TAD boundaries that become weaker in ASD"), xlab = "Ratio of the number of down- and up- regulated genes at TAD boundaries")
abline(v = 101/78, col = "red")
dev.off()

# TADb get weaker is not associated with direction of DEG changes - sure, some genes may gain interaction of enhancers in a neighboring TAD, some genes may loosen interactions of enhancers within the same TAD. Therefore, I can't say anything about SFARI gene down-reg.

#### How many ASD diff IS bins overlap with Dup15q NeuNp diff IS bins?
rm(list = ls())
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")
lnames = load("p_magnitude_Bulk_lmeDiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange_includingTechRepsAndOutliers.rda") # p magnitude diffIS
ASD_diffIS = diffIS
lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_Dup15q/Hi-C/data_analysis/11_TADs/IS_GENOVA/st5_v5_p_magnitude_NeuNp_lmeDiseaseSexValid.interaction.rmdupdupcis.longRange_includingTechRepsAndOutliers.rda") # p magnitude diffIS
Dup15q_NeuNp_diffIS = diffIS

ASD_fdr = 0.05 # 0.05
Dup15q_fdr = 0.1 # 0.1

BG = intersect(rownames(ASD_diffIS), rownames(Dup15q_NeuNp_diffIS)) # 9625 TAD boundaries
ASD = rownames(ASD_diffIS)[which(ASD_diffIS$FDR < ASD_fdr & ASD_diffIS$Magnitude > 0)] # 754 TADb get weaker in ASD bulk
Dup15q_NeuNp = rownames(Dup15q_NeuNp_diffIS)[which(Dup15q_NeuNp_diffIS$FDR < Dup15q_fdr & Dup15q_NeuNp_diffIS$Magnitude > 0)] # 739 TADb get weaker in Dup15q NeuNp
Shared = intersect(ASD, Dup15q_NeuNp)  # 61 TADb get weaker in both ASD bulk and Dup15q NeuNp

fisher.test(matrix(c(length(Shared), length(setdiff(ASD, Dup15q_NeuNp)), length(setdiff(Dup15q_NeuNp, ASD)), length(setdiff(BG, union(ASD, Dup15q_NeuNp)))), nrow = 2))
# There is no significant overlap between the TAD boundaries that get weaker in bulk ASD samples and Dup15q neurons.
# I can't explain why TAD boundary changes are so different b/w bulk ASD samples and Dup15q neurons. How about cor of their logFC?

ASD_diffIS$TADb_bin = rownames(ASD_diffIS)
Dup15q_NeuNp_diffIS$TADb_bin = rownames(Dup15q_NeuNp_diffIS)

diffIS = inner_join(ASD_diffIS, Dup15q_NeuNp_diffIS, by = "TADb_bin")
colnames(diffIS) = gsub("\\.x", "_ASD", colnames(diffIS))
colnames(diffIS) = gsub("\\.y", "_Dup15qNeuNp", colnames(diffIS))

lm_res = lm(Magnitude_Dup15qNeuNp ~ 0 + Magnitude_ASD, data = diffIS)
lm_res$coefficients[1] # 0.32
lm_summary = summary(lm_res)
formatC(lm_summary$coefficients[,4], digits = 1) # p = 2e-27
save(diffIS, lm_res, lm_summary, file = "5_v4_st2_Correlation_TADbIS_logFC_inASDvsDup15qNeuNp.rda")

pdf("5_v4_st2_Correlation_TADbIS_logFC_inASDvsDup15qNeuNp.pdf", height = 4, width = 6)
par(mar = c(5,5.5,4,2))
plot(x = diffIS$Magnitude_ASD, y = diffIS$Magnitude_Dup15qNeuNp, pch = 19, col = alpha("black", 0.3), xlab = "logFC of insulation score changes in bulk ASD", ylab = "logFC of insulation score changes\nin Dup15q neurons", main = paste0("ASD ~ Dup15q NeuNp\nCorrelation coef. = ", round(lm_res$coefficients[1], 2), ", p = ", formatC(lm_summary$coefficients[,4], digits = 1)))
abline(a = 0, b = lm_res$coefficients[1], col = "red")
dev.off()
# There is significant correlation between TADb changes in ASD vs. NeuNp, GREAT!


## What about logFC of TADb_IS bw ASD and Dup15q_NeuNn?
rm(list = ls())
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")
lnames = load("p_magnitude_Bulk_lmeDiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange_includingTechRepsAndOutliers.rda") # p magnitude diffIS
ASD_diffIS = diffIS
lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_Dup15q/Hi-C/data_analysis/11_TADs/IS_GENOVA/st5_v5_p_magnitude_NeuNn_lmeDiseaseAgeBA7dupcis_includingTechRepsAndOutliers.rda") # p magnitude diffIS
Dup15q_NeuNn_diffIS = diffIS

ASD_diffIS$TADb_bin = rownames(ASD_diffIS)
Dup15q_NeuNn_diffIS$TADb_bin = rownames(Dup15q_NeuNn_diffIS)

diffIS = inner_join(ASD_diffIS, Dup15q_NeuNn_diffIS, by = "TADb_bin")
colnames(diffIS) = gsub("\\.x", "_ASD", colnames(diffIS))
colnames(diffIS) = gsub("\\.y", "_Dup15qNeuNn", colnames(diffIS))

lm_res = lm(Magnitude_Dup15qNeuNn ~ 0 + Magnitude_ASD, data = diffIS)
lm_res$coefficients[1] # 1.4
lm_summary = summary(lm_res)
formatC(lm_summary$coefficients[,4], digits = 1) # p < 3e-254
save(diffIS, lm_res, lm_summary, file = "5_v4_st2_Correlation_TADbIS_logFC_inASDvsDup15qNeuNn.rda")

pdf("5_v4_st2_Correlation_TADbIS_logFC_inASDvsDup15qNeuNn.pdf", height = 4, width = 6)
par(mar = c(5,5.5,4,2))
plot(x = diffIS$Magnitude_ASD, y = diffIS$Magnitude_Dup15qNeuNn, pch = 19, col = alpha("black", 0.3), xlab = "logFC of insulation score changes in bulk ASD", ylab = "logFC of insulation score changes\nin Dup15q neurons", main = paste0("ASD ~ Dup15q NeuNn\nCorrelation coef. = ", round(lm_res$coefficients[1], 1), ", p = ", formatC(lm_summary$coefficients[,4], digits = 1)))
abline(a = 0, b = lm_res$coefficients[1], col = "red")
dev.off()
# There is very significant correlation between TADb changes in ASD vs. NeuNn, GREAT!

## Do we have significant overlap of DEGs b/w ASD and Dup15q bulk?
Jill_DEG = readxl::read_excel("~/Documents/Documents/Geschwind_lab/LAB/Database_download/31_Jill_ASD_pancortical_RNAseq_datasets/logFC_SupplementaryTable3.xlsx")

BG = Jill_DEG$ensembl_gene_id # 24836 genes
ASD = Jill_DEG$ensembl_gene_id[which(Jill_DEG$WholeCortex_ASD_FDR < 0.05)] # 4219 dysreg genes in ASD bulk
Dup15q_NeuNp = Jill_DEG$ensembl_gene_id[which(Jill_DEG$WholeCortex_dup15q_FDR < 0.05)] # 5556 dysreg genes in Dup15q NeuNp
Shared = intersect(ASD, Dup15q_NeuNp) # 2769 dysreg genes in both ASD bulk and Dup15q NeuNp

fisher.test(matrix(c(length(Shared), length(setdiff(ASD, Dup15q_NeuNp)), length(setdiff(Dup15q_NeuNp, ASD)), length(setdiff(BG, union(ASD, Dup15q_NeuNp)))), nrow = 2)) # p < 2.2e-16, OD = 12.2


#### In the end, I could have pie chart, showing % of DEGs (FDR < 0.1) affected by TF up-reg, TADb strength change, CTCF down-reg, caQTL, Unknown reason.
rm(list = ls())
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")

Jill_DEG = readxl::read_excel("~/Documents/Documents/Geschwind_lab/LAB/Database_download/31_Jill_ASD_pancortical_RNAseq_datasets/logFC_SupplementaryTable3.xlsx")
DEG_fdr = 0.05

length(which(Jill_DEG$WholeCortex_ASD_FDR < DEG_fdr)) # 4219
DEG = unique(Jill_DEG$ensembl_gene_id[which(Jill_DEG$WholeCortex_ASD_FDR < DEG_fdr)])
DEGdown = unique(Jill_DEG$ensembl_gene_id[Jill_DEG$WholeCortex_ASD_FDR < DEG_fdr & Jill_DEG$WholeCortex_ASD_logFC < 0]) # 2277 genes are up-reg (FDR < 0.05)
DEGup = unique(Jill_DEG$ensembl_gene_id[Jill_DEG$WholeCortex_ASD_FDR < DEG_fdr & Jill_DEG$WholeCortex_ASD_logFC > 0]) # 1942 genes are down-reg (FDR < 0.05)

### 1. Explained by promoter ATAC changes
lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC01.rda") # sig_CorATAC, sig_CorATAC_uniq, promATAC
DAR_fdr = 0.1

DEG_promATACup = unique(promATAC$ensembl_gene_id[which(promATAC$ATAC_FDR < DAR_fdr & promATAC$WholeCortex_ASD_FDR < DEG_fdr & promATAC$ATAC_logFC > 0 & promATAC$WholeCortex_ASD_logFC > 0)]) # 108 genes have promoter ATAC up-reg (FDR < 0.05)

DEG_promATACdown = unique(promATAC$ensembl_gene_id[which(promATAC$ATAC_FDR < DAR_fdr & promATAC$WholeCortex_ASD_FDR < DEG_fdr & promATAC$ATAC_logFC < 0 & promATAC$WholeCortex_ASD_logFC < 0)]) # 79 genes have promoter ATAC down-reg (FDR < 0.05)

### 2. Explained by distal ATAC changes
DEG_distATACup = unique(sig_CorATAC_uniq$ensembl_gene_id[which(sig_CorATAC_uniq$distalATAC_FDR < DAR_fdr & sig_CorATAC_uniq$WholeCortex_ASD_FDR < DEG_fdr & sig_CorATAC_uniq$distalATAC_logFC > 0 & sig_CorATAC_uniq$WholeCortex_ASD_logFC > 0)]) # 57 genes have promoter ATAC up-reg (FDR < 0.05)

DEG_distATACdown = unique(sig_CorATAC_uniq$ensembl_gene_id[which(sig_CorATAC_uniq$distalATAC_FDR < DAR_fdr & sig_CorATAC_uniq$WholeCortex_ASD_FDR < DEG_fdr & sig_CorATAC_uniq$distalATAC_logFC < 0 & sig_CorATAC_uniq$WholeCortex_ASD_logFC < 0)]) # 120 genes have promoter ATAC down-reg (FDR < 0.05)

### 3. Explained by weakened TAD boundary strength (potentially due to CTCF down-reg)
IS_fdr = 0.1
lnames = load(paste0("5_v4_st2_geneTSS_inTADbBins_wISchange_FDR",IS_fdr,".rda")) # hits

DEG_weakerTADb = unique(Jill_DEG$ensembl_gene_id[which(Jill_DEG$ensembl_gene_id %in% hits$ensembl_gene_id[which(hits$IS_Dysreg == "Weaker in ASD")] & Jill_DEG$WholeCortex_ASD_FDR < DEG_fdr)])
length(DEG_weakerTADb) # 179 genes (DEG_fdr < 0.05)

# Are BATF/FOSL1/BACH1/NFE2 one of the DEG_weakerTADb?
Jill_DEG$ensembl_gene_id[Jill_DEG$external_gene_name %in% c("BATF","FOSL1","BACH1","NFE2")] %in% DEG_weakerTADb # all FALSE, these TFs are not driven by weakened TAD boundaries

### Venn Diagram
#install.packages("venn")
library(venn)
CexSize = 0.4 # cex = 0.4 gives font at 0.093 inch tall or 5 pt, used in Figure1 but not this script

pdf(paste0("5_v4_st2_ASDwholecortexDEGfdr",gsub("\\.","", DEG_fdr),"_explainedbyPromDistalDARfdr",gsub("\\.","", DAR_fdr),"orWeakerTADb",gsub("\\.","", IS_fdr),".pdf"), height = 2, width = 2.5) # use 3 to make Figure prettier after inserting into .ai
x <- list(DEG_promATACup, DEG_distATACup, DEG_promATACdown, DEG_distATACdown, DEG_weakerTADb)
venn(x, ilab=TRUE, zcolor = "style", snames = c("Promoter ATAC\nup-reg\n", "Distal ATAC\nup-reg\n", "   Promoter ATAC\n   down-reg\n", "\n  Distal ATAC\n  down-reg", "\n\nWithin 40kb of  \nweakened TAD  \nboundaries  "), box = F, ilcs = CexSize, sncs = CexSize) # used \n and space to adjust the label positions
dev.off()

# Observations:
# 1) Because the distal ATAC is correlted with prom ATAC, we see big overlap b/w the two pairs of up- and down-reg DAR categories.
# 2) Weakened TADb explain a big amount of DEGs on their own. (Little overlap with the DAR-explained categories). This could mean the CTCF-KD result in TADb weakening and loop/enhancer changes through separate processes.
# 3) Together these 5 categories explain 
length(unique(c(DEG_promATACup, DEG_distATACup, DEG_promATACdown, DEG_distATACdown, DEG_weakerTADb)))/length(DEG) 
# 11% -> 20% of DEGs (DEG_fdr < 0.05) can be explained by DARs (DAR_fdr < 0.05 to 0.1) or weakened TADb (IS_fdr < 0.05).
# 13% -> 22% of DEGs (DEG_fdr < 0.05) can be explained by DARs (DAR_fdr < 0.05 to 0.1) or weakened TADb (IS_fdr < 0.1). 
# 11% -> 19% of DEGs (DEG_fdr < 0.1) can be explained by DARs (DAR_fdr < 0.05 to 0.1) or weakened TADb (IS_fdr < 0.05). 
# 13% -> 21% of DEGs (DEG_fdr < 0.1) can be explained by DARs (DAR_fdr < 0.05 to 0.1) or weakened TADb (IS_fdr < 0.1).
# Use DEG_fdr < 0.05, DAR_fdr < 0.1, IS_fdr < 0.1

### a. Subset of DEG explained by up-reg TFoi binding at promoter ATAC?
DIR = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_TOBIAS/ind_BINDetect_Jaspar2022/"
lnames = load(paste0(DIR, "../../10_3_10_OverlapATACwTFbound/DiffATAC_DEG_logFC_PromoterAndDistalATAC_eaTFbound.rda")) # promATAC, sig_CorATAC_uniq, sig_CorATAC, tf_bound, tf_bound2
# tf_bound is the up-reg TFs, tf_bound2 is CTCF 3 motifs
colnames(promATAC)

DEG_promATACup_UpregTF = unique(promATAC$ensembl_gene_id[which(promATAC$ATAC_FDR < DAR_fdr & promATAC$ATAC_logFC > 0 & promATAC$WholeCortex_ASD_FDR < DEG_fdr & promATAC$WholeCortex_ASD_logFC > 0 & (promATAC$BATF == "yes" | promATAC$FOSL1 == "yes" | promATAC$BACH1 == "yes" | promATAC$NFE2 == "yes"))]) 

length(DEG_promATACup_UpregTF) # 92 genes
length(DEG_promATACup_UpregTF)/length(DEG_promATACup) # 33% genes
length(setdiff(DEG_promATACup_UpregTF, DEG_weakerTADb)) # 80 genes, nope, use the initial calc 92 genes
length(setdiff(DEG_promATACup_UpregTF, DEG_weakerTADb))/length(setdiff(DEG_promATACup, DEG_weakerTADb)) # 22% genes, nope, use the initial calc 26%

# Are the up-reg TFs themselves DEG_weakerTADb?
Jill_DEG$ensembl_gene_id[match(c("BACH1", "NFIL3", "NFE2", "BATF", "FOSL1", "CTCF"), Jill_DEG$external_gene_name)] %in% DEG_weakerTADb # all FALSE, no these up-reg TFs themselves do not locate close to TAD boundaries that become weaker. 

### b. Subset of DEG explained by decreased CTCF-binding at promoter or distal ATAC?
colnames(sig_CorATAC_uniq)

DEG_ATACdown_DownregCTCF = unique(c(promATAC$ensembl_gene_id[which(promATAC$ATAC_FDR < DAR_fdr & promATAC$ATAC_logFC < 0 & promATAC$WholeCortex_ASD_FDR < DEG_fdr & promATAC$WholeCortex_ASD_logFC < 0 & (promATAC$CTCF_MA0139.1 == "yes" | promATAC$CTCF_MA1929.1 == "yes" | promATAC$CTCF_MA1930.1 == "yes"))],
                               sig_CorATAC_uniq$ensembl_gene_id[which(sig_CorATAC_uniq$distalATAC_FDR < DAR_fdr & sig_CorATAC_uniq$distalATAC_logFC < 0 & sig_CorATAC_uniq$WholeCortex_ASD_FDR < DEG_fdr & sig_CorATAC_uniq$WholeCortex_ASD_logFC < 0 & (sig_CorATAC_uniq$CTCF_MA0139.1 == "yes" | sig_CorATAC_uniq$CTCF_MA1929.1 == "yes" | sig_CorATAC_uniq$CTCF_MA1930.1 == "yes"))]))

length(DEG_ATACdown_DownregCTCF) # 302 genes
length(DEG_ATACdown_DownregCTCF)/length(unique(c(DEG_promATACdown, DEG_distATACdown))) # 91% genes, that's a lot, but this has not been validated by CTCF ChIP-seq!

### c, Compile bed files of promoter and distal ATAC down-reg & weakened TAD boundaries 40kb for Matilde to check ASD variants (Upon suggestion of Dan)
rm(list = ls())
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")
DEG_fdr = 0.05

## Promoter & distal ATAC down-reg
lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC01.rda") # sig_CorATAC, sig_CorATAC_uniq, promATAC
DAR_fdr = 0.1

promATACdown_GEdown = promATAC[which(promATAC$ATAC_FDR < DAR_fdr & promATAC$WholeCortex_ASD_FDR < DAR_fdr & promATAC$ATAC_logFC < 0 & promATAC$WholeCortex_ASD_logFC < 0),] # 296 rows
length(unique(promATACdown_GEdown$ATACpeak)) # 288 unique ATAC peaks

distATACdown_GEdown = sig_CorATAC_uniq[which(sig_CorATAC_uniq$distalATAC_FDR < DAR_fdr & sig_CorATAC_uniq$distalATAC_logFC < 0 & sig_CorATAC_uniq$WholeCortex_ASD_logFC < 0),] # 1880 rows
length(unique(distATACdown_GEdown$distal_ATAC)) # 1254 unique ATAC peaks

length(unique(c(promATACdown_GEdown$ATACpeak, distATACdown_GEdown$distal_ATAC))) # 1404 unique ATAC peaks down-reg with target gene expression logFC < 0

## Weakened TAD boundaries
IS_fdr = 0.1
lnames = load(paste0("5_v4_st2_geneTSS_inTADbBins_wISchange_FDR",IS_fdr,".rda")) # hits

weakerTADb_GEdown = hits[which(hits$IS_Dysreg == "Weaker in ASD"),] # 1475 rows
length(unique(weakerTADb_GEdown$IS_bin)) # 903 unique TAD boundaries

## Bed files - hg19
bed_promATACdown_GEdown = as.data.frame(str_split_fixed(unique(promATACdown_GEdown$ATACpeak), "_",3))
bed_distATACdown_GEdown = as.data.frame(str_split_fixed(unique(distATACdown_GEdown$distal_ATAC), "_",3))
bed_weakerTADb_GEdown = as.data.frame(str_split_fixed(unique(weakerTADb_GEdown$IS_bin), "_",3))
save(bed_promATACdown_GEdown, bed_distATACdown_GEdown, bed_weakerTADb_GEdown, file = "5_v4_st2_promORdistalATACdownreg_AND_weakenedTADboundaries_hg19_forMatilde.rda")

