## Background: Luppino 2020 Nat Genet states that "We found a significant enrichment of DEGs within 2.5 and 5.0 kb of a domain boundary (Fig. 5f)." after cohesin loss, and that "most DEGs with > 2-fold change in expression following cohesin loss were located within 50kb of a domain boundary". And CTCF had opposite effect on TAD boundary strength compared to cohesin loss.

## Goal in this script, I want to perform Fisher's exact test on DEG enrichment at TAD boundaries that became significantly weaker in ASD, using all genes in the same range of all TAD boundaries as background: 
#       TSS within x kb (eg. 50kb) of TAD boundary
#               Y              N
#       ------------------------------
# DEG Y |               |             |
#       ------------------------------
# DEG N |               |             |
#       ------------------------------

## After seeing 6_5_v4_st2.7_DEGenrichment_atWeakenedTADbExt0To15Mb_UnequalStep_wISfdr0.05_FisherRes_bgAllGenesInSameRangeOfAllTADb.pdf generated by 6_5_v4_st2.7_test_DEG_enrichment_at_weakenedTADboundaries_extend5Mb_bgAllGenesInSameRangeOfTADb.R, Dan suggested to use a window of TAD mean size + 2SD, which shall give a clear view of the drop of enrichment OR of DEGs with increasing distance from weakened TAD boundaries.

##### pipeline #####
### (1) Load diffIS TADb and calculate mean TAD size + 2SD
### (2) Load and plot Fisher's Exact Test on SFARI gene enrichment at different distance to weakened TADb 
# * calculations done in 6_5_v4_st2.7_test_DEG_enrichment_at_weakenedTADboundaries_extend5Mb_bgAllGenesInSameRangeOfTADb.R
### (3) What proportion of DEGs are located within 1.5Mb (mean TAD size + 2SD) of weakened TADb
####################

rm(list = ls())
options(stringsAsFactors = F, scipen = 999)

library(stringr)
library(Repitools)
library(GenomicRanges)
library(tidyverse)    
library(ggplot2)   
library(cowplot)
library(reshape2)

#setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")
setwd("/Volumes/DataTransferBwMac/Working_Dir/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")

### (1) Load diffIS TADb and calculate mean TAD size + 2SD

## Load diffIS results
# generated by 6_5_differential_ISnonsegdup_analysis_v4_afterGRC_TADbOnly.R
lnames = load("p_magnitude_Bulk_lmeDiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange_includingTechRepsAndOutliers.rda") # p, magnitude, diffIS 
rm(p, magnitude)

## Calculate mean and SD of TAD size 
df = as.data.frame(str_split_fixed(rownames(diffIS), "_", 3))
df$V2 = as.integer(df$V2); df$V3 = as.integer(df$V3)
colnames(df) = c("chr", "start", "end")
diffIS = cbind(df, diffIS); rm(df)

TADsize = diffIS$start[-1] - diffIS$end[-nrow(diffIS)]
TADsize = TADsize[TADsize > 0]
hist(TADsize, xlim = c(0,2000000), breaks = 1000)
M = mean(TADsize) # 400kb
SD = sd(TADsize) # 605kb
W = (M + 2 * SD)/1000 # 1.6M (W has a unit of kb)

### (2) Load and plot Fisher's Exact Test on DEG enrichment at different distance to weakened TADb 

rm(list = setdiff(ls(), "W"))
IS_FDR_threshold = 0.05
lnames = load("6_5_v4_st2.7_DEGenrichment_atWeakenedTADbExtUpTo5Mb_wISfdr0.05_FisherRes_bgAllGenesInSameRangeOfAllTADb.rda") # Fisher_df
Fisher_df_selected = Fisher_df[Fisher_df$ext_bp <= W, ]

# Alternatively for IS_fdr < 0.1:
#IS_FDR_threshold = 0.1
#lnames = load(paste0("6_5_v4_st2.7_DEGenrichment_atWeakenedTADbExt0To15Mb_wISfdr",IS_FDR_threshold,"_FisherRes_bgAllGenesInSameRangeOfAllTADb.rda")) # Fisher_df
#Fisher_df_selected = unique(Fisher_df[which(Fisher_df$ext_bp < 1000 | Fisher_df$ext_bp %% 500 == 0),])

plot1 = Fisher_df_selected %>% # [Fisher_df$ext_bp > 0,]
  ggplot() +
  geom_point(aes(x = ext_bp/1000, y = Fisher_ODs)) +
  theme_bw() +
  ylab("Odds ratio") +
  ggtitle("DEG enrichment") +
  xlab("Distance from weakened TAD boundaries (Mb)") +
  geom_hline(yintercept = 1, col = "red")

Fisher_df_selected$Fisher_Ps_num = as.numeric(Fisher_df_selected$Fisher_Ps)
plot2 = Fisher_df_selected %>% # [Fisher_df$ext_bp > 0,]
  ggplot() +
  geom_point(aes(x = ext_bp/1000, y = Fisher_Ps_num)) +
  theme_bw() +
  ylab("P-value") +
  ggtitle("DEG enrichment") +
  xlab("Distance from weakened TAD boundaries (Mb)") +
  geom_hline(yintercept = 0.05, col = "red")

pdf(paste0("6_5_v4_st2.10_DEGenrichment_atWeakenedTADbExt0To1p5Mb_UnequalStep_wISfdr",IS_FDR_threshold,"_FisherRes_bgAllGenesInSameRangeOfAllTADb.pdf"), width = 8, height = 4)
plot_grid(plot1, plot2, nrow = 1)
dev.off()

# Conclusion: ASD-associated DEGs (FDR < 0.05) are enriched within 10Mb of TAD boundaries that become weaker in ASD (FDR < 0.05 or 0.1). 
# Do this for strengthened TADb as control. -> st2.8

### (3) What proportion of DEGs are located within 1.5Mb (mean TAD size + 2SD) of weakened TADb

rm(list = setdiff(ls(), c("W", "plot1", "plot2", "Fisher_df_selected")))
DEG_FDRt = 0.05; IS_FDR_threshold = 0.05
lnames = load(paste0("6_5_v4_st2.7_nDEG_atDiffTypesOfTADbExt0To15Mb_wISfdr",IS_FDR_threshold,".rda")) # nDEG_distFromDiffIS

nDEG_distFromDiffIS = nDEG_distFromDiffIS[nDEG_distFromDiffIS$ext_bp < W,]

## plot
nDEG_distFromDiffIS_melt = melt(nDEG_distFromDiffIS, id.vars = "ext_bp", variable.name = "TAD_type", value.name = "nDEGs")

plot1_DEG = nDEG_distFromDiffIS_melt[! nDEG_distFromDiffIS_melt$TAD_type %in% c("nGenes_StrengthenedTADb", "NS_TADb"),] %>%
  ggplot(aes(x = ext_bp/1000, y = nDEGs, col = TAD_type)) +
  geom_point() +
  theme_bw() +
  ylab("Number of DEGs") +
  xlab("Distance from TAD boundaries (Mb)") +
  #geom_vline(xintercept = 10, col = "red") +
  theme(legend.position = "top",
        legend.margin = margin(t = 0, unit = "lines"),
        legend.key.size = unit(0.5, "lines")) +
  guides(col = guide_legend(nrow = 3))

plot2_DEG = nDEG_distFromDiffIS_melt[! nDEG_distFromDiffIS_melt$TAD_type %in% c("nGenes_StrengthenedTADb", "NS_TADb"),] %>%
  ggplot(aes(x = ext_bp/1000, y = nDEGs/4219, col = TAD_type)) +
  geom_point() +
  theme_bw() +
  ylab("Percent of DEGs") +
  xlab("Distance from TAD boundaries (Mb)") +
  #geom_vline(xintercept = 10, col = "red") +
  ylim(0,1) +
  theme(legend.position = "top",
        legend.margin = margin(t = 0, unit = "lines"),
        legend.key.size = unit(0.5, "lines")) +
  guides(col = guide_legend(nrow = 3))

pdf(paste0("6_5_v4_st2.10_nDEG_atDiffTypesOfTADbExt0To1p5Mb_wISfdr",IS_FDR_threshold,".pdf"), width = 8, height = 4)
plot_grid(plot1_DEG, plot2_DEG, nrow = 1)
dev.off()

pdf(paste0("6_5_v4_st2.10_DEGenrichmentANDnumber_atDiffTypesOfTADbExt0To1p5Mb_wISfdr",IS_FDR_threshold,".pdf"), width = 8, height = 4)
plot_grid(plot1, plot2_DEG, nrow = 1)
dev.off()

save(plot1, plot2_DEG, Fisher_df_selected, file = paste0("6_5_v4_st2.10_DEGenrichmentANDnumber_atDiffTypesOfTADbExt0To1p5Mb_wISfdr",IS_FDR_threshold,".rda"))

