rm(list = ls())
options(stringsAsFactors = F, scipen = 999)

library(tidyverse)    
library(corrplot)
library(olsrr)
library(nlme)
library(ggplot2)    

setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")

## Load meta data
Annot_numeric = read.table("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/4_QCstat/Annot_numeric.txt", header = T)
Annot_numeric = Annot_numeric[,c(21, 1:2, 4, 6:10, 14:20)]

## Load insulation scores
res = "40kb"
load("../ISdf40kb_nonsegdupAutosome.rda") # IS_df copied to MAC

## Load TADs from aggregated Hi-C matrices
# according to 16_2_v2_caQTLBryois_plot_EffectOnATAC_vs_ASDgwasZ_ColorByPromDistUpDown.R NACC1 example
ws = 5
SampleName1 = "Batch1and2_CTL"
SampleName2 = "Batch1and2_ASD"
ASD_TopDom_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/TopDom/6_9_aggregated_matrix_Batch1and2/"
load(paste0(ASD_TopDom_dir, SampleName1, "_TADcallsDomains_TopDom2GENOVA_windowsize",ws,".rda")); Domains_CTL = Domains # Domains
load(paste0(ASD_TopDom_dir, SampleName2, "_TADcallsDomains_TopDom2GENOVA_windowsize",ws,".rda")); Domains_ASD = Domains # Domains

## Only include 40kb bins adjacent to both CTL and ASD TAD boundaries
lnames = load("../v3_afterGRC_TADbOnly/IS_binsAdjacentToTADb.rda") # IS_df. Generated by 6_5_differential_ISnonsegdup_analysis_v3_afterGRC_TADbOnly.R

# If cannot load, run the following:
# --- ran in 6_5_differential_ISnonsegdup_analysis_v3_afterGRC_TADbOnly.R ---
# Domains = unique(rbind(Domains_CTL, Domains_ASD)) # 6898 union of domains 
# Domains = Domains %>%
#   arrange(chrom, start, end)
# rm(Domains_ASD, Domains_CTL)
# 
# head(Domains)
# rownames(IS_df)[1:2]
# Bins = unique(c(paste0(Domains$chrom, "_", Domains$start - 40e3, "_", Domains$start),
#                 paste0(Domains$chrom, "_", Domains$start, "_", Domains$start + 40e3),
#                 paste0(Domains$chrom, "_", Domains$end - 40e3, "_", Domains$end),
#                 paste0(Domains$chrom, "_", Domains$end, "_", Domains$end + 40e3)))
# length(Bins) # 13290 40kb bins at TAD boundaries, covering 0.53 billion BP (1/6 of the entire genome, sounds right with reported average TAD size 350kb by Luppino 2020 Nat Genet)
# 
# IS_df = IS_df[rownames(IS_df) %in% Bins,] # 11167 bins available (non segmental dup), which covers 15% of BP in the genome
# save(IS_df, file = "IS_binsAdjacentToTADb.rda")

# pdf("st5_v3_histogram_IS_Bulk.pdf", height = 4, width = 6)
# hist(as.matrix(IS_df), breaks = 200) # looks like normal distribution but with a large negative tail and a little-skewed
# dev.off()
# ---------------------

## PCA analysis
pca = prcomp(t(IS_df)) # scale or log2 requires more topPCs to explain 90% var, and reduces the cor bw Diagnosis and topPCs!
pca_Var = pca$sdev^2/sum(pca$sdev^2) # PC1 explains 91.5% variance, PC2 0.85%, PC3-5 = 0.5% each
pca_Var
sum(pca_Var[1:10]) # 11 > 80%, 19 >= 0.9
nPC=11 # used to be 19
PC=pca$x[,1:nPC] # Each column is the loadings.
colnames(PC) = paste0(round(pca_Var,3)*100,"% ",colnames(PC))[1:nPC]

# Calculate correlation between PCs and covariates
stopifnot(rownames(PC) == Annot_numeric$Sample)
PC_Covariates_Table <- cbind(PC,Annot_numeric[,-1])

Cor_pearson = cor(PC_Covariates_Table)
Cor_spearman = cor(PC_Covariates_Table,method = "spearman")
Cor = Cor_pearson
colnames(Cor)
idx = c(1,3:8)
Cor[,nPC + idx] = Cor_spearman[,nPC + idx] # Use spearman correlation for categorical variables
Cor[nPC + idx,] = Cor_spearman[nPC + idx,] # Use spearman correlation for categorical variables

# Plot all to all correlations - done in 6_5_differential_ISnonsegdup_analysis_v3_afterGRC_TADbOnly.R
# pdf(paste0("Corrplot_PCnonsegdupautosomeIS40kb_Annot.pdf"), width = 20, height = 15)
# corrplot(Cor[1:nPC, (nPC+1):ncol(Cor)],method="ellipse",tl.pos = "lt",tl.col = "black", tl.srt = 45, addCoef.col = "darkgrey",
#          tl.cex = 2, cl.cex = 2, number.cex = 2)
# dev.off()

## Find out which Covariates significantly correlate with the topPCs (like what Yuyan described in Feng 2022 BioRxiv)
Cor_sig = matrix(nrow = nrow(Cor), ncol = ncol(Cor))
rownames(Cor_sig) = colnames(Cor_sig) = colnames(Cor)
for (i in 1:ncol(PC_Covariates_Table)) {
  for (j in 1:ncol(PC_Covariates_Table)) {
    tmp = cor.test(PC_Covariates_Table[,i], PC_Covariates_Table[,j])
    Cor_sig[i,j] = tmp$p.value
    # if (tmp$p.value < 0.05) {print(paste(i, colnames(Cor)[i], j, colnames(Cor)[j]))}
  }
}

n_tests = (ncol(Cor_sig)-1)^2 - (ncol(PC)-1)^2
(p_cor_threshold = 0.05/n_tests)
Cov_pool_idx = which(apply(Cor_sig[1:ncol(PC),], 2, function(x) any(x < p_cor_threshold)))
(Cov_pool = colnames(Cor_sig)[Cov_pool_idx]) # Sex, duplicate, trans_interaction, cis_interaction, cis_shortRange

# Maybe bonforroni correction of the p-val is too stringent, try use fdr and see how many covaraites are candidates
Cor_fdr = matrix(p.adjust(Cor_sig, method = "fdr"), nrow = nrow(Cor_sig))
rownames(Cor_fdr) = colnames(Cor_fdr) = colnames(Cor_sig)
for (i in 1:ncol(PC_Covariates_Table)) {
  Cor_fdr[i,i] = 1
}

Cov_pool_idx = which(apply(Cor_fdr[1:ncol(PC),], 2, function(x) any(x < 0.05)))
(Cov_pool = colnames(Cor_fdr)[Cov_pool_idx]) # Sex, Age, Diagnosis, Batch2_Frontal, Batch2_Temporal, ABN, NICHD, valid_interaction, duplicate, trans_interaction, cis_interaction, cis_shortRange, cis_longRange 

## Corrplot (the 2nd plot of each denotes fdr<0.05 by *) - done in 6_5_differential_ISnonsegdup_analysis_v3_afterGRC_TADbOnly.R
# sig_level = 0.05
# # change the old corrplot name as xxx_FrontalAsBase
# pdf(paste0("Corrplot_PCnonsegdupautosomeIS40kb_Annot_withSigCor.pdf"), height = 35, width = 45) 
# corrplot(Cor,method="ellipse",tl.pos = "lt",tl.col = "black", tl.srt = 45, addCoef.col = "darkgrey", tl.cex = 2, cl.cex = 2, number.cex = 2)
# corrplot(Cor, p.mat = Cor_fdr, insig = "label_sig", sig.level = sig_level, pch.col = "white",tl.pos = "lt",tl.col = "black", tl.srt = 45, tl.cex = 2, cl.cex = 2)
# corrplot(Cor[1:ncol(PC), (ncol(PC) + 1):ncol(Cor)],method="ellipse",tl.pos = "lt",tl.col = "black", tl.srt = 45, addCoef.col = "darkgrey",
#          tl.cex = 2, cl.cex = 2, number.cex = 2) 
# corrplot(Cor[1:ncol(PC), (ncol(PC) + 1):ncol(Cor)], p.mat = Cor_fdr[1:ncol(PC), (ncol(PC) + 1):ncol(Cor)], insig = "label_sig", sig.level = sig_level, pch.col = "white",tl.pos = "lt",tl.col = "black", tl.srt = 45, tl.cex = 2, cl.cex = 2)
# corrplot(Cor[(ncol(PC) + 1):ncol(Cor),(ncol(PC) + 1):ncol(Cor)],method="ellipse",tl.pos = "lt",tl.col = "black", tl.srt = 45, addCoef.col = "darkgrey",
#          tl.cex = 2, cl.cex = 2, number.cex = 2)
# corrplot(Cor[(ncol(PC) + 1):ncol(Cor),(ncol(PC) + 1):ncol(Cor)], p.mat = Cor_fdr[(ncol(PC) + 1):ncol(Cor),(ncol(PC) + 1):ncol(Cor)], insig = "label_sig", sig.level = sig_level, pch.col = "white",tl.pos = "lt",tl.col = "black", tl.srt = 45, tl.cex = 2, cl.cex = 2)
# dev.off()

### Select covariates ###
## I know that Batch/Cortex/Region/BrainBank are correlated

Cov_pool
# [1] "Sex"               "Age"               "Diagnosis"         "Batch2_Frontal"   
# [5] "Batch2_Temporal"   "ABN"               "NICHD"             "valid_interaction"
# [9] "duplicate"         "trans_interaction" "cis_interaction"   "cis_shortRange"   
# [13] "cis_longRange" 

## First include all candidate covariates that cor > 0.4 with PC1-PC4 and that are not significantly correlated with each other.
Cov_pool[sapply(Cov_pool, function(x) any(abs(Cor[1:4,x]) > 0.4))] # dropped Batch2_Temporal, NICHD, valid_interaction

# Prioritize biological before technical covariate, as well as significant ones by FDR 
test_row = which(rownames(Cor_sig) == "Diagnosis")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # none.
# Include DiagnosisASD

test_row = which(rownames(Cor_sig) == "Sex")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # none.
# Include Sex

test_row = which(rownames(Cor_sig) == "duplicate")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # Batch2_Frontal, ABN
test_row = which(rownames(Cor_sig) == "Batch2_Frontal")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # ABN, duplicate, read_depth
test_row = which(rownames(Cor_sig) == "ABN")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # Batch2_Frontal, duplicate

sum(abs(Cor[1:3,which(colnames(Cor) == "ABN")])) # 1.190666
sum(abs(Cor[1:3,which(colnames(Cor) == "Batch2_Frontal")])) # 0.946051
sum(abs(Cor[1:3,which(colnames(Cor) == "duplicate")])) # 0.805376
# Include ABN while exclude Batch2_Frontal or duplicate

test_row = which(rownames(Cor_sig) == "trans_interaction")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # cis_interaction, cis_shortRange, cis_longRange

sum(abs(Cor[1:3,which(colnames(Cor) == "trans_interaction")])) # 1.036021
sum(abs(Cor[1:3,which(colnames(Cor) == "cis_interaction")])) # 1.036021
sum(abs(Cor[1:3,which(colnames(Cor) == "cis_shortRange")])) # 0.7483016
sum(abs(Cor[1:3,which(colnames(Cor) == "cis_longRange")])) # 1.096212
# If I were to include any, it should be cis_longRange. But this is sort of connected to IS, which is negatively correlated with contact freq bw neibouring TADs. So I'm not sure I should include any of these technical covariates.

test_row = which(rownames(Cor_sig) == "Age")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # none.
# Include Age

test_row = which(rownames(Cor_sig) == "Batch2_Temporal")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # none.
# Include Batch2_Temporal

test_row = which(rownames(Cor_sig) == "NICHD")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # none.
# Include NICHD (although it has p<0.05 cor with Age)

test_row = which(rownames(Cor_sig) == "valid_interaction")
picard_idx = which(Cor_sig[test_row,] < p_cor_threshold)
(picard_cor = colnames(Cor_sig)[picard_idx]) # none.
# Include valid_interaction

## Check VIF
# Base model - same as 6_5_differential_ISnonsegdup_analysis_v3_afterGRC_TADbOnly.R
expression_lm = "lm(IS ~ Diagnosis + Age + Sex + ABN + Batch2_Temporal + valid_interaction + NICHD, data = cur_data)"
# All VIF < 2, GREAT
expression_lm = "lm(IS ~ Diagnosis + Age + Sex + ABN + Batch2_Temporal + valid_interaction + NICHD + cis_longRange, data = cur_data)" # final model
# All VIF < 2, GREAT

i=1
cur_data = IS_df[i,]
cur_data = as.data.frame(cbind(cur_data, Annot_numeric[,-1]))
colnames(cur_data)[1] = c("IS")

fit_infunction <- eval(parse(text = expression_lm))
(vif_df_infunction = ols_vif_tol(fit_infunction)) # VIF over 5 is warning sign

## Final model: 
expression_lm = "lm(IS ~ Diagnosis + Age + Sex + Batch2_Temporal + ABN + NICHD + valid_interaction + cis_longRange, data = cur_data)"

## Run linear regression - using linear mixed model, including random effect of subjects
library(nlme)
runlme <- function(thisdat,expression) {
  lm1 <- eval(parse(text=expression));
  lm1.summary = summary(lm1)
  tabOut <- lm1.summary$coefficients$fixed
  lm1.anova = anova(lm1)
  return(list(tabOut, lm1.anova))
}

expression_lm
expression_model = gsub("lm","lme",expression_lm)
(expression_model = gsub(",",", random=~1|Subject,", expression_model))

Annot_numeric$Subject = substr(Annot_numeric$Sample, 1, 5)
n = length(unlist(str_split(expression_model, "\\+")))
p = magnitude = matrix(nrow = nrow(IS_df), ncol = n) 

for (i in 1:nrow(IS_df)) {
  if (i %% 3e3 == 0) {print(paste0("Done ", i, "th loop"))}
  cur_data = IS_df[i,]
  cur_data = as.data.frame(cbind(cur_data, Annot_numeric[,-1]))
  colnames(cur_data)[1] = c("IS")
  lm1.out <- try(runlme(cur_data,expression_model),silent=F)
  
  if (substr(lm1.out[1],1,5)!="Error") {
    tabOut <- lm1.out[[1]]
    lm1.anova = lm1.out[[2]]
    magnitude[i,] <- tabOut[-1]
    p[i,] <- lm1.anova[-1,"p-value"]
  } else {
    cat('Error in LME of IS bin', i, rownames(IS_df)[i],'\n')
    cat('Setting P-value=NA,Beta value=NA, and SE=NA\n')
    magnitude[i,] <- p[i,] <- NA
  }
}
# 2023/07/03 11:19-11:21 PM 
length(which(is.na(p[,1]))) 
# 0 Error

tabOut
colnames(p) = colnames(magnitude) = names(tabOut)[-1]
rownames(p) = rownames(magnitude) = rownames(IS_df)

fdr = p.adjust(p[,1], method = "fdr") 
p = as.data.frame(p); magnitude = as.data.frame(magnitude)
diffIS = data.frame(Mean = apply(IS_df, 1, mean), Magnitude = magnitude$Diagnosis, Pval = p$Diagnosis, FDR = fdr)

e1 = unlist(str_split(expression_model, "~ "))[2]
(e2 = unlist(str_split(e1, ", data"))[1])
e3 = unlist(str_split(e2, ","))[1]
e3 = gsub("_", ".", e3)
(e3 = gsub(" \\+ ", "", e3)) # "DiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange"

save(p, magnitude, diffIS, file = paste0("p_magnitude_Bulk_lme",e3,"_includingTechRepsAndOutliers.rda"))
#lnames = load(paste0("p_magnitude_Bulk_lme",e3,"_includingTechRepsAndOutliers.rda"))
#lnames = load(paste0("p_magnitude_Bulk_lmeDiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interaction_includingTechRepsAndOutliers.rda"))

pos = str_locate_all(pattern = "\\+", e2)[[1]][,1]
if (length(pos) >= 4) {npos = pos[4]} else {npos = nchar(e2)}

pdf(paste0("HistPval_Bulk_lme",e3,"_includingTechRepsAndOutliers.pdf"), height = 5, width = 8)
hist(p[,1], breaks = 30, xlab = "p-value by Diagnosis", main = paste0("Linear mixed model: ", substr(e2,1,npos), "\n", substr(e2,npos+1,nchar(e2))))
dev.off()
# Still very enriched at p<0.05

range(p[,1], na.rm = T) # 0 to 1
length(which(p[,1] < 0.05)) # 2940 nominally significant TAD boundaries
range(diffIS$FDR, na.rm = T) # 0 to 1. Great! 

## MA plot, check whether bins with higher IS score tend to have increased deltaIS in ASD.
library(ggplot2)
library(tidyverse)
IS_FDR_threshold = 0.05
diffIS$Dysreg = ifelse(is.na(diffIS$FDR) | diffIS$FDR >= IS_FDR_threshold, "No significant change", ifelse(diffIS$FDR < IS_FDR_threshold & diffIS$Magnitude > 0, "Weaker in ASD", "Stronger in ASD"))
diffIS$Dysreg = factor(diffIS$Dysreg, levels = c("Weaker in ASD", "Stronger in ASD", "No significant change"))
diffIS = diffIS %>%
  arrange(desc(Dysreg)) 
table(diffIS$Dysreg)
# FDR < 0.05: 754 TAD boundaries become weaker, 297 become stronger
# FDR < 0.1: 1287 TAD boundaries become weaker, 545 become stronger
# FDR < 0.15: 1738 TAD boundaries become weaker, 751 become stronger
# FDR < 0.2: 2070 TAD boundaries become weaker, 964 become stronger
# All are consistent with down-reg of CTCF in ASD from ATAC-seq analysis! Use FDR < 0.05. 
  
TextSize = 5 # 5 pt, eg. text = element_text(size = TextSize)
PointSize = 1 # used as PointSize/2 or PointSize/3 in geom_point
AnnoSize = 1.8 # font 0.093 inch tall or 5 pt, used in annotate(size = AnnoSize) or geom_text(size = AnnoSize)
LegendSize = 0.5 # used in legend.key.size = unit(LegendSize, 'lines'),

pdf(paste0("MAplot_Bulk_IStadbonly_lme",e3,"_includingTechRepsAndOutliers_fdr",IS_FDR_threshold,".pdf"), width = 3.4, height = 2)
diffIS %>%
  ggplot(aes(x = Mean, y = Magnitude, col = Dysreg)) +
  # ggplot(aes(x = MeanCTL, y = Magnitude, col = Dysreg)) + # very similar to use Mean
  geom_point(size = PointSize/2) +
  geom_abline(slope = 0, intercept = 0, linetype = 2, linewidth = PointSize/4) +
  scale_color_manual(values = c("Stronger in ASD" = "red", "Weaker in ASD" = "blue", "No significant change" = "lightgrey"), labels = c(paste0("Weaker in ASD (", length(which(diffIS$Dysreg == "Weaker in ASD")), ")"), paste0("Stronger in ASD (", length(which(diffIS$Dysreg == "Stronger in ASD")), ")"), paste0("No significant change (", length(which(diffIS$Dysreg == "No significant change")), ")"))) + 
  labs(col = paste0("Number of TAD boundaries (FDR cutoff ", IS_FDR_threshold, ")")) +
  annotate("text", x = -7, y = 0.02, label = paste0(length(which(diffIS$Magnitude > 0)), " bins"), size = AnnoSize) +
  annotate("text", x = -7, y = -0.02, label = paste0(length(which(diffIS$Magnitude < 0)), " bins"), size = AnnoSize) +
  theme_bw() + # size = 2 gives 8 pt
  xlab("Average insulation score\nStrong TAD boundary <-> Weak TAD boundary") +
  ylab("Difference in insulation score\nStronger in ASD <-> Weaker in ASD") +
  ggtitle(paste0("Total ", nrow(diffIS), " bins adjacent to TAD boundaries (40kb resolution)")) + # TAD boundaries
  theme(legend.position = c(0.35,0.84), #, "none"
        text = element_text(size = TextSize),
        axis.text = element_text(size = TextSize), # required for axis text to be 5 pt
        title = element_text(size = TextSize),
        plot.title = element_text(hjust = 0.5, size = TextSize),
        # element_blank() removes grey grids but also axis ticks
        plot.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.text = element_text(size = TextSize),
        legend.key.size = unit(LegendSize, 'lines'),
        legend.spacing.y = unit(0.2, "lines"),
        legend.background = element_blank()) 
dev.off()
# Observations:
# 1) TAD boundaries that are relatively strong (with lower mean IS) become significantly weaker in ASD samples. This is consistent with Luppino et al 2020 Nat Genet finding: Check out slides 20230703_ASDdup15q_IS_update_notpresented.ppt
# 2) Note the shape of the MA plot showing a relationship b/w decrease in Average IS and increase in delta IS. 
plot(x = diffIS$Mean, y = diffIS$Magnitude)
summary(lm(Magnitude ~ Mean, data = diffIS)) # slope = -0.0039038, p = 3.3e-13
# 4) Most TAD boundary significant changes become weaker in ASD.
length(which(diffIS$Magnitude < 0)) # 5247
length(which(diffIS$Magnitude > 0)) # 5920 - weaker in ASD

### Statistical test on the distribution of ratio of number of bins with Magnitude > 0 vs bins with Magnitude < 0. Permutate the diagnosis labels.

# tmux attach -t CHIC
# qrsh -l h_data=10G,h_rt=72:00:00,highp
# module load R
# R
# setwd("/u/project/geschwind/jennybea/ASD_project_2ndbatch/Dup15q_Annot_temporary/ASD_temporary/")

## Current data
rm(list = ls())
library(tidyverse)
library(stringr)
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/differential_IS/v4_afterGRC_TADbOnly_includeTransCisInLm/")
lnames = load(paste0("p_magnitude_Bulk_lmeDiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange_includingTechRepsAndOutliers.rda")) # p magnitude diffIS
# length(which(diffIS$Magnitude > 0)) - length(which(diffIS$Magnitude < 0)) # 673

## Permutation distribution
# Load IS and covariates
lnames = load("IS_binsAdjacentToTADb.rda") # IS_df
#Annot_numeric = read.table("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/4_QCstat/Annot_numeric.txt", header = T)
Annot_numeric = read.table("Annot_numeric.txt", header = T) # On Hoffman2
Annot_numeric = Annot_numeric[,c(21, 1:2, 4, 6:10, 14:20)]
stopifnot(colnames(IS_df) == Annot_numeric$Sample)

# linear model
expression_lm = "lm(IS ~ Diagnosis + Age + Sex + Batch2_Temporal + ABN + NICHD + valid_interaction + cis_longRange, data = cur_data)"

## Run linear regression - using linear mixed model, including random effect of subjects
library(nlme)
runlme <- function(thisdat,expression) {
  lm1 <- eval(parse(text=expression));
  lm1.summary = summary(lm1)
  tabOut <- lm1.summary$coefficients$fixed
  lm1.anova = anova(lm1)
  return(list(tabOut, lm1.anova))
}

expression_model = gsub("lm","lme",expression_lm)
(expression_model = gsub(",",", random=~1|Subject,", expression_model))
e1 = unlist(str_split(expression_model, "~ "))[2]
(e2 = unlist(str_split(e1, ", data"))[1])
e3 = unlist(str_split(e2, ","))[1]
e3 = gsub("_", ".", e3)
(e3 = gsub(" \\+ ", "", e3)) # "DiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange"

Annot_numeric$Subject = substr(Annot_numeric$Sample, 1, 5)
Annot_numeric2 = Annot_numeric
n = length(unlist(str_split(expression_model, "\\+")))
p = magnitude = matrix(nrow = nrow(IS_df), ncol = n) 

set.seed(703)
B = 1000
quant_TADbMagnitude0 = as.data.frame(matrix(nrow = B, ncol = 8))
colnames(quant_TADbMagnitude0) = c("MagGt0", "MagLt0", "MagGt0FDR01", "MagLt0FDR01", "MagGt0FDR005", "MagLt0FDR005", "MagGt0FDR015", "MagLt0FDR015")

for (j in 1:B) {
  if (j %% 10 == 0) {print(j)}
  
  # randomly assign CTL/ASD to the 2 pairs of technical replicates
  idx_techrep = which(Annot_numeric2$Subject %in% Annot_numeric2$Subject[duplicated(Annot_numeric2$Subject)]) # 16 17 21 22
  Annot_numeric2$Diagnosis[idx_techrep] = rep(sample(c(0,1),length(idx_techrep)/2), each = 2)
  
  # permutate the other samples wo tech reps
  idx_norep = setdiff(1:nrow(Annot_numeric2), idx_techrep)
  n1 = length(unique(Annot_numeric$Subject[which(Annot_numeric$Diagnosis == 1)])) - length(which(Annot_numeric2$Diagnosis[idx_techrep] == 1))/2
  
  idx1 = sample(idx_norep, n1)
  Annot_numeric2$Diagnosis[idx1] = 1
  idx0 = setdiff(idx_norep, idx1)
  Annot_numeric2$Diagnosis[idx0] = 0
  
  # run lme
  for (i in 1:nrow(IS_df)) {
    if (i %% 3e3 == 0) {print(paste0("Done ", i, "th loop"))}
    cur_data = IS_df[i,]
    cur_data = as.data.frame(cbind(cur_data, Annot_numeric2[,-1]))
    colnames(cur_data)[1] = c("IS")
    lm1.out <- try(runlme(cur_data,expression_model),silent=F)
    
    if (substr(lm1.out[1],1,5)!="Error") {
      tabOut <- lm1.out[[1]]
      lm1.anova = lm1.out[[2]]
      magnitude[i,] <- tabOut[-1]
      p[i,] <- lm1.anova[-1,"p-value"]
    } else {
      cat('Error in LME of IS bin', i, rownames(IS_df)[i],'\n')
      cat('Setting P-value=NA,Beta value=NA, and SE=NA\n')
      magnitude[i,] <- p[i,] <- NA
    }
  }
  
  colnames(p) = colnames(magnitude) = names(tabOut)[-1]
  rownames(p) = rownames(magnitude) = rownames(IS_df)
  fdr = p.adjust(p[,1], method = "fdr")
  p = as.data.frame(p); magnitude = as.data.frame(magnitude)
  diffIS = data.frame(Mean = apply(IS_df, 1, mean), Magnitude = magnitude$Diagnosis, Pval = p$Diagnosis, FDR = fdr)
  
  # quantification
  quant_TADbMagnitude0[j,1] = length(which(diffIS$Magnitude > 0))
  quant_TADbMagnitude0[j,2] = length(which(diffIS$Magnitude < 0))
  quant_TADbMagnitude0[j,3] = length(which(diffIS$Magnitude > 0 & diffIS$FDR < 0.1))
  quant_TADbMagnitude0[j,4] = length(which(diffIS$Magnitude < 0 & diffIS$FDR < 0.1))
  quant_TADbMagnitude0[j,5] = length(which(diffIS$Magnitude > 0 & diffIS$FDR < 0.05))
  quant_TADbMagnitude0[j,6] = length(which(diffIS$Magnitude < 0 & diffIS$FDR < 0.05))
  print(quant_TADbMagnitude0[j,])
  quant_TADbMagnitude0[j,7] = length(which(diffIS$Magnitude > 0 & diffIS$FDR < 0.15))
  quant_TADbMagnitude0[j,8] = length(which(diffIS$Magnitude < 0 & diffIS$FDR < 0.15))
  print(quant_TADbMagnitude0[j,])
}
# 2023/07/03 11:47PM - 2023/07/04 2:10AM (B=50)
# 2023/07/10 7:45PM- 2023/07/12 9:27AM (B=1000, add FDR015) 

quant_TADbMagnitude0$ratioMag = quant_TADbMagnitude0$MagGt0/quant_TADbMagnitude0$MagLt0
quant_TADbMagnitude0$ratioSig01 = (quant_TADbMagnitude0$MagGt0FDR01 + 0.01)/(quant_TADbMagnitude0$MagLt0FDR01 + 0.01)
quant_TADbMagnitude0$ratioSig005 = (quant_TADbMagnitude0$MagGt0FDR005 + 0.01)/(quant_TADbMagnitude0$MagLt0FDR005 + 0.01)
quant_TADbMagnitude0$ratioSig015 = (quant_TADbMagnitude0$MagGt0FDR015 + 0.01)/(quant_TADbMagnitude0$MagLt0FDR015 + 0.01)
quant_TADbMagnitude0$deltaMag = quant_TADbMagnitude0$MagGt0 - quant_TADbMagnitude0$MagLt0
quant_TADbMagnitude0$deltaSig01 = quant_TADbMagnitude0$MagGt0FDR01 - quant_TADbMagnitude0$MagLt0FDR01
quant_TADbMagnitude0$deltaSig005 = quant_TADbMagnitude0$MagGt0FDR005 - quant_TADbMagnitude0$MagLt0FDR005
quant_TADbMagnitude0$deltaSig015 = quant_TADbMagnitude0$MagGt0FDR015 - quant_TADbMagnitude0$MagLt0FDR015

save(quant_TADbMagnitude0, file = paste0("5_v4_st2_quantTADbMagnitude0_permutateDiagnosis_lme",e3,"_includingTechRepsAndOutliers.rda"))

lnames = load(paste0("5_v4_st2_quantTADbMagnitude0_permutateDiagnosis_lmeDiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange_includingTechRepsAndOutliers.rda"))
e3 = "DiagnosisAgeSexBatch2.TemporalABNNICHDvalid.interactioncis.longRange"
B = 1000

pdf(paste0("PermutationRes_DeltaNumberOfTADbWith_MagnitudeGtVsLt0_or_SignificantFDR01or005ISchange_lme",e3,"_includingTechRepsAndOutliers.pdf"), width = 12, height = 4)
par(mfrow = c(1,3))

a = length(which(quant_TADbMagnitude0$deltaMag >= 5920 - 5247))
main_title = ifelse(a == 0, paste0("p < ", 1/B), paste0("p = ", a/B))
p1 = hist(quant_TADbMagnitude0$deltaMag, main = main_title, xlab = "Difference in the number of TAD boundaries\nthat become weaker vs. stronger", breaks = 30) +
  abline(v = 5920 - 5247, col = "red")

a = length(which(quant_TADbMagnitude0$deltaSig01 > 1287-545))
main_title = ifelse(a == 0, paste0("p < ", 1/B), paste0("p = ", a/B))
p2 = hist(quant_TADbMagnitude0$deltaSig01, main = main_title, xlab = "Difference in the number of TAD boundaries\nthat become significantly weaker vs. stronger (FDR < 0.1)", xlim = c(min(c(1287-545, min(quant_TADbMagnitude0$deltaSig01))), max(c(1287-545, max(quant_TADbMagnitude0$deltaSig)))), breaks = 10) + # the ratioSig = 301 (9/50) ones are forbidden significant changes, making p = 0.2
  abline(v = 1287-545, col =  "red")

a = length(which(quant_TADbMagnitude0$deltaSig005 > 754-297))
main_title = ifelse(a == 0, paste0("p < ", 1/B), paste0("p = ", a/B))
p3 = hist(quant_TADbMagnitude0$deltaSig005, main = main_title, xlab = "Difference in the number of TAD boundaries\nthat become significantly weaker vs. stronger (FDR < 0.05)", xlim = c(min(c(754-297, min(quant_TADbMagnitude0$deltaSig005))), max(c(754-297, max(quant_TADbMagnitude0$deltaSig005)))), breaks = 10) + # the ratioSig = 301 (9/50) ones are forbidden significant changes, making p = 0.2
  abline(v = 754-297, col =  "red")

dev.off()
# Observation: more TAD boundaries get significantly weaker than stronger. (p = 0.005 with FDR < 0.1 or 0.05)


