## Goal/Question: Are there genetic variants at CTCF-bound distal (and promoter) ATAC of ASD down-reg genes? Especially SFARI genes or other nervous system/synaptic genes?
# This is to explain the reduction in CTCF binding score and down-regulation of target genes

###############     
### Outline ###
###############     

#### 1. Identify ATAC peaks bound by CTCF with down-reg GE
#### 2. Run motifbreakR to find motif disrupting/altering SNPs at these CTCF-bound ATAC region 
#### 3. Use WGS or VarCA to identify genetic variants in ASD vs. CTL at these motif disrupting/altering SNPs

##############     
### Script ###
##############     
rm(list = ls())
options(stringsAsFactors = F)
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_14_GeneticVariants_at_CTCFboundATAC_withGEdownreg/")

#### 1. Identify ATAC peaks bound by CTCF with down-reg GE
### 1) Identify ATAC peaks bound by CTCF
# Load the ATAC peaks with any of the three Jaspar2022 hs CTCF motifs, generated by 10_3_7_Link_DiffTFbsAndge_to_ATACchange_Jaspar2022_v2heatmapATACregressed.R
CTCF_bound1 = read.table(paste0("../10_TOBIAS/ind_BINDetect_Jaspar2022/TFoi_bound_ATACpeaks/CTCF-MA1930.1_BoundInAnySample.txt"), header = T)
CTCF_bound2 = read.table(paste0("../10_TOBIAS/ind_BINDetect_Jaspar2022/TFoi_bound_ATACpeaks/CTCF-MA0139.1_BoundInAnySample.txt"), header = T)
CTCF_bound3 = read.table(paste0("../10_TOBIAS/ind_BINDetect_Jaspar2022/TFoi_bound_ATACpeaks/CTCF-MA1929.1_BoundInAnySample.txt"), header = T)
tmp = inner_join(CTCF_bound1, CTCF_bound2)
CTCF_bound = inner_join(tmp, CTCF_bound3) # 22242, match the number on UpSetR
colnames(CTCF_bound) = c("chr", "start", "end")
CTCF_bound$ATACpeak = paste0(CTCF_bound$chr, "_", CTCF_bound$start, "_", CTCF_bound$end)

rm(CTCF_bound1, CTCF_bound2, CTCF_bound3)

### 2) Link ATAC peaks to genes
lnames = load("../10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC01.rda") # "sig_CorATAC" "sig_CorATAC_uniq" "promATAC"
library(readxl)
Jill_DEG = read_excel("/Users/dhglab/Documents/Documents/Geschwind_lab/LAB/Database_download/31_Jill_ASD_pancortical_RNAseq_datasets/logFC_SupplementaryTable3.xlsx")

colnames(sig_CorATAC_uniq)[1] = "ATACpeak"
CTCF_bound_promATAC = left_join(CTCF_bound, promATAC[,c("ATACpeak", "ensembl_gene_id")])
CTCF_bound_promATAC = CTCF_bound_promATAC[complete.cases(CTCF_bound_promATAC),]
CTCF_bound_distalATAC = left_join(CTCF_bound, sig_CorATAC_uniq[,c("ATACpeak", "ensembl_gene_id")])
CTCF_bound_distalATAC = CTCF_bound_distalATAC[complete.cases(CTCF_bound_distalATAC),]

CTCF_bound_promATAC$ATACtype = "promoter"
CTCF_bound_distalATAC$ATACtype = "distal"
CTCF_bound_ATAC = rbind(CTCF_bound_promATAC, CTCF_bound_distalATAC) # 19457 rows

### 3) Subset for down-regulated genes
CTCF_bound_ATAC$WholeCortex_ASD_logFC = Jill_DEG$WholeCortex_ASD_logFC[match(CTCF_bound_ATAC$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]
CTCF_bound_ATAC$WholeCortex_ASD_FDR = Jill_DEG$WholeCortex_ASD_FDR[match(CTCF_bound_ATAC$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]

CTCF_bound_ATAC_DEGdown = CTCF_bound_ATAC[CTCF_bound_ATAC$WholeCortex_ASD_logFC < 0 & CTCF_bound_ATAC$WholeCortex_ASD_FDR < 0.05,] # 2798 rows
CTCF_bound_ATAC_DEGdown$chr = gsub("chr","",CTCF_bound_ATAC_DEGdown$chr)
CTCF_bound_ATAC_DEGdown_gr = makeGRangesFromDataFrame(CTCF_bound_ATAC_DEGdown)

save(CTCF_bound_ATAC, CTCF_bound_ATAC_DEGdown, CTCF_bound_ATAC_DEGdown_gr, file = "CTCF_bound_ATAC_gr.rda")

## Now go to hoffman2 to work on SNPlocs.xxx.xxx and MotifbreakR (R/4.2.2), because my MAC does not have the capacity to run the programs.

#qrsh -l h_data=20G,h_rt=8:00:00 # 10G too small for snpsByOverlaps with SNPlocs.Hsapiens.dbSNP155.GRCh37
# [suggested by Hoffman2 help desk, useful!] In your $HOME/.bashrc, you should remove (or comment out) the lines in between 'conda initialize' AND in $HOME/.bash_profile you should remove (or comment out) the export PATH line that adds the miniconda bin directory. Then try installing your R packages.
#module load R/4.2.2
#R
rm(list = ls())
setwd("/u/project/geschwind/jennybea/ASD_project_2ndbatch/ATAC/10_3_14_GeneticVariants_at_CTCFboundATAC_withGEdownreg/")
lnames = load("CTCF_bound_ATAC_gr.rda") # CTCF_bound_ATAC, CTCF_bound_ATAC_DEGdown, CTCF_bound_ATAC_DEGdown_gr

#### 2. Run motifbreakR to find motif disrupting/altering SNPs at these CTCF-bound ATAC region 

## st1. generate snp_info
# BiocManager::install("motifbreakR") # successful with R/4.2.2, update all.
library(motifbreakR)
library(BSgenome)
# BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")  # successful on all R versions
library(BSgenome.Hsapiens.UCSC.hg19)
available.SNPs()
#BiocManager::install("SNPlocs.Hsapiens.dbSNP155.GRCh37")
library(SNPlocs.Hsapiens.dbSNP155.GRCh37)

CTCFboundDEGdownSNPs = snpsByOverlaps(SNPlocs.Hsapiens.dbSNP155.GRCh37, CTCF_bound_ATAC_DEGdown_gr) # On hoffman2 R/4.1.0 2022/12/21 01:41-01:43AM 
save(CTCFboundDEGdownSNPs, file = "CTCFboundDEGdownSNPs_dbSNP155GRCh37.rda") 
lnames = load("CTCFboundDEGdownSNPs_dbSNP155GRCh37.rda") # CTCFboundDEGdownSNPs
CTCFboundDEGdownSNPs_df = as.data.frame(CTCFboundDEGdownSNPs)
dim(CTCFboundDEGdownSNPs_df) # 1674713 positions and 5 metadata columns: "seqnames","pos","strand","RefSNP_id" 

# snps.mb <- snps.from.rsid(rsid = CTCFboundDEGdownSNPs_df$RefSNP_id,
#                           dbSNP = SNPlocs.Hsapiens.dbSNP155.GRCh37,
#                           search.genome = BSgenome.Hsapiens.UCSC.hg19) # 777 ranges
# save(snps.mb, file = "snps_mb_CTCFboundDEGdownSNPs_dbSNP155GRCh37.rda")
# 2022/12/21 01:45-01:?PM (taking forever)

## Split by chr
unique(CTCFboundDEGdownSNPs_df$seqnames) # 1:X
for (i in unique(CTCFboundDEGdownSNPs_df$seqnames)) {
  chri_CTCFboundDEGdownSNPs_df = CTCFboundDEGdownSNPs_df[CTCFboundDEGdownSNPs_df$seqnames == i,]
  print(c(i, dim(chri_CTCFboundDEGdownSNPs_df)))
  save(chri_CTCFboundDEGdownSNPs_df, file = paste0("CTCFboundDEGdownSNPs_dbSNP155GRCh37_", i, ".rda"))
}

## Run snps.from.rsid for each chr
library(tidyverse)
chr_count = as.data.frame(table(CTCFboundDEGdownSNPs_df$seqnames)) # 1:X
chr_count = chr_count %>%
  arrange(Freq)
chr_count = chr_count[chr_count$Freq > 0,]
unique(chr_count$Var1) # 21 X 18 13 14 22 6 4 20 8 5 15 10 | 7 3 9 12 2 | 11 17 16 1  19

#for (i in unique(chr_count$Var1)) {
#for (i in rev(unique(chr_count$Var1))) {
#for (i in unique(chr_count$Var1)[14:23]) {
for (i in unique(chr_count$Var1)[17:19]) {
    if (! file.exists(paste0("snps_mb_CTCFboundDEGdownSNPs_dbSNP155GRCh37_",i,".rda"))) {
    lnames = load(paste0("CTCFboundDEGdownSNPs_dbSNP155GRCh37_", i, ".rda")) # chri_CTCFboundDEGdownSNPs_df
    print(c(i, dim(chri_CTCFboundDEGdownSNPs_df)))
    
    snps.mb <- snps.from.rsid(rsid = chri_CTCFboundDEGdownSNPs_df$RefSNP_id,
                              dbSNP = SNPlocs.Hsapiens.dbSNP155.GRCh37,
                              search.genome = BSgenome.Hsapiens.UCSC.hg19) # 777 ranges
    save(snps.mb, file = paste0("snps_mb_CTCFboundDEGdownSNPs_dbSNP155GRCh37_",i,".rda"))
    rm(snps.mb)
    gc()
  }
}
# 2022/12/21 ?-4:58PM: 1 finished. 
# 2022/12/21 03:48-6:35PM: unique(chr_count$Var1) 21,X,18,13,14,22 finished. At 6 cannot allocate vector of size 8Gb
# 2022/12/21 05:46-9:24PM: rev(unique(chr_count$Var1)) 19 (6:52PM), 16,17,11
# 2022/12/21 06:14-8:44PM: unique(chr_count$Var1) 6,4,20,8,5,15,10
# 2022/12/21 06:53-8:20PM: unique(chr_count$Var1)[14:23] 7,3,9,2 (stop)
# 2022/12/21 07:25-8:34PM: unique(chr_count$Var1)[17:19] 12,2 finished. At 11 error cannot allocate vector of size 8.0 Gb

# module load R/4.1.0 # for st3, but do it now cuz st3 needs to load st2
rm(list = ls())
setwd("/u/project/geschwind/jennybea/ASD_project_2ndbatch/ATAC/10_3_14_GeneticVariants_at_CTCFboundATAC_withGEdownreg/")
library(motifbreakR)
library(BSgenome)
library(BSgenome.Hsapiens.UCSC.hg19)

## st2. generate motif_lib - only able to work on R/4.1.0
lnames = load("../10_3_13_GeneticVariants_at_CTCFpromoter/mf_jaspar2022hs.rda") # mf

## st3. compute snp-motif scores (st4 filter for strong effect SNPs in the loop)

#lnames = load("../10_3_13_GeneticVariants_at_CTCFpromoter/snps_mb_CTCFpromSNPs_dbSNP151GRCh38.rda")
#results = motifbreakR(snpList = snps.mb, filterp = TRUE, pwmList = mf, threshold = 1e-4) # mf is from jaspar 2022
# also fail with R/4.2.2, but successful with R/4.1.0

#for (i in c(19)) {
#for (i in c(2:1)) {
#for (i in c(16:17)) {
#for (i in c(6:10)) {
#for (i in c(16:19)) {
#for (i in c(11:15)) {
#for (i in rev(c(6:10))) {
for (i in rev(c(1:22, "X"))) {
#for (i in c(5:1)) {
#for (i in c(2:1)) {
  if (! file.exists(paste0("motifbreakRresults_jaspar2022hsmotifs_CTCFboundDEGdownSNPs_dbSNP155GRCh37_",i,".rda"))) {
    print(i)
    lnames = load(paste0("snps_mb_CTCFboundDEGdownSNPs_dbSNP155GRCh37_",i,".rda")) # snps.mb
    print(length(snps.mb)) # 119924 for chr2
    results = motifbreakR(snpList = snps.mb, filterp = TRUE, 
                          pwmList = mf, # mf is from jaspar 2022
                          threshold = 1e-4)
    # R/4.2.2 Error in d$value$value : $ operator is invalid for atomic vectors
    
    save(results, file = paste0("motifbreakRresults_jaspar2022hsmotifs_CTCFboundDEGdownSNPs_dbSNP155GRCh37_",i,".rda"))
    
    ## st4. Filter for "strong" predicted effects
    results_names = names(results) # 2678 rsids
    uniq_results_names = unique(names(results)) # 568 rsids
    
    df_results = as.data.frame(unname(results)) # 2678 obs x 24 columns
    strong_results = df_results[df_results$effect == "strong", ] # 1831 rows
    length(unique(strong_results$SNP_id)) # 449 SNPs
    save(results, df_results, strong_results, file = paste0("STRONGmotifbreakRresults_jaspar2022hsmotifs_CTCFboundDEGdownSNPs_dbSNP155GRCh37_",i,".rda"))
    
    rm(results, df_results, strong_results)
    gc()
  }
}
# 2022/12/22 00:27-04:30AM c(5:1) 5,4,3
# 2022/12/21 9:38PM-00:43AM rev(c(1:22, "X")) X,22,21,20
# 2022/12/21 9:42PM-6:15AM rev(c(6:10)) 10,9,8,7,6
# 2022/12/22 00:56-09:26AM, 2:12-7:32AM c(15:11) 15,14,13,12,11
# 2022/12/22 07:35-08:12AM c(18:16)  18
# 2022/12/22 03:16-PM, 4:17-?PM c(17:16) 17, 16
# 2022/12/22 03:16-5:36PM c(2:1) 2
# 2022/12/22 03:20-PM 19

# qsub for chr that can't be finished on qrsh node. run 10_3_14_qsub_motifbreakR.sh

#### 3. Use WGS or VarCA to identify genetic variants in ASD vs. CTL at these motif disrupting/altering SNPs

rm(list = ls())
options(stringsAsFactors = F)
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_14_GeneticVariants_at_CTCFboundATAC_withGEdownreg/")

STRONG_files = list.files(pattern = "^STRONGmotifbreakRresults_.*.rda")
STRONG_all = matrix(nrow = 0, ncol = 26)
lnames = load("AllChr_STRONGmotifbreakRresults_jaspar2022hsmotifs_CTCFboundDEGdownSNPs_dbSNP155GRCh37.rda") # STRONG_all

### 1) WGS
## Prepare query SNP file
for (i in STRONG_files) {
  #if (file.exists(paste0("uniqSNPs_", gsub(".rda", ".txt",i)))) { # ! 
    print(i)
    lnames = load(i) # "results, df_results, strong_results"
    
    strong_results$Chr_Pos = paste0(strong_results$seqnames, "_", strong_results$start)
    strong_results$motifPos_start = sapply(strong_results$motifPos, function(x) unlist(x)[1])
    strong_results$motifPos_end = sapply(strong_results$motifPos, function(x) unlist(x)[2])
    
    if (ncol(strong_results) == ncol(STRONG_all) + 1) {
      STRONG_all = rbind(STRONG_all, strong_results[,-10])
    } else {
      STRONG_all = rbind(STRONG_all, strong_results[,colnames(STRONG_all)])
    }
    
    strong_results$seqnames = gsub("chr", "", strong_results$seqnames)
    strong_results = unique(strong_results[,c(1:7,ncol(strong_results)-1)])
    write.table(strong_results, file = paste0("uniqSNPs_", gsub(".rda", ".txt",i)), quote = F, sep = "\t", row.names = F, col.names = F)
  #}
}

colnames(STRONG_all)[c(24, 1:9, 25:26, 10:23)]
STRONG_all = STRONG_all[,c(24, 1:9, 25:26, 10:23)]

save(STRONG_all, file = "AllChr_STRONGmotifbreakRresults_jaspar2022hsmotifs_CTCFboundDEGdownSNPs_dbSNP155GRCh37.rda")

# transfer the txt file to /u/project/geschwind/jennybea/ASD_project_2ndbatch/ATAC/10_3_14_GeneticVariants_at_CTCFboundATAC_withGEdownreg/

## Extract VCF that match the SNPs
# Run script 10_3_14_st2_WGS_vcf_includingAN08873.sh

## Load the extracted VCF
VCF_files = list.files(pattern = ".*_WGS.vcf")
VCF = read.table(VCF_files[1], comment.char = "", header = T)
for (i in VCF_files[2:length(VCF_files)]) {
  tmp = read.table(i, comment.char = "", header = T)
  VCF = rbind(VCF, tmp)
}
dim(VCF) # 20535 x 35
unique(VCF$X.CHROM) # 1:22, X

idx = apply(VCF, 1, function(x) which(! startsWith(as.character(x), "0/0"))) 
idx = lapply(idx, function(x) setdiff(x, c(1:9)))
idx = lapply(idx, function(x) x - 9)
range(lengths(idx)) # 0-26
tmp = which(lengths(idx) > 0 & lengths(idx) < 26) # 9742 SNPs show variation.
VCF$Chr_Pos = paste0(VCF$X.CHROM, "_", VCF$POS)
VCF_vary = VCF[which(lengths(idx) > 0 & lengths(idx) < 26),]
VCF_vary = VCF_vary[,c(36, 1:35)]

## Check whether variant calls are consistent between BA regions
VCF_Subject = gsub("_.*","",colnames(VCF)[10:35]) # There are BA regions from the same subject
(which(duplicated(VCF_Subject))) # 2  4  6 10 12 14 19 21 23 26. 
unique(VCF_vary$FORMAT) # GT always in the first place

library(reshape2)
library(stringr)
VCF_vary_melt = melt(VCF_vary[,c(1:6, 11:36)], id.vars = c(1:6))
VCF_vary_melt$subject = gsub("_.*", "", VCF_vary_melt$variable)
VCF_vary_melt$GT = sapply(VCF_vary_melt$value, function(x) unlist(str_split(x, ":"))[1])
unique(VCF_vary_melt$GT) # "0/0" "1/1" "0/1" "./."

VCF_vary_melt_DupIdx = which(duplicated(VCF_vary_melt[,c(1:6, ncol(VCF_vary_melt)-1)])) # 97420
VCF_vary_melt_DupIdx2 = which(duplicated(VCF_vary_melt[,c(1:6, ncol(VCF_vary_melt) - 1, ncol(VCF_vary_melt))])) # 95805
all(VCF_vary_melt_DupIdx2 %in% VCF_vary_melt_DupIdx) # T
VCF_vary_melt_DupIdx3 = setdiff(VCF_vary_melt_DupIdx, VCF_vary_melt_DupIdx2) # 1615 potentially different calls between subject

inconsistent_calls = matrix(nrow = 0, ncol = ncol(VCF_vary_melt))
library(tidyverse)
for (i in VCF_vary_melt_DupIdx3) {
  this_sample = VCF_vary_melt[i,]
  all_samples = left_join(this_sample[,-c(7,8,10)], VCF_vary_melt) # "variable","value","GT"
  if (nrow(all_samples) == 2 & "./." %in% all_samples$GT) {
    next
  } else if (nrow(all_samples) == 2 & ! "./." %in% all_samples$GT) {
    inconsistent_calls = rbind(inconsistent_calls, all_samples)
  } else {
    print(i)
    break
  }
}
dim(inconsistent_calls) # 1170 x 10
unique(inconsistent_calls$GT) # "0/1" "0/0" "1/1"
unique(VCF_vary_melt$variable[grepl("CBL", VCF_vary_melt$variable)]) # 13 CBL samples
unique(as.character(inconsistent_calls$variable)) # 10 pairs of CBL-cortical samples
table(as.character(inconsistent_calls$variable)) # Each of these samples have 39-85 variants called differently bw CBL and CORTICAL

# Are these somatic mutation?
unique(VCF$FILTER) # PASS. Possibly are somatic mutations

inconsistent_id = paste0(inconsistent_calls$X.CHROM, "_", inconsistent_calls$POS, "_", inconsistent_calls$variable)
all_id = paste0(VCF_vary_melt$X.CHROM, "_", VCF_vary_melt$POS, "_", VCF_vary_melt$variable)
idx_inconsistent = which(all_id %in% inconsistent_id)
VCF_vary_melt$somatic = F
VCF_vary_melt$somatic[idx_inconsistent] = T

## Do the non-somatic and somatic variants occur in ASD or CTL?
lnames = load("../3_QC/BiolTechCov_and_QC.rda") # df_wAllCov
VCF_vary_melt$Diagnosis = df_wAllCov$Diagnosis[match(VCF_vary_melt$subject, df_wAllCov$Subject_ID)]
which(is.na(VCF_vary_melt$Diagnosis)) # integer(0)

colnames(VCF)[10:35] # CBL not always before CORTICAL
VCF_Subject_Diagnosis = df_wAllCov$Diagnosis[match(VCF_Subject, df_wAllCov$Subject_ID)]
idx_dupSubject = which(duplicated(VCF_Subject)) # 10
table(VCF_Subject_Diagnosis[-idx_dupSubject]) # 7 ASD, 9 CTL
#dup_samples = colnames(VCF)[idx_dupSubject+9]
dup_samples = colnames(VCF)[grepl(paste(unique(VCF_Subject[idx_dupSubject]), collapse = "|"), colnames(VCF)) & grepl("CBL", colnames(VCF))]
dup_samples

# a) Is there a difference in the Number of somatic variants each ASD or CTL sample bear?
tmp = VCF_vary_melt[VCF_vary_melt$somatic == T & ! VCF_vary_melt$variable %in% dup_samples & ! VCF_vary_melt$GT %in% c("0/0"),] # , "./."
unique(tmp$GT) # "0/1" "1/1"

tmp_sum = tmp %>%
  group_by(subject, Diagnosis) %>%
  summarise(count_01 = sum(GT == "0/1"), count_11 = sum(GT == "1/1"), count_01or11 = sum(GT %in% c("0/1", "1/1"))) %>%
  ungroup()
# sum(tmp$subject == "AN00493" & tmp$GT %in% c("0/1", "1/1")) # confirm correct
tmp_sum_melt = melt(tmp_sum, id.vars = c(1,2))

library(ggplot2)
pdf("Number_of_SOMATICvariants_wGT01or11_inASDvsCTL.pdf",height = 5, width = 8)
tmp_sum_melt %>%
  ggplot(aes(x = Diagnosis, y = value)) +
  geom_jitter(aes(col = Diagnosis), position = position_jitter(w = 0.1, h = 0)) +
  theme_bw() +
  facet_wrap(. ~ variable, scales = "free_y", labeller = as_labeller(c("count_01" = "Gennotype = 0/1", "count_11" = "Genotype = 1/1", "count_01or11" = "Genotype != 0/0")))
dev.off()
# Observation: Only 3 ASD but 7 CTL samples show "somatic" variants - likely false callings. No significant difference in the total number of variants with 0/1 or 1/1 between CTL and ASD.

# b) Is there a difference in the Number of non-somatic variants each ASD or CTL sample bear?
HOMO = as.data.frame(table(VCF_vary_melt$Chr_Pos[VCF_vary_melt$GT == "1/1" & ! VCF_vary_melt$variable %in% dup_samples])) # 1875 SNPs with 1/1 genotype
range(HOMO$Freq) # 1-15
hist(HOMO$Freq) # Most only exist in only 1 out of the 16 subjects. Can't set a threshold for whether the 1/1 GT is loss or gain of motif binding from the GT frequency

tmp = VCF_vary_melt[VCF_vary_melt$somatic == F & ! VCF_vary_melt$variable %in% dup_samples & ! VCF_vary_melt$GT %in% c("0/0"),] # , "./."
unique(tmp$GT) # "0/1" "1/1"

tmp_sum = tmp %>%
  group_by(subject, Diagnosis) %>%
  summarise(count_01 = sum(GT == "0/1"), count_11 = sum(GT == "1/1"), count_na = sum(GT == "./."), count_01or11 = sum(GT %in% c("0/1", "1/1"))) %>%
  ungroup()
# sum(tmp$subject == "AN00493" & tmp$GT %in% c("0/1", "1/1")) # confirm correct
tmp_sum_melt = melt(tmp_sum, id.vars = c(1,2))

pdf("Number_of_variants_wGT01or11_inASDvsCTL.pdf",height = 5, width = 8)
tmp_sum_melt %>%
  ggplot(aes(x = Diagnosis, y = value)) +
  geom_jitter(aes(col = Diagnosis), position = position_jitter(w = 0.1, h = 0)) +
  theme_bw() +
  facet_wrap(. ~ variable, scales = "free_y", labeller = as_labeller(c("count_01" = "Gennotype = 0/1", "count_11" = "Genotype = 1/1", "count_na" = "Genotype = ./.", "count_01or11" = "Genotype != 0/0")))
dev.off()
# Observation: 
# CTL samples seem to have more 1/1 than ASD. ASD samples seem to have more ./. calls than CTL. Need to normalize to the total number of GT called as non-./. in CTL vs. ASD.

# c) Any variant preferably show up in ASD?
tmp = VCF_vary_melt[VCF_vary_melt$somatic == F & ! VCF_vary_melt$variable %in% dup_samples,]
unique(tmp$GT) # "0/0" "0/1" "./." "1/1"

tmp_sum = tmp %>%
  group_by(Chr_Pos, REF, ALT, Diagnosis) %>%
  summarise(count_00 = sum(GT == "0/0"), count_01 = sum(GT == "0/1"), count_11 = sum(GT == "1/1"), count_na = sum(GT == c("./."))) %>%
  ungroup()
# sum(tmp$subject == "AN00493" & tmp$GT %in% c("0/1", "1/1")) # confirm correct

tmp_sum$n = apply(tmp_sum[,(ncol(tmp_sum) - 3):ncol(tmp_sum)], 1, sum)
all(tmp_sum$n[tmp_sum$Diagnosis == "ASD"] == 7) # F
#idx_ASD = which(tmp_sum$n != 7 & tmp_sum$Diagnosis == "ASD")
#tmp_sum[idx_ASD[1],]

tmp_sum$count_0 = (tmp_sum$count_00*2 + tmp_sum$count_01*1)/(tmp_sum$n*2)
tmp_sum$count_1 = (tmp_sum$count_11*2 + tmp_sum$count_01*1)/(tmp_sum$n*2)

tmp_sum_count1 = dcast(tmp_sum[,c(1:4,ncol(tmp_sum))], Chr_Pos + REF + ALT ~ Diagnosis)
tmp_sum_count1$diff = tmp_sum_count1$ASD - tmp_sum_count1$CTL
tmp_sum_count1 = tmp_sum_count1[tmp_sum_count1$diff != 0,] # 5817 rows

range(tmp_sum_count1$diff) # -0.6 to 0.6
# Take 5% extremes on both ends
tmp_idx = rank(tmp_sum_count1$diff)
th1 = round(0.025*nrow(tmp_sum_count1))
th2 = round(0.975*nrow(tmp_sum_count1))
c1 = range(tmp_sum_count1$diff[tmp_idx < th1])[2]
c2 = range(tmp_sum_count1$diff[tmp_idx > th2])[1]

pdf("Histogram_diff_in_alt_allele_freq_ASDminusCTL.pdf", height = 5, width = 8)
hist(tmp_sum_count1$diff, breaks = 40, xlab = "Difference in alt allele frequency (ASD - CTL)", main = paste0("5% cutoffs: ", round(c1,2), ", ", round(c2,2))) # bimodal distribuion with peaks at -0.06~-0.04 and 0.06~0.08
abline(v = c(c1,c2), col = "red", lwd = 2)
dev.off()
sig_count1 = tmp_sum_count1[tmp_idx < th1 | tmp_idx > th2,] # 931 rows, this is pval < 0.1, too loose

tmp_sum_count1$p = sapply(tmp_sum_count1$diff, function(x) ifelse(x > 0, sum(tmp_sum_count1$diff > x)/nrow(tmp_sum_count1)*2, sum(tmp_sum_count1$diff < x)/nrow(tmp_sum_count1)*2))
tmp_sum_count1$fdr = p.adjust(tmp_sum_count1$p)
range(tmp_sum_count1$fdr) # 0 to 1
sig_count1_FDRbased = tmp_sum_count1[tmp_sum_count1$fdr < 0.1,] # 2 rows, too few

sig_count1_VOLCANObased = tmp_sum_count1[tmp_sum_count1$diff < -0.3 | tmp_sum_count1$diff > 0.3,] # 216 rows
sig_count1_VOLCANOpbased = tmp_sum_count1[tmp_sum_count1$p < 0.01,] # 98 rows
c1_2 = range(sig_count1_VOLCANOpbased$diff[sig_count1_VOLCANOpbased$diff > 0])[1] # diff > 0.365
c2_2 = range(sig_count1_VOLCANOpbased$diff[sig_count1_VOLCANOpbased$diff < 0])[2] # diff < -0.365

pdf("Volcano_diff_in_alt_allele_freq_ASDminusCTL.pdf", height = 5, width = 8)
plot(tmp_sum_count1$diff, -log10(tmp_sum_count1$p), pch = 19, col = alpha("black", 0.2), xlab = "Difference in alt allele frequency (ASD - CTL)", main = "5% and 1% cutoffs", ylab = "-log10(p-value)")
abline(v = c(c1,c2), col = "red", lwd = 2) # 5% cutoffs
#abline(v = c(-0.28,0.28), col = "red", lwd = 2)
text(x = c1, y = 2.5, labels = paste0("x = ", round(c1,2)))
text(x = c2, y = 2.5, labels = paste0("x = ", round(c2,2)))
#abline(v = c(-0.3,0.3), col = "red", lwd = 2) # 2.5% cutoffs
#text(x = -0.3, y = 3, labels = "x = -0.3") # based on the plot
#text(x = 0.3, y = 3, labels = "x = 0.3") # based on the plot
#range(tmp_sum_count1$p[tmp_sum_count1$diff > 0.3]) # p< 0.0255
#range(tmp_sum_count1$p[tmp_sum_count1$diff < -0.3]) # p< 0.02
abline(v = c(c1_2,c2_2), col = "red", lwd = 2) # 1% cutoffs
text(x = c1_2, y = 3, labels = paste0("x = ", round(c1_2,2)))
text(x = c2_2, y = 3, labels = paste0("x = ", round(c2_2,2)))
dev.off()
# Use 1% cutoff based on the volcano plot - 71 SNPs (sig_count1_VOLCANOpbased)

save(sig_count1_VOLCANOpbased, tmp_sum_count1, tmp_sum, tmp, VCF_vary, VCF_vary_melt, VCF, file = "WGSvcf_Vary_AltFreq_p001.rda")

# d) Which TF motifs are predicted to be altered by these SNPs? 
lnames = load("WGSvcf_Vary_AltFreq_p001.rda") # sig_count1_VOLCANOpbased, tmp_sum_count1, tmp_sum, tmp, VCF_vary, VCF_vary_melt, VCF
sig_count1_VOLCANOpbased$Chr_Pos = paste0("chr", sig_count1_VOLCANOpbased$Chr_Pos)

lnames = load("AllChr_STRONGmotifbreakRresults_jaspar2022hsmotifs_CTCFboundDEGdownSNPs_dbSNP155GRCh37.rda") # STRONG_all
dim(STRONG_all) # 4148856      26
unique(STRONG_all$varType) # SNV
unique(STRONG_all$width) # 1

sig_count1_VOLCANOpbased = left_join(sig_count1_VOLCANOpbased, STRONG_all[,c(1:21,24:26)]) # 223 rows
save(sig_count1_VOLCANOpbased, file = "WGSvcf_AltFreqDiffASDvsCTLp001_motifbreakRstrongAttached.rda") 

rm(list = ls())
load("WGSvcf_AltFreqDiffASDvsCTLp001_motifbreakRstrongAttached.rda")
tmp = which(is.na(sig_count1_VOLCANOpbased$geneSymbol)) # 20 SNPs have different WGS Alt allele from the motifbreakR Alt allele
sig_count1_VOLCANOpbased = sig_count1_VOLCANOpbased[complete.cases(sig_count1_VOLCANOpbased),] # 203 rows

(DiffAltFreq_TF = unique(sig_count1_VOLCANOpbased$geneSymbol)) # 147 TF motifs are predicted to be altered with the SNPs that show significantly differential Alt allele freq between ASD and CTL
DiffAltFreq_TF # including many KLFs etc.

# Do the Alt Freq Diff disrupt or enhance the TF binding?
sig_count1_VOLCANOpbased$predictedTFbinding_inASD = ifelse(sig_count1_VOLCANOpbased$diff * sig_count1_VOLCANOpbased$alleleDiff < 0, "Lower", "Higher")
table(sig_count1_VOLCANOpbased$predictedTFbinding_inASD) # 91 Higher, 112 Lower. ASD-preferred alleles at SNPs in CTCF-bound ATAC peaks of down-reg genes tend to reduce TF binding.
DiffAltFreq_TFlower = unique(sig_count1_VOLCANOpbased$geneSymbol[sig_count1_VOLCANOpbased$predictedTFbinding_inASD == "Lower"]) 
DiffAltFreq_TFlower = DiffAltFreq_TFlower[order(DiffAltFreq_TFlower)] # including EGR2/3/4, EWSR1-FLI1, GLIS1/2/3, KLF1/3/4/5/10/12/14/15/16, MAZ, REST, TFAP2A/B/C, many ZNFs, etc. Note that EWSR1-FLI1 may regulate CTCF. Note that many of these TFs show reduced binding score in TOBIAS but invalid footprint! Could it be that ATAC peak is open, but due to variants, these TF-bindings are disrupted, thus gene expression decrease? 
DiffAltFreq_TFhigher = unique(sig_count1_VOLCANOpbased$geneSymbol[sig_count1_VOLCANOpbased$predictedTFbinding_inASD == "Higher"]) 
DiffAltFreq_TFhigher = DiffAltFreq_TFhigher[order(DiffAltFreq_TFhigher)] # including ETV2/6/7, EWSR1-FLI1, IRF2/6/7/9, KLF4/11/17, MAZ, MEF2A/B/C/D, TFAP2A/B/C/E, many ZNFs, etc. 
DiffAltFreq_TFlower_specific = DiffAltFreq_TFlower[! DiffAltFreq_TFlower %in% DiffAltFreq_TFhigher] # including ATF6, BCL6B, CREB3(L1), DMRTA1/A2/C2, DPRX, E2F6, EBF3, EGR2/3/4, ELF2, ERF::FOXO1, FOXD2/E1, GLIS1/2/3, GRHL2, GSC, HES7, HIF1A, INSM1, KLF1/3/5/10/12/14/15/16, LHX2, NFIB/C, NFIC::TLX1, NHLH2, NR1H2::RXRA, NR2F1, NRL, OTX2, PATZ1, PKNOX2, PPARD, REST, RXRB/G, SOX8/12/14, SP2, TFAP4::FLI1, TFDP1, TGIF1/2, THRA/B, ZBTB14, ZNF140/143/189/454/460/530/549/669/784/93, ZSCAN4.
DiffAltFreq_TFhigher_specific = DiffAltFreq_TFhigher[! DiffAltFreq_TFhigher %in% DiffAltFreq_TFlower] # including ASCL1, BHLHE22, CREB1, ELF1, ETV2/6/7, FOXO1::FLI1, GABPA, HES6, HOXB13, IRF2/6/7/9. KLF11/17, MEF2A/B/C/D, MGA, MYOG, NHLH1, PBX3, PLAG1, POU2F2/3F2/3F3/3F4, RFX2/3/4/5, SNAI2/3, STAT1::STAT2, TBX1/3/15/20/21, TCF4, TCFL5, TFAP2E, ZBTB6, ZKSCAN3, ZNF24/282/320/410/416/418/528/692/701/740.

# Exciting ones: 
lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_TOBIAS/ind_BINDetect_Jaspar2022/DiffBS_lm_Volcano.rda") # DiffBS_lm_Volcano
unique(DiffBS_lm_Volcano$col) # "NS" "Down_inASD" "Up_inASD"
# DiffAltFreq_TFlower_specific: 
lower_intersect = intersect(DiffAltFreq_TFlower_specific, DiffBS_lm_Volcano$TF_shortname[DiffBS_lm_Volcano$col == "Down_inASD"]) # "GLIS2"  "KLF15"  "KLF3"   "PATZ1"  "TFDP1"  "ZBTB14" "ZNF454" "ZNF530" "ZNF669" "ZNF93"
# DiffAltFreq_TFhigher_specific: 
higher_intersect = intersect(DiffAltFreq_TFhigher_specific, DiffBS_lm_Volcano$TF_shortname[DiffBS_lm_Volcano$col == "Up_inASD"]) # "BHLHE22" "MEF2A"   "MEF2B"   "MEF2C"   "MEF2D"

# Test for significant overlap b/w TFs with differential binding score and TF binding altered by SNP variants
ASDsnpLowerBinding_res = fisher.test(matrix(c(length(lower_intersect), length(setdiff(DiffAltFreq_TFlower_specific, lower_intersect)), length(setdiff(DiffBS_lm_Volcano$TF_shortname[DiffBS_lm_Volcano$col == "Down_inASD"], lower_intersect)), length(setdiff(DiffBS_lm_Volcano$TF_shortname, union(DiffAltFreq_TFlower_specific, DiffBS_lm_Volcano$TF_shortname[DiffBS_lm_Volcano$col == "Down_inASD"])))), nrow = 2))
ASDsnpLowerBinding_OD = round(ASDsnpLowerBinding_res$estimate, 2) # 3.95
ASDsnpLowerBinding_p = formatC(ASDsnpLowerBinding_res$p.value, format = "e", digits = 2) # 1.52e-3, Yay!

ASDsnpHigherBinding_res = fisher.test(matrix(c(length(higher_intersect), length(setdiff(DiffAltFreq_TFhigher_specific, higher_intersect)), length(setdiff(DiffBS_lm_Volcano$TF_shortname[DiffBS_lm_Volcano$col == "Up_inASD"], higher_intersect)), length(setdiff(DiffBS_lm_Volcano$TF_shortname, union(DiffAltFreq_TFhigher_specific, DiffBS_lm_Volcano$TF_shortname[DiffBS_lm_Volcano$col == "Up_inASD"])))), nrow = 2))
ASDsnpHigherBinding_OD = round(ASDsnpHigherBinding_res$estimate, 2) # 1.46
ASDsnpHigherBinding_p = formatC(ASDsnpHigherBinding_res$p.value, format = "e", digits = 2) # 0.4, n.s. Sure, as I am assessing CTCF-bound ATAC peaks of DOWN-REG GENES!

# Venn diagram
library(VennDiagram)
library(gridExtra)

save(DiffAltFreq_TFlower_specific, DiffBS_lm_Volcano, lower_intersect, ASDsnpHigherBinding_res, ASDsnpLowerBinding_p, file = "VennDiagram_OverlapTFs_DisruptedbyASDAlt_DecreasedBindingScoreInASD.rda")

png("VennDiagram_OverlapTFs_DisruptedbyASDAlt_DecreasedBindingScoreInASD.png", height = 500, width = 500)
grid.newpage()
my_venndiag <- draw.pairwise.venn(length(DiffAltFreq_TFlower_specific), length(DiffBS_lm_Volcano$TF_shortname[DiffBS_lm_Volcano$col == "Down_inASD"]), length(lower_intersect), fill = c("orange","chartreuse"), alpha = 0.6, category = c("TFs disrupted by ASD-\npreferred alleles specifically", "TFs with decreased\nbinding score in ASD"), cat.pos = c(0,5), cat.dist = c(0.05, 0.06), cex = 2, cat.cex = 1.5, fontfamily = "Arial", cat.fontfamily = "Arial")
grid.arrange(gTree(children = my_venndiag), # Add title & subtitle
             #top = "My Main Title",
             bottom = textGrob(paste0("Significant overlap, p = ", ASDsnpLowerBinding_p), gp = gpar(fontsize=20), vjust = -2))
dev.off()
dev.off()

tmp = paste(lower_intersect, collapse = ", ")

