rm(list = ls())
setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/13_SFARIgeneEnrichment/13_5_v4_TFBS_disrupted_by_SNVs/")

## Identify proband SNVs in ASD down-reg distal ATAC peaks
lnames = load("../13_2_v4_DistalATACgenePairFDR015/13_2_v4_Simons_Within500bpOfATACanno.rda") # Simons, generated by 13_2_SimonsDeNovoMutations_DiseaseImpactScore_withPromoterOrDistalDiffATAC_v5_IncludeSNVsWithin500bpOfATAC_distATACasNonPromATAC.R
Simons$chr[1] # should contain chr! eg. chr1
Simons$SNV_id = paste0(Simons$chr, ":", Simons$Pos, ":", Simons$Ref, ":", Simons$Alt) # required in this format by motifbreakR, see https://bioc.ism.ac.jp/packages/3.4/bioc/vignettes/motifbreakR/inst/doc/motifbreakR-vignette.html

Simons_Proband = Simons[Simons$Proband == "Probands" & Simons$inATACdistDown == T,] # 63 rows
Simons_Sibling = Simons[Simons$Proband == "Siblings" & Simons$inATACdistDown == T,] # 88 rows

## Create bed files for SNVs
SNV_Proband = data.frame(chromosome = Simons_Proband$chr, start = Simons_Proband$Pos - 1, end = Simons_Proband$Pos, name = Simons_Proband$SNV_id, score = 0, strand = "+")
SNV_Sibling = data.frame(chromosome = Simons_Sibling$chr, start = Simons_Sibling$Pos - 1, end = Simons_Sibling$Pos, name = Simons_Sibling$SNV_id, score = 0, strand = "+")

write.table(SNV_Proband, file = "SNV_Proband_downregDistATAC.bed", quote = F, sep = "\t", row.names = F, col.names = F)
write.table(SNV_Sibling, file = "SNV_Sibling_downregDistATAC.bed", quote = F, sep = "\t", row.names = F, col.names = F)

# On Hoffman2:
# qrsh -l h_data=10G,h_rt=4:00:00
# module load R
# export R_LIBS_USER=/u/project/geschwind/jennybea/R/4.2.2/:$R_LIBS_USER
# R

setwd("/u/project/geschwind/jennybea/ASD_project_2ndbatch/ATAC/13_5_v4_TFBS_disrupted_by_SNVs/")

library(motifbreakR)
library(BSgenome)
library(BSgenome.Hsapiens.UCSC.hg19)
available.SNPs()
library(SNPlocs.Hsapiens.dbSNP155.GRCh37)
seqnames(SNPlocs.Hsapiens.dbSNP155.GRCh37) # 1,2,3,...

## import the BED file
#tmp = read.table("SNV_Proband_downregDistATAC.bed", header = FALSE); head(tmp)
snps.mb.frombed_Proband <- snps.from.file(file = "SNV_Proband_downregDistATAC.bed",
                                  #dbSNP = SNPlocs.Hsapiens.dbSNP155.GRCh37,
                                  search.genome = BSgenome.Hsapiens.UCSC.hg19,
                                  format = "bed")
snps.mb.frombed_Proband # looks good, REF and ALT are recognized. 
snps.mb.frombed_Sibling <- snps.from.file(file = "SNV_Sibling_downregDistATAC.bed",
                                          #dbSNP = SNPlocs.Hsapiens.dbSNP155.GRCh37,
                                          search.genome = BSgenome.Hsapiens.UCSC.hg19,
                                          format = "bed")
snps.mb.frombed_Sibling # looks good, REF and ALT are recognized

## Find Broken Motifs
lnames = load("/u/project/geschwind/jennybea/ASD_project_2ndbatch/ATAC/10_3_13_GeneticVariants_at_CTCFpromoter/mf_jaspar2022hs.rda") # mf

for (i in c("Proband", "Sibling")) {
  print(i)
  snps.mb = get(paste0("snps.mb.frombed_", i))
  print(length(snps.mb)) # Proband: 133, Sibling: 145 snps
  results = motifbreakR(snpList = snps.mb, filterp = TRUE, 
                        pwmList = mf, # mf is from jaspar 2022
                        threshold = 1e-4)

  save(results, file = paste0("motifbreakRresults_jaspar2022hsmotifs_",i,"_SNVsWithin500bpOfDownregDistATAC.rda")) # 1min

    ## st4. Filter for "strong" predicted effects
  results_names = names(results) 
  print(length(results_names)) # 295 or 356 rsids
  uniq_results_names = unique(names(results)) 
  print(length(uniq_results_names)) # 88 or 96 rsids
  
  df_results = as.data.frame(unname(results))
  print(dim(df_results)) # 295 or 356 x 25
  strong_results = df_results[df_results$effect == "strong", ] 
  print(dim(strong_results)) # 232 or 256 obs x 25 columns
  print(length(unique(strong_results$SNP_id))) # 79 or 82
  save(results, df_results, strong_results, file = paste0("STRONGmotifbreakRresults_jaspar2022hsmotifs_",i,"_SNVsWithin500bpOfDownregDistATAC.rda"))
  
  rm(results, df_results, strong_results)
  gc()
}

# Back to Mac:
## Find out which TFBS is preferably disrupted/created in ASD probands (less in siblings)
lnames = load("STRONGmotifbreakRresults_jaspar2022hsmotifs_Proband_SNVsWithin500bpOfDownregDistATAC.rda") # "results"        "df_results"     "strong_results"
Proband_StrongRes = strong_results
lnames = load("STRONGmotifbreakRresults_jaspar2022hsmotifs_Sibling_SNVsWithin500bpOfDownregDistATAC.rda") # "results"        "df_results"     "strong_results"
Sibling_StrongRes = strong_results

length(unique(Proband_StrongRes$geneSymbol)) # 98 TF motifs may be altered by Proband SNVs
length(unique(Sibling_StrongRes$geneSymbol)) # 103 TF motifs may be altered by Sibling SNVs
length(intersect(Proband_StrongRes$geneSymbol, Sibling_StrongRes$geneSymbol)) # 29
# The rest are unique to Proband or Sibling, but those could be random, because 29 seems a big overlap. Maybe quantify the frequency of each TF?

Proband_TF_freq = as.data.frame(table(Proband_StrongRes$geneSymbol)) # 98 TFs
Sibling_TF_freq = as.data.frame(table(Sibling_StrongRes$geneSymbol)) # 103 TFs
colnames(Proband_TF_freq)[2] = "Freq_in_Proband"
colnames(Sibling_TF_freq)[2] = "Freq_in_Sibling"
TF_freq = full_join(Proband_TF_freq, Sibling_TF_freq) # 172 TFs in total
TF_freq[is.na(TF_freq)] = 0

range(TF_freq$Freq_in_Proband) # 0-5
range(TF_freq$Freq_in_Sibling) # 0-3
TF_freq$dFreq = TF_freq$Freq_in_Proband - TF_freq$Freq_in_Sibling
hist(TF_freq$dFreq) # many are -1 or 1, with some -3 or 3. This could be totally random hits, can't speak to any TF being preferably disrupted in ASD probands.
library(tidyverse)
TF_freq = TF_freq %>%
  arrange(dplyr::desc(dFreq))
TF_freq[TF_freq$dFreq == 3,] # ZNF317 (3 counts in probands and 0 in siblings), EWSR1-FLI1 (this one is 5-2). Check out literature for ZNF317 and NACC1 etc. during brain development (https://genome.cshlp.org/content/early/2021/08/16/gr.275133.120.full.pdf)
TF_freq[TF_freq$dFreq == -3,] # The bottom ones have 3 counts in siblings and 0 in probands: GLIS3, SP2

# If I search for SOX in TF_freq table:
TF_freq[grepl("SOX", TF_freq$Var1),] # I got SOX2,4,8-9,13-15,21 all show up in probands but not siblings. That's great, as Brie says that SOX regulons are down in ASD neurons. Note that Sox4,15,2 TF motifs are also enriched in ASD down-reg ATAC peaks (HOMER results in lab meeting 20230118) 
save(TF_freq, Proband_TF_freq, Sibling_TF_freq, file = "TF_freq.rda")

## Do these TFs form PPI? Specific PPI network be disrupted?
# Put Proband_TF_freq and Sibling_TF_freq TF list into DAPPLE.
writeLines(as.character(Proband_TF_freq$Var1), "Proband_TF_SNVsWithin500bpOfDownregDistalATAC_motifbreakRstrongresults_forDAPPLE.txt")
writeLines(as.character(Sibling_TF_freq$Var1), "Sibling_TF_SNVsWithin500bpOfDownregDistalATAC_motifbreakRstrongresults_forDAPPLE.txt")

# GenePattern -> Run (tab) -> Public Server (Register with gmail) -> Browse Modules (button) -> Proteomics -> DAPPLE -> Show DAPPLE version 0.19 -> Upload File (button) upload "xxx.txt", set Permute Length = 50, genome build = hg19, Keyword = Proband/Sibling -> Submit -> For Proband, See "496080. DAPPLE submitted: Feb 28 10:35:16 PM"; For Sibling, See "496081. DAPPLE submitted: Feb 28 10:36:38 PM" -> Finished running	Feb 28 10:42 PM -> download all files in the Jobs tab to Mac download directory and transfer to the getwd()/DAPPLE_res -> Focus on the Proband/Sibling_plot.pdf files, see if there is difference.
# Observed BACH1-FOSL1-FOSL2-JUNB-BATF3-BATF-FOS PPI network in Sibling SNV-disrupted PPIs only. This coincides with up-reg of ATAC peaks bound by these TFs in ASD. However it's the same SNP that disrupts these TFs. See below:
unique(Sibling_StrongRes$SNP_id[Sibling_StrongRes$geneSymbol %in% c("BACH1","FOSL1","FOSL2","JUNB","BATF3","BATF","FOS")]) # chr9:563780:G:T
# This shows that the PPI networks are biased due to same SNP disupting multiple TF motifs.
# And DAPPLE only provides PPI networks for each list separately, I don't know how to compare the two PPI networks.

## If I link SNV to target genes, and compare their GO enrichment, will I get interesting results?
Proband_df = data.frame(SNV_id = unique(Proband_StrongRes$SNP_id))
Sibling_df = data.frame(SNV_id = unique(Sibling_StrongRes$SNP_id))
Proband_df = left_join(Proband_df, Simons[,c("SNV_id", "chr", "Pos", "Ref", "Alt", "start", "end")]) # start and end is SNV +- 500bp
Sibling_df = left_join(Sibling_df, Simons[,c("SNV_id", "chr", "Pos", "Ref", "Alt", "start", "end")])
Proband_gr = annoDF2GR(Proband_df)
Sibling_gr = annoDF2GR(Sibling_df)

lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC015.rda") # "sig_CorATAC"      "sig_CorATAC_uniq"
library(readxl)
Jill_DEG = read_excel("/Users/dhglab/Documents/Documents/Geschwind_lab/LAB/Database_download/31_Jill_ASD_pancortical_RNAseq_datasets/logFC_SupplementaryTable3.xlsx")
sig_CorATAC_uniq$external_gene_name = Jill_DEG$external_gene_name[match(sig_CorATAC_uniq$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]
sig_CorATAC_uniq = sig_CorATAC_uniq[,c(1,2,7,3:6)]

DownregDistATAC_df = unique(as.data.frame(str_split_fixed(sig_CorATAC_uniq$distal_ATAC[which(sig_CorATAC_uniq$distalATAC_FDR < 0.05 & sig_CorATAC_uniq$distalATAC_logFC < 0)], "_", 3)))
DownregDistATAC_df$V2 = as.integer(DownregDistATAC_df$V2); DownregDistATAC_df$V3 = as.integer(DownregDistATAC_df$V3)
colnames(DownregDistATAC_df) = c("chr", "start", "end")
DownregDistATAC_df$distal_ATAC = paste0(DownregDistATAC_df$chr, "_", DownregDistATAC_df$start, "_", DownregDistATAC_df$end)
DownregDistATAC_gr = annoDF2GR(DownregDistATAC_df)

hits = as.data.frame(findOverlaps(Proband_gr, DownregDistATAC_gr))
hits$SNV_id = Proband_df$SNV_id[hits$queryHits]
hits$distal_ATAC = DownregDistATAC_df$distal_ATAC[hits$subjectHits]
hits = unique(hits[,3:4]) # 37 SNV-ATAC pairs, n=? SNVs outside of the ATAC peak (could be caQTLs?).
hits_Proband = left_join(hits, sig_CorATAC_uniq[,1:3]) # 98 rows
length(unique(hits_Proband$external_gene_name)) # 90 genes

hits = as.data.frame(findOverlaps(Sibling_gr, DownregDistATAC_gr))
hits$SNV_id = Sibling_df$SNV_id[hits$queryHits]
hits$distal_ATAC = DownregDistATAC_df$distal_ATAC[hits$subjectHits]
hits = unique(hits[,3:4]) # 44 SNV-ATAC pairs, n=? SNVs outside of the ATAC peak.
hits_Sibling = left_join(hits, sig_CorATAC_uniq[,1:3]) # 83 rows
length(unique(hits_Sibling$external_gene_name)) # 81 genes

(ov = intersect(hits_Proband$external_gene_name, hits_Sibling$external_gene_name)) # 16 genes
setdiff(unique(hits_Proband$external_gene_name), ov) # Many lncRNAs (RPxxx, LINCxxx, Cxxorfxx, CITF22-92A6.1), and others
setdiff(unique(hits_Sibling$external_gene_name), ov) # Some ZNF genes, few lnRNAs (RPxxx, CTD-xxx), and others
save(hits_Proband, hits_Sibling, file = "SNVs_motifbreakRstrongresults_ProbandOrSibling_within500bpOfDownregDistATAC_targetGenes.rda")

# GO enrichment on these target genes
# Shall use all genes associated with ASD down-reg ATAC peaks as background gene list.
DownregDistATAC_df = left_join(DownregDistATAC_df, sig_CorATAC_uniq[,c("distal_ATAC", "ensembl_gene_id", "external_gene_name")]) # expanded to 1625 rows
length(unique(DownregDistATAC_df$ensembl_gene_id)) # 1112 genes as background genes

library(gprofiler2)
gost_proband = gost(query = unique(hits_Proband$ensembl_gene_id), organism = "hsapiens", source = "GO:BP", custom_bg = unique(DownregDistATAC_df$ensembl_gene_id), correction_method = "fdr") # NULL
gost_sibling = gost(query = unique(hits_Sibling$ensembl_gene_id), organism = "hsapiens", source = "GO:BP", custom_bg = unique(DownregDistATAC_df$ensembl_gene_id), correction_method = "fdr") # NULL

## Maybe motifbreakR results are not great. It's only good to overlap with experimentally validated variants.
## Now include all SNVs and get their gene targets
Proband_gr = annoDF2GR(Simons_Proband)
Sibling_gr = annoDF2GR(Simons_Sibling)

DownregDistATAC_df = unique(as.data.frame(str_split_fixed(sig_CorATAC_uniq$distal_ATAC[which(sig_CorATAC_uniq$distalATAC_FDR < 0.05 & sig_CorATAC_uniq$distalATAC_logFC < 0)], "_", 3)))
DownregDistATAC_df$V2 = as.integer(DownregDistATAC_df$V2); DownregDistATAC_df$V3 = as.integer(DownregDistATAC_df$V3)
colnames(DownregDistATAC_df) = c("chr", "start", "end")
DownregDistATAC_df$distal_ATAC = paste0(DownregDistATAC_df$chr, "_", DownregDistATAC_df$start, "_", DownregDistATAC_df$end)
DownregDistATAC_gr = annoDF2GR(DownregDistATAC_df)

hits = as.data.frame(findOverlaps(Proband_gr, DownregDistATAC_gr))
hits$SNV_id = Simons_Proband$SNV_id[hits$queryHits]
hits$distal_ATAC = DownregDistATAC_df$distal_ATAC[hits$subjectHits]
hits = unique(hits[,3:4]) # 63 SNV-ATAC pairs
hits_Proband = left_join(hits, sig_CorATAC_uniq[,1:3]) # 177 rows
length(unique(hits_Proband$external_gene_name)) # 144 genes

hits = as.data.frame(findOverlaps(Sibling_gr, DownregDistATAC_gr))
hits$SNV_id = Simons_Sibling$SNV_id[hits$queryHits]
hits$distal_ATAC = DownregDistATAC_df$distal_ATAC[hits$subjectHits]
hits = unique(hits[,3:4]) # 88 SNV-ATAC pairs
hits_Sibling = left_join(hits, sig_CorATAC_uniq[,1:3]) # 178 rows
length(unique(hits_Sibling$external_gene_name)) # 160 genes

(ov = intersect(hits_Proband$external_gene_name, hits_Sibling$external_gene_name)) # 42 genes
setdiff(unique(hits_Proband$external_gene_name), ov) # 102 genes
setdiff(unique(hits_Sibling$external_gene_name), ov) # 118 genes

# Add DEG info
hits_Proband = left_join(hits_Proband, Jill_DEG[,c("ensembl_gene_id", "WholeCortex_ASD_FDR", "WholeCortex_ASD_logFC")])
hits_Sibling = left_join(hits_Sibling, Jill_DEG[,c("ensembl_gene_id", "WholeCortex_ASD_FDR", "WholeCortex_ASD_logFC")])

# GO enrichment on these target genes
# Shall use all genes associated with ASD down-reg ATAC peaks as background gene list.
DownregDistATAC_df = left_join(DownregDistATAC_df, sig_CorATAC_uniq[,c("distal_ATAC", "ensembl_gene_id", "external_gene_name")]) # expanded to 1625 rows
length(unique(DownregDistATAC_df$ensembl_gene_id)) # 1112 genes as background genes

library(gprofiler2)
gost_proband = gost(query = unique(hits_Proband$ensembl_gene_id), organism = "hsapiens", source = "GO:BP", custom_bg = unique(DownregDistATAC_df$ensembl_gene_id), correction_method = "fdr") # NULL
gost_sibling = gost(query = unique(hits_Sibling$ensembl_gene_id), organism = "hsapiens", source = "GO:BP", custom_bg = unique(DownregDistATAC_df$ensembl_gene_id), correction_method = "fdr") # NULL
# Still too few genes to get positive GO enrichment.

# Add motifbreakR info
colnames(Proband_StrongRes)[6] = colnames(Sibling_StrongRes)[6] = "SNV_id"; colnames(Proband_StrongRes)[11] = colnames(Sibling_StrongRes)[11] = "TF"; colnames(Proband_StrongRes)[14] = colnames(Sibling_StrongRes)[14] = "TFmotif_id"

hits_Proband$motifbreakR_strong = ifelse(hits_Proband$SNV_id %in% Proband_StrongRes$SNV_id, T, F)
hits_Sibling$motifbreakR_strong = ifelse(hits_Sibling$SNV_id %in% Sibling_StrongRes$SNV_id, T, F)

hits_Proband = left_join(hits_Proband, Proband_StrongRes[,c(6, 11, 14, 23)])
hits_Sibling = left_join(hits_Sibling, Sibling_StrongRes[,c(6, 11, 14, 23)])

## Are Proband SNVs more likely to disrupt TF binding? - Looks like so
length(unique(hits_Proband$SNV_id)) # 63
length(unique(hits_Sibling$SNV_id)) # 88
length(unique(hits_Proband$SNV_id[which(hits_Proband$alleleDiff < 0 & hits_Proband$motifbreakR_strong == T)])) # 28
length(unique(hits_Sibling$SNV_id[which(hits_Sibling$alleleDiff < 0 & hits_Sibling$motifbreakR_strong == T)])) # 26, a smaller proportion!
length(unique(hits_Proband$SNV_id[which(hits_Proband$motifbreakR_strong == T)])) # 37
length(unique(hits_Sibling$SNV_id[which(hits_Sibling$motifbreakR_strong == T)])) # 44, still smaller proportion

# formal test - randomly draw m = 10-20 unique SNVs from this pools for B times, what is the proportion of SNVs that is predicted to disrupt TF binding?
m = 20
record = as.data.frame(matrix(nrow = 0, ncol = 2))
set.seed(328)
for (B in 1:1000) {
  snvs_pro = sample(unique(hits_Proband$SNV_id), m)
  snvs_sib = sample(unique(hits_Sibling$SNV_id), m)
  n_pro = length(unique(hits_Proband$SNV_id[which(hits_Proband$SNV_id %in% snvs_pro & hits_Proband$motifbreakR_strong == T & hits_Proband$alleleDiff < 0)]))
  n_sib = length(unique(hits_Sibling$SNV_id[which(hits_Sibling$SNV_id %in% snvs_sib & hits_Sibling$motifbreakR_strong == T & hits_Sibling$alleleDiff < 0)]))
  record = rbind(record, c(n_pro, n_sib))
}
colnames(record) = c("proband", "sibling")
record_melt = melt(record)
record_melt$value = record_melt$value/m # transform to proportion of SNVs

res_wx = wilcox.test(record$proband, record$sibling)
wx_p = formatC(res_wx$p.value, format = "e", digits = 1) # p < 2e-16

bw = function(b, x) { b/bw.nrd0(x) } # to smoothen the line

pdf("SNVsWithin500bpOfASDdownregDistalATAC_MoreLikelyToDisruptTFbinding_inProbandsVsSiblings.pdf", height = 4, width = 6)
record_melt %>%
  ggplot(aes(x = value, col = variable)) +
  #geom_density() +
  geom_density(adjust = bw(0.05, record_melt$value)) +
  xlab("Proportion of SNVs predicted to disrupt TF binding") +
  ylab("Density") + # can't explain the y-axis
  theme_bw() +
  ggtitle("SNVs within 500bp of ASD down-reg ATAC peaks") +
  annotate("text", x = mean(record_melt$value), y = 4.3, label = "p < 2e-16")
dev.off()
# This explains why Proband SNVs are deleterious! Great!

## Add SFARI yes/no
SFARI = read.csv("~/Documents/Documents/Geschwind_lab/LAB/Database_download/SFARI_human_genes/SFARI-Gene_genes_01-11-2022release_03-03-2022export.csv")
SFARI_S12genes = SFARI$gene.symbol[SFARI$gene.score %in% c("S", "1", "2")] # 554 genes, not all in Jill's DEG. use SFARI$ensembl.id gets the same 554 genes.

hits_Proband$SFARI_S12 = ifelse(hits_Proband$external_gene_name %in% SFARI_S12genes, T, F)
hits_Sibling$SFARI_S12 = ifelse(hits_Sibling$external_gene_name %in% SFARI_S12genes, T, F)

# Find good examples for Proband SNV within 500bp of ASD down-reg distal ATAC peaks of SFARI genes:
sig_CorATAC$external_gene_name = Jill_DEG$external_gene_name[match(sig_CorATAC$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]

intersect(hits_Proband$external_gene_name, SFARI_S12genes) # 6 genes including "TSC2"   "TRAF7"  "MYO9B"  "ADSL"   "ANK3"   "ZBTB20".
df = hits_Proband[which(hits_Proband$external_gene_name %in% SFARI_S12genes),]
df = left_join(df, sig_CorATAC[,1:9])
df_proband4plotgardner = df
# ADSL and ZBTB20 have proband SNVs disrupting TF binding.
# ADSL is the best example, where one SNVs close to the distal ATAC peak, forming 170kb loop with the gene promoter, disrupts SOX4 and SOX10 binding sites.
# 2 SNPs locate within 500bp of the same distal ATAC peak (within 30kb of promoter) of ZBTB20. Both of them show strong effect on altering TF binding, but the effects are in both directions.
# TSC2, TRAF7 and MY09B are also good examples with chromatin loops. ANK3 distal ATAC locates within the gene intronic region, forming chromatin loop with the gene promoter. But MotifbreakR shows no strong effect. Note that TRAF7 is also a target gene of a sibling SNV.

intersect(hits_Sibling$external_gene_name, SFARI_S12genes) # 5 genes including "ZBTB7A" "LRRC4C" "HDAC4"  "CHD7"   "TRAF7". Note that TRAF7 is also disrupted in sibling.
df = hits_Sibling[which(hits_Sibling$external_gene_name %in% SFARI_S12genes),]
df = left_join(df, sig_CorATAC[,1:9])
df_sibling4plotgardner = df
# Note that HDAC4 and CHD7 have SNVs in siblings. The distal ATAC peaks of these genes are all within 30kb of gene promoters.

save(hits_Proband, hits_Sibling, df_proband4plotgardner, df_sibling4plotgardner, file = "SNVs_LabelMotifbreakrEffect_ProbandOrSibling_within500bpOfDownregDistATAC_targetGenes_SFARIgeneLabeled.rda")

## Identify good examples show among Proband SNVs that disrupt TF binding and linking to gene promoters with long-range Hi-C loops
rm(list = ls())
lnames = load("SNVs_LabelMotifbreakrEffect_ProbandOrSibling_within500bpOfDownregDistATAC_targetGenes_SFARIgeneLabeled.rda") # hits_Proband, hits_Sibling, df_proband4plotgardner, df_sibling4plotgardner

lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC015.rda") # "sig_CorATAC"      "sig_CorATAC_uniq"

tmp_pro = hits_Proband[hits_Proband$motifbreakR_strong == T & hits_Proband$alleleDiff < 0,] # 197 rows
tmp_sib = hits_Sibling[hits_Sibling$motifbreakR_strong == T & hits_Sibling$alleleDiff < 0,] # 139 rows
tmp_pro = tmp_pro[! tmp_pro$ensembl_gene_id %in% tmp_sib$ensembl_gene_id,] # 188 rows.
tmp_pro = left_join(tmp_pro, sig_CorATAC[,1:8]) # add Loop info

tmp_pro_reduced = unique(tmp_pro[,c("SNV_id", "distal_ATAC", "ensembl_gene_id", "external_gene_name")])
tmp_pro_genenames = as.data.frame(table(tmp_pro_reduced$external_gene_name)) # 72 genes
tmp_pro_genenames = tmp_pro_genenames %>%
  arrange(desc(Freq)) # C17orf62, RAB40B, WDR45B were struck twice. The other genes once.
tmp_pro_genenames$Var1[tmp_pro_genenames$Var1 %in% SFARI_S12genes] #2 genes:ADSL, ZBTB20. Consistent with previous findings in this script.

tmp_pro_selected = tmp_pro[tmp_pro$external_gene_name %in% tmp_pro_genenames$Var1[tmp_pro_genenames$Freq > 1],]
unique(tmp_pro_selected[, c("SNV_id", "external_gene_name", "distal_ATAC", "Loop", "WholeCortex_ASD_logFC", "WholeCortex_ASD_FDR")])
#       SNV_id    external_gene_name    distal_ATAC                Loop           WholeCortex_ASD_logFC WholeCortex_ASD_FDR
# chr17:80551327:C:T    C17orf62  chr17_80548902_80551772 chr17_80405000_80555000                0.0759              0.1180
# chr17:80551327:C:T    RAB40B    chr17_80548902_80551772 chr17_80555000_80655000               -0.0904              0.0975
# chr17:80551327:C:T    WDR45B    chr17_80548902_80551772 chr17_80555000_80605000                0.0526              0.0807
# chr17:80551309:C:T    C17orf62  chr17_80548902_80551772 chr17_80405000_80555000                0.0759              0.1180
# chr17:80551309:C:T    RAB40B    chr17_80548902_80551772 chr17_80555000_80655000               -0.0904              0.0975
# chr17:80551309:C:T    WDR45B    chr17_80548902_80551772 chr17_80555000_80605000                0.0526              0.0807
# 2 SNVs disrupting TF binding at distal ATAC peak (chr17_80548902_80551772), which forms Hi-C loops with 3 gene promoters (C17orf62, RAB40B and WDR45B), out of which only RAB40B is down-reg with FDR < 0.1. ps. Wdr45 deficiency causes a defect in autophagy in neurons. RAB40B regulates cell migration in breast cancer. "The remaining rare DMCpGs/meSNVs found in single or few ASD patients need additional studies in larger data sets to confirm a potential association with the phenotype. Some of them have been related to ASD by point mutations (C15orf62/DNAJC17 and ADAP1), linkage studies (TLE3), aberrant brain expression (PRCD, LCP1, RXRB and SETD1A)67 and copy number variants (n=11 genes). Other genes were involved in relevant functions as neuron differentiation (SERPINF1, TCF12 and KAL1), neuron signaling (C1QL3) and ubiquitinization (DNAJC17 and RAB40B)." (Homs 2016 Transl Psychiatry)

tmp_pro_selected = tmp_pro[tmp_pro$WholeCortex_ASD_FDR < 0.1 & tmp_pro$WholeCortex_ASD_logFC < 0,]
length(unique(tmp_pro_selected$external_gene_name))# 9 genes with FDR < 0.05, 12 genes with FDR < 0.1
tmp_pro_selected_info = unique(tmp_pro_selected[, c("SNV_id", "external_gene_name", "distal_ATAC", "Loop", "WholeCortex_ASD_logFC", "WholeCortex_ASD_FDR")]) # 10 rows, 9 genes, 8 Hi-C loops and 2 "Within 30kb". -> 14 rows, 12 genes, 12 Hi-C loops and 2 "Within 30kb".
unique(tmp_pro_selected_info$external_gene_name) # "FAAH"    "HAGH"    "NDUFB10" "ANKRD24" "MAP2K2"  "GLYR1"   "NLN"     "FBXW5"   "ANAPC2" -> added RAB40B, ZNF500, FAM162A
# What's the correlation b/w MAP2K2 distal ATAC chr19_4033916_4035688 and ZBTB7A promoter?
#---
lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC01.rda") # "sig_CorATAC"      "sig_CorATAC_uniq" "promATAC" 
promATAC$external_gene_name = Jill_DEG$external_gene_name[match(promATAC$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]
promATAC[promATAC$external_gene_name == "ZBTB7A",] # promoter ATAC chr19_4064268_4067961
promATAC[promATAC$external_gene_name == "MAP2K2",] # promoter ATAC chr19_4123275_4124882 and chr19_4100517_4101768

lnames = load("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Cor_Gene_ATAC_calcedCorP.rda") # "Cor_Gene_ATAC“

Cor_Gene_ATAC$external_gene_name = Jill_DEG$external_gene_name[match(Cor_Gene_ATAC$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]
Cor_Gene_ATAC %>%
  filter(distal_ATAC == "chr19_4033916_4035688", 
         promoter_ATAC == "chr19_4064268_4067961")
# Two genes and ZBTB7A and CTD-2622I13.3 share the promoter. cor b/w distal and promoter ATAC is 0.55, cor FDR = 0.164
Cor_Gene_ATAC %>%
  filter(distal_ATAC == "chr19_4033916_4035688", 
         promoter_ATAC == "chr19_4123275_4124882")
# One gene MAP2K2 has the promoter. cor b/w distal and promoter ATAC is 0.69, cor FDR = 0.133
#---
# Just make a note that ZBTB7A may also be the target gene if using this MAP2K2 example.

# Google "[genename] brain/gene function" or "[genename] autism":
# FAAH: "The distribution of FAAH in brain overlaps with that of CB1 receptors and as such, it is functionally positioned to regulate ECS activity in brain regions that mediate stress and fear responses (Egertova et al., 2003)". "Pharmacological inhibition of FAAH enhances AEA levels and reverses the behavioral deficits among different autistic animal models." (Su 2021 Frontiers in Psychiatry) "Remarkably, we found that FAAH blockade completely reversed the social impairment in both mouse models." (Wei 2016 Cannabis Cannabinoid Res) - Both suggest that lower FAAH expression may be compensatory rather than ASD disease causing.
# HAGH: "The enzyme encoded by this gene is classified as a thiolesterase and is responsible for the hydrolysis of S-lactoyl-glutathione to reduced glutathione and D-lactate.Jan 10, 2023" No info found for brain-related function.
# NDUFB10: encodes an accessory subunit located within the PD part of respiratory chain complex I in muscle, heart and liver. (Friederich 2017 HMG) No info found for brain-related function.
# ANKRD24: The protein's function in humans is currently unknown.

# MAP2K2 - INTERESTING! due to CFC syndrome with high-prevalence of ASD caused by mutations in MAP2K2 (25%) and 3 other genes: 
# "We also discovered 2 kinases, MAP2K2/MEK2 (mitogen-activated protein kinase kinase 2) and PLK1 (polo-like kinase 1), to be potentially upregulated by Cory, whereas the siRNA-mediated knockdown of Map2k2 and Plk1 significantly inhibited Cory-induced autophagy. Cory promoted the clearance of Alzheimer disease-associated APP (amyloid β [A4] precursor protein) and Parkinson disease-associated SNCA/α-synuclein (synuclein, α) by enhancing autophagy, and these effects were dramatically diminished by the inhibition of the kinase activities of MAP2K2 and PLK1." (Chen 2017 Autophagy) 
# "Intellectual impairment and psychiatric morbidity are known to be common in the RASopathies. CFC syndrome is a rare disorder, caused by mutations in BRAF, MAP2K1, MAP2K2, or KRAS." (Garg 2017 Developmental Medicine & Child Neurology).
# "Syndromic disorders with high prevalence of ASD are caused by mutations in pathway components that regulate ERK activity (NF1, RAS isoforms, RAF isoforms, MAP2K1, MAP2K2), mTOR activity (TSC1, TSC2, PTEN) or mRNA translation directly (FMR1) [4]." (Kelleher 2012 Plos One)
# "Neuronal projection is coordinated by several regulatory pathways involved in actin cytoskeleton organization, including the MAPK/ERK, RAC/CDC42/PAK, and Rho-ROCK pathways. The proteins related to actin cytoskeleton organization (Actn2, Pfn2, Arpc3/4, and Cfl2) and its regulatory pathway (MAPK/ERK pathway: Map2k2, Mapk1, and Pip4k2b; RAC/CDC42/PAK pathway: Brk1, Wasf1, and Pak2/3) were decreased. Cntnap2 is known to regulate the MAPK/ERK pathway via IP3R1, thereby influencing neuronal migration or projection. Although the core molecules of RAC/CDC42/PAK pathway (Apc, Rac3, Cdc42, and Pak2/5) were downregulated in Cntnap2-deficient excitatory neurons, some of the related molecules (Map2k2, Pak3, Arpc3, Gap43, and Cntnap2) were upregulated and showed negative expressional correlation to the Cntnap2 KO mouse proteome." (Jang 2023 Molecular Psychiatry) - Confusing. 

# GLYR1: GLYR1 functions as a nucleosome-destabilizing factor that facilitates Pol II transcription through nucleosomes.
# NLN: "These experiments revealed that abundance of Nln in the brain protects animals from stroke." (Jayaraman 2020 J Neurochem)
# FBXW5: "FBXW5 was found to regulate the Hippo signaling pathway by binding to LATS1 and degrading LATS1 via ubiquitination." "Hippo signaling is an evolutionarily conserved pathway that controls organ size by regulating cell proliferation, apoptosis, and stem cell self renewal." No info found for brain-related function. 
# Both ANAPC2 and FBXW5 is one of the genes hit by CNV > 500kb (ADHD and ASD) used by the analyses (Table S4 of Martin 2014 J Am Acad Child Adolesc Psychiatry)
# ANAPC2: "ANAPC2 is 1 of several subunits of the anaphase-promoting complex (APC), which functions at the metaphase-to-anaphase transition of the cell cycle and is regulated by spindle checkpoint proteins."

# RAB40B: described earlier in this script.
# ZNF500: Read paper titled "Chromosomal contacts connect loci associated with autism, BMI and head circumference phenotypes" (Loviglio 2017 Mol Psychiatry) - cis and trans contacts of 16p11.2 CNV
# FAM162A: "It plays an important role during embryonal development as programmed cell death and accompanies a variety of normal involutional processes in which it serves as a mechanism to remove "unwanted" cells." (wikipedia)

### Conclusion: 
## Proband SNVs within 500kb of ASD down-reg ATAC peaks are signif. more likely to disrupt TF binding than Sibling SNVs. (p<2e-16)
## 2 examples of Proband SNVs map to important genes: 1) SFARI gene ADSL with 170kb loop 2) MAP2K2 gene with 90kb loop - make a note of ZBTB7A

## Plot the examples
# Script modified from 16_v7_identify_DiseaseRiskIncreasing_BryoiscaQTLinDiffATAC.R
library(plotgardener)
Dup15q_GENOVA_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_Dup15q/Hi-C/data_analysis/11_TADs/IS_GENOVA/"
ASD_GENOVA_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/6_9_aggregated_matrix_Batch1and2/W16_MinstrengthMinus1/"
# For now, use ATAC bigwig of sample CQ56-2_unique.bw
CTL_ATAC_bw = readBigwig(file = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/6_logFC_cor_DAR_DEG/IGV/bw/CQ56-2_unique.bw") 
colnames(CTL_ATAC_bw)[1] = "chrom"

# Get all ATAC within consensus promoter Hi-C loops (union of Bulk, NeuNp, NeuNn)
lnames = load("../../../../../../Hi-C/2nd_batch_20samples/data_analysis/results/25_nlme_DiffLoopAnalysis/Consensus_promoter_loops_8Bulk7NeuNn9NeuNp_LoopBySample_logCPM_includingOutlier.rda") # "Bulk_logCPM"  "NeuNp_logCPM" "NeuNn_logCPM"

for (ct in c("Bulk", "NeuNp", "NeuNn")) {
  ct_logCPM = get(paste0(ct, "_logCPM"))
  ct_bed = as.data.frame(str_split_fixed(rownames(ct_logCPM), "_", 3))
  ct_bed$V2 = as.integer(ct_bed$V2)
  ct_bed$V3 = as.integer(ct_bed$V3)
  ct_bed$Loop = rownames(ct_logCPM)
  assign(paste0(ct, "_logCPM_bed"), ct_bed)
}

options(scipen=999)
plot_gdn = function(i=1, HALF_window = 3e5, CUTOFF = 1500, DOMAIN_COL = "darkgrey", Loop_ct = "Bulk", SNP_label_pos, ATAC_plot_bs, candidate_clear = candidate_clear, df_cur = df_cur, ATACbin_cur = ATACbin_cur, cur_Loop = cur_Loop, SNV_cur = SNV_cur) {
  print(paste0("Loop ", paste(candidate_clear$Loop)))
  CHR = candidate_clear$chr[i]
  Loop_center = (candidate_clear$Loop_start + candidate_clear$Loop_end)/2
  START = Loop_center - HALF_window # SLC6A1: 3e5, old: 1e6 
  END = Loop_center + HALF_window # SLC6A1: 3e5, old: 1e6 
  
  if (candidate_clear$Loop_start[i] < START) {
    print(paste0("Loop",i , " ", candidate_clear$Loop[i]))
    START = candidate_clear$Loop_start[i] - 2e5
  }
  if (candidate_clear$Loop_end[i] > END) {
    print(paste0("Loop",i , " ", candidate_clear$Loop[i]))
    END = candidate_clear$Loop_end[i] + 2e5
  }
  SNP_HALFwidth = (END-START)/500 # 300bp for window size 600kb
  
  Loop_toLabel = data.frame(chrom1 = CHR, start1 = candidate_clear$Loop_start - 5e3, end1 = candidate_clear$Loop_start + 5e3, chrom2 = CHR, start2 = candidate_clear$Loop_end - 5e3, end2 = candidate_clear$Loop_end + 5e3)
  
  for (SampleName in c("Batch1and2_CTL", "CTL_NeuNp", "CTL_NeuNn")) {
    print(SampleName)
    if (SampleName == "Batch1and2_CTL") {
      load(paste0(ASD_GENOVA_dir, SampleName, "_loadcontacts.rda"))
      load(paste0(ASD_GENOVA_dir, SampleName, "_TADcallsDomains.rda"))
    } else {
      load(paste0(Dup15q_GENOVA_dir, SampleName, "_loadcontacts.rda"))
      load(paste0(Dup15q_GENOVA_dir, SampleName, "_TADcallsDomains.rda"))
    }
    
    ABS = SampleName_40kb$IDX
    chr_range = range(ABS$V4[ABS$V1 == CHR])
    ABS_subset = ABS %>%
      filter(V1 == CHR, V3 >= START, V2 <= END)
    
    SampleName_40kb_MAT = SampleName_40kb$MAT
    
    SampleName_40kb_chr = SampleName_40kb_MAT %>%
      filter(V1 >= chr_range[1], V2 <= chr_range[2], V1 != V2)
    # Clean up Diagonal
    SampleName_40kb_chr$V3[which(SampleName_40kb_chr$V1 == SampleName_40kb_chr$V2)] = 0
    
    SampleName_40kb_subset = SampleName_40kb_chr %>%
      filter(V1 >= min(ABS_subset$V4), V2 <= max(ABS_subset$V4))
    colnames(SampleName_40kb_subset)[3] = "counts"
    # Set diagonal as max
    Diagonal_subset = data.frame(V1 = seq(min(ABS_subset$V4), max(ABS_subset$V4), 1), V2 = seq(min(ABS_subset$V4), max(ABS_subset$V4), 1), counts = max(SampleName_40kb_subset$counts))
    SampleName_40kb_subset = rbind(SampleName_40kb_subset, Diagonal_subset)
    # Add genomic coordinates
    SampleName_40kb_subset$V4 = ABS_subset$V2[match(SampleName_40kb_subset$V1, ABS_subset$V4)] # Note that I should use V2 instead of mid
    SampleName_40kb_subset$V5 = ABS_subset$V2[match(SampleName_40kb_subset$V2, ABS_subset$V4)]
    SampleName_40kb_subset = SampleName_40kb_subset[,c(4,5,3,1,2)]
    
    #Domains_relevant = Domains[Domains$chrom == CHR & Domains$end > START & Domains$start < END,]
    Domains_relevant = Domains[Domains$chrom == CHR & Domains$start > START & Domains$end < END,]
    
    tmp_list = list(MAT = SampleName_40kb_subset, Domains_relevant = Domains_relevant, SUM_CC = sum(SampleName_40kb_chr$V3))
    assign(paste0("list_", SampleName), tmp_list)
  }
  
  # Normalize for total contact count on this chr
  nf_Bulk = list_Batch1and2_CTL$SUM_CC/list_CTL_NeuNp$SUM_CC
  list_Batch1and2_CTL$MAT$counts = list_Batch1and2_CTL$MAT$counts/nf_Bulk
  nf_NeuNn = list_CTL_NeuNn$SUM_CC/list_CTL_NeuNp$SUM_CC
  list_CTL_NeuNn$MAT$counts = list_CTL_NeuNn$MAT$counts/nf_NeuNn
  
  # ATAC prep
  CTL_ATAC_bw_subset = CTL_ATAC_bw %>%
    filter(chrom == CHR, end > START, start < END)
  range(CTL_ATAC_bw_subset$score) # 0-2.77 for ASDL gene
  
  # SNP prep
  SNP_df = data.frame(chrom = CHR, start = as.integer(sapply(SNV_cur, function(x) unlist(str_split(x, ":"))[2])) - SNP_HALFwidth, end = as.integer(sapply(SNV_cur, function(x) unlist(str_split(x, ":"))[2])) + SNP_HALFwidth, strand = "+", rsid = SNV_cur) # SNP_HALFwidth = 1e2 for SLC6A1
  
  # Loop prep
  Ct_logCPM = get(paste0(Loop_ct, "_logCPM"))
  Ct_logCPM_bed = get(paste0(Loop_ct, "_logCPM_bed"))
  idx = which(grepl(CHR, rownames(Ct_logCPM)) & grepl(ATACbin_cur, rownames(Ct_logCPM)))
  Loop_df = Ct_logCPM_bed[idx,]
  Loop_df$chrom1 = Loop_df$chrom2 = CHR
  Loop_df$start1 = Loop_df$V2 - 5e3
  Loop_df$end1 = Loop_df$V2 + 5e3
  Loop_df$start2 = Loop_df$V3 - 5e3
  Loop_df$end2 = Loop_df$V3 + 5e3
  Loop_df$length = (Loop_df$start2 - Loop_df$start1) / 1000
  Loop_df = Loop_df[,c("chrom1", "start1", "end1", "chrom2", "start2", "end2", "length", "Loop")]
  Loop_df$col = ifelse(Loop_df$Loop == cur_Loop, "red", "dodgerblue")
  move_to_last <- function(df, n) df[c(setdiff(seq_len(nrow(df)), n), n), ]
  Loop_df = move_to_last(Loop_df, which(Loop_df$col == "red"))
  Loop_df = Loop_df[Loop_df$start1 > START & Loop_df$end2 < END,] # filter out loops out of the window
  
  # Hi-C heatmap color max
  CUTOFF_df = data.frame(SampleName = c("Batch1and2_CTL", "CTL_NeuNp", "CTL_NeuNn"),
                         Cutoff = CUTOFF) # SLC6A1: 1500, old: 850
  Gb_scale = "Mb"
  Loop_radias = 1 # 1.5
  FontSize = 14
  Gene_highlight = candidate_clear$external_gene_name[i]
  
  save(candidate_clear, i, CHR, START, END, list_Batch1and2_CTL, list_CTL_NeuNn, list_CTL_NeuNp, Loop_toLabel, CTL_ATAC_bw_subset, Gene_highlight, SNP_df, Loop_df, CUTOFF_df, Gb_scale, Loop_radias, FontSize, DOMAIN_COL, Loop_ct, file = paste0("13_5_v4_plotgardner_",Gene_highlight,"_Loop",candidate_clear$Loop[i],"_Window_",START/1000,"to",END/1000,"kb_CombineCt_CUTOFF",CUTOFF_df$Cutoff[1],".rda"))
  
  pdf(paste0("13_5_v4_plotgardner_",Gene_highlight,"_Loop",candidate_clear$Loop[i],"_Window_",START/1000,"to",END/1000,"kb_CombineCt_CUTOFF",CUTOFF_df$Cutoff[1],".pdf"), height = 11.5, width = 6) 
  pageCreate(width = 6, height = ATAC_plot_bs + 1.5, showGuides = F); # pageGuideHide(), height + 2.5 for Genes. height = 2.75*3 + 3.25 for SLC6A1
  
  region <- pgParams(
    chrom = CHR,
    chromstart = START, chromend = END,
    assembly = "hg19",
    width = 5
  )
  
  # CTL_Bulk
  hicPlot_Bulk = plotHicTriangle(
    data = list_Batch1and2_CTL$MAT[,1:3], resolution = 40000,
    zrange = c(0, CUTOFF_df$Cutoff[CUTOFF_df$SampleName == "Batch1and2_CTL"]),
    params = region,
    x = 0.5, y = 0.25, height = 2.5,
    just = c("left", "top"),
    default.units = "inches"
  )
  plotText(
    label = "Bulk", fontsize = FontSize, fontface = "bold",
    x = 1, y = 0.75
  )
  annoHeatmapLegend(
    plot = hicPlot_Bulk, x = 5.6, y = 0.25,
    width = 0.13, height = 1.5,
    just = c("left", "top"),
    fontcolor = "black",
    fontsize = FontSize
  )
  annoDomains(
    plot = hicPlot_Bulk, 
    data = list_Batch1and2_CTL$Domains_relevant,
    linecolor = DOMAIN_COL,  # darkgrey
    lwd = 3
  )
  # annoPixels(
  #   plot = hicPlot_Bulk, 
  #   data = Loop_toLabel,
  #   type = "circle", 
  #   col = "red",
  #   shift = Loop_radias,
  #   lwd = 1.5
  # )
  
  # CTL_NeuNn
  hicPlot_NeuNn = plotHicTriangle(
    data = list_CTL_NeuNn$MAT[,1:3], resolution = 40000,
    zrange = c(0, CUTOFF_df$Cutoff[CUTOFF_df$SampleName == "CTL_NeuNn"]),
    params = region,
    x = 0.5, y = 3, height = 2.5 # adjust y
  )
  plotText(
    label = "NeuNn", fontsize = FontSize, fontface = "bold",
    x = 1, y = 3.5
  )
  
  annoDomains(
    plot = hicPlot_NeuNn, 
    data = list_CTL_NeuNn$Domains_relevant,
    linecolor = DOMAIN_COL, 
    lwd = 3
  )
  # annoPixels(
  #   plot = hicPlot_NeuNn, 
  #   data = Loop_toLabel,
  #   type = "circle", 
  #   col = "red",
  #   shift = Loop_radias,
  #   lwd = 1.5
  # ) 
  
  # CTL_NeuNp - bring NeuNp closer to the gene
  hicPlot_NeuNp = plotHicTriangle(
    data = list_CTL_NeuNp$MAT[,1:3], resolution = 40000,
    zrange = c(0, CUTOFF_df$Cutoff[CUTOFF_df$SampleName == "CTL_NeuNp"]),
    params = region,
    x = 0.5, y = 5.75, height = 2.5
  )
  plotText(
    label = "NeuNp", fontsize = FontSize, fontface = "bold",
    x = 1, y = 6.25
  )
  
  annoDomains(
    plot = hicPlot_NeuNp, 
    data = list_CTL_NeuNp$Domains_relevant,
    linecolor = DOMAIN_COL, 
    lwd = 3
  )
  # annoPixels(
  #   plot = hicPlot_NeuNp, 
  #   data = Loop_toLabel,
  #   type = "circle", 
  #   col = "red",
  #   shift = Loop_radias,
  #   lwd = 1.5
  # )
  
  # Genome labels
  annoGenomeLabel(
    plot = hicPlot_Bulk, x = 0.5, y = 8.25,
    scale = Gb_scale, # If not pretty, remove this line to allow full expression of xxx,xxx,xxx bp
    fontsize = FontSize, 
    just = c("left", "top")
  )
  
  # Genes
  genesPlot <- plotGenes(
    params = region,
    fill = c("black", "black"),
    fontcolor = c("black", "black"),
    fontsize = FontSize, 
    x = 0.5, y = 8.5, height = 1, 
    # adjust y = 3.25 when Triangle baseline at 3
    # remember to adjust width to the same as Triangle Hi-C map
    geneHighlights = data.frame(gene = Gene_highlight, color = "red"), geneBackground = "black"
  ) 
  
  # SNPs
  pileupPlot <- plotRanges(
    data = SNP_df,
    params = region,
    fill = "red",
    # fill = colorby("strand", palette =
    #                  colorRampPalette(c("steel blue", "light salmon"))),
    x = 0.5, y = 9.5, height = ifelse(length(SNP_df$rsid) == 2, 0.35, 0.17),
    boxHeight = unit(3, "mm"), spaceHeight = 0.4
  )
  plotText(
    label = SNP_df$rsid[1], fontcolor = "red", fontsize = FontSize,
    x = SNP_label_pos, y = 9.6 # SNP_label_pos = 2.2 for SLC6A1
  )
  
  # ATAC peaks
  signalPlot <- plotSignal(
    data = CTL_ATAC_bw_subset, params = region,
    range = c(0, max(CTL_ATAC_bw_subset$score)),  # this sets the range of the signal
    x = 0.5, y = ATAC_plot_bs, height = 0.75, # y=9.85 for SLC6A1
    linecolor = "black", baseline.color = "lightgrey"
  )
  plotText(
    label = "ATAC", fontsize = FontSize, fontface = "bold",
    x = 1, y = 10.05
  )
  
  # Loops
  #data("IMR90_DNAloops_pairs")
  heights <- sqrt(Loop_df$length) / sqrt(max(Loop_df$length)) * 0.5
  # colors <- mapColors(vector = IMR90_DNAloops_pairs$length,
  #                     palette = colorRampPalette(c("dodgerblue2", "firebrick2")))
  archPlot <- plotPairsArches(
    data = Loop_df, params = region,
    fill = Loop_df$col,
    linecolor = "fill",
    archHeight = heights, alpha = 1,
    x = 0.5, y = ATAC_plot_bs + 0.75, height = 0.5,
    flip = T
  )
  
  dev.off()
}
save(plot_gdn, file = "13_5_v4_plot_gdn_function.rda")

# 1) SFARI gene ADSL with proband SNV disrupting distal ATAC linked to gene promoter via a 170kb loop

df_cur = tmp_pro[tmp_pro$external_gene_name == "ADSL",]
SNV_cur = unique(df_cur$SNV_id)
ATACpeak_cur = unique(df_cur$distal_ATAC)
ATACbin_cur = unique(df_cur$Distal_bin)

cur_Loop = unique(df_cur$Loop)
cur_Loop %in% rownames(Bulk_logCPM) # T
cur_Loop %in% rownames(NeuNp_logCPM) # F
cur_Loop %in% rownames(NeuNn_logCPM) # F

candidate_clear = data.frame(
  chr = unlist(str_split(cur_Loop, "_"))[1],
  Loop_start = as.integer(unlist(str_split(cur_Loop, "_"))[2]),
  Loop_end = as.integer(unlist(str_split(cur_Loop, "_"))[3]),
  external_gene_name = unique(df_cur$external_gene_name),
  ensembl_gene_id = unique(df_cur$ensembl_gene_id),
  Loop = sub("_", ":", cur_Loop)
)

plot_gdn(HALF_window = 3.5e5, SNP_label_pos = 1.3, ATAC_plot_bs = 9.95, DOMAIN_COL = "red", candidate_clear = candidate_clear, df_cur = df_cur, ATACbin_cur = ATACbin_cur, cur_Loop = cur_Loop, SNV_cur = SNV_cur)
# Great! The SNV sits within TNRC6B gene, but Hi-C clearly shows a loop with ADSL gene.

# Show later disruption of SOX4/10 binding

# 2) CFC syndrome gene MAP2K2 with proband SNV disrupting distal ATAC linked to gene promoter via a 90kb loop

df_cur = tmp_pro[tmp_pro$external_gene_name == "MAP2K2",]
SNV_cur = unique(df_cur$SNV_id)
ATACpeak_cur = unique(df_cur$distal_ATAC)
ATACbin_cur = unique(df_cur$Distal_bin)

cur_Loop = unique(df_cur$Loop)
cur_Loop %in% rownames(Bulk_logCPM) # F
cur_Loop %in% rownames(NeuNp_logCPM) # F
cur_Loop %in% rownames(NeuNn_logCPM) # T

candidate_clear = data.frame(
  chr = unlist(str_split(cur_Loop, "_"))[1],
  Loop_start = as.integer(unlist(str_split(cur_Loop, "_"))[2]),
  Loop_end = as.integer(unlist(str_split(cur_Loop, "_"))[3]),
  external_gene_name = unique(df_cur$external_gene_name),
  ensembl_gene_id = unique(df_cur$ensembl_gene_id),
  Loop = sub("_", ":", cur_Loop)
)

# plot_gdn(HALF_window = 2.5e5, SNP_label_pos = 1.6, ATAC_plot_bs = 9.85, DOMAIN_COL = "red", candidate_clear = candidate_clear, df_cur = df_cur, ATACbin_cur = ATACbin_cur, cur_Loop = cur_Loop, SNV_cur = SNV_cur, Loop_ct = "NeuNn")
plot_gdn(HALF_window = 1.7e5, SNP_label_pos = 1.3, ATAC_plot_bs = 9.85, DOMAIN_COL = "red", candidate_clear = candidate_clear, df_cur = df_cur, ATACbin_cur = ATACbin_cur, cur_Loop = cur_Loop, SNV_cur = SNV_cur, Loop_ct = "NeuNn")
# Good! The SNV sits within PIAS4 gene, but Hi-C clearly shows a loop with MAP2K2 gene promoter. This enhancer also interacts with 4 other gene promoters in NeuNn. 
# The highest ATAC peak in the region looks like ZBTB7A promoter and it's also linked to the SNV. Found a paper "Heterozygous variants in ZBTB7A cause a neurodevelopmental disorder associated with symptomatic overgrowth of pharyngeal lymphoid tissue, macrocephaly, and elevated fetal hemoglobin. 7/12 probands show autistic features." (Lippe 2021 AJMG part A)
Jill_DEG[Jill_DEG$external_gene_name == "ZBTB7A", c("WholeCortex_ASD_logFC", "WholeCortex_ASD_FDR")] # logFC = -0.15, FDR = 0.008! Yes! Should be it! -> make correction by alleviating DEG FDR to FDR < 0.1 -> get the same result. as promoter-distal ATAC cor of ZBTB7A is 0.55 (0.15 < FDR < 0.2)

# Show later disruption of ZNF135 binding.

