rm(list = ls())
options(stringsAsFactors = F)
library(tidyverse)
library(Repitools)
library(GenomicRanges)
library(reshape2)
library(ggplot2)
library(ggrepel)
library(readxl)

# install.packages("LDlinkR")
# library(LDlinkR)

setwd("~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/16_caQTL_in_DiffATAC/")

## Goal: Assess how caQTL of ASD diffATAC impact ASD disease risk
## Strategy: Scatter plot of caQTLs, x-axis showing their effect on ATAC signal, y-axis showing their effect on ASD disease risk (GWAS Z), color the dots by whether the caQTL-associated ATAC peak is up/dowm-reg promoter/distal ATAC peaks. May plot the 4 dysreg ATAC types on separate plots. 
## More rules:
# If a caQTL is associated with multiple ATAC peaks, hopefully the ATAC peaks do not show significant changes in opposite directions.
# For now, a promoter ATAC peak will not be considered as distal ATAC peak. If a caQTL is associated with both promoter and distal ATAC peak, it will be colored by the ATAC peak that shows significant changes, otherwise default black/grey.
# I will start by using the 6200 brain caQTLs in Bryois et al 2018, later may consider adding the > 2000 Neuron/Progenitor caQTLs in Liang et al 2021. I know from previous analysis that caQTLs overlapped in these two papers show consistent effect on ATAC peaks (see 16_v7_identify_DiseaseRiskIncreasing_BryoiscaQTLinDiffATAC.R).
# First, define distal ATAC peaks as all non-promoter ATAC peaks. Then may define them as those significantly correlate with promoter ATAC peaks (FDR < 0.15 for Simons SNVs, may test the same here)

## Look for list of cQTLs from Bryois et al:
# Bryois et al states "In total, we identified 6200 SNPs that were significantly associated with differences in chromatin accessibility (5% FDR, Fig. 4a)." But I can't find the cQTLs -> Got the 6200 caQTLs by emailing Bryois on 2023/02/21
# Note that Bryois et al states "Finally, we performed a Bayesian colocalization analysis to identify regions with high probability of a shared causal variant associating both with schizophrenia and chromatin accessibility." -> Shall I use similar approach to identify the causal variant associating both with ASD and chromatin accessibility?

###############     
### Outline ###
###############     

#### 1. Load 6200 brain caQTLs in Bryois 2018 Nat Commun ####
#### 2. Get ASD GWAS Grove 2019 sumstats of the caQTLs ####
#### 3. Adjust the alleles ####
#### 4. Plot the effect of caQTLs on ATAC signal vs. disease risk (promoter vs distal, all vs. dysreg) ####
#### 5. Plot the effect of caQTLs on ATAC signal vs. disease risk (distal dysreg with target genes) ####
#### 6. Plotgardner of great examples ####
#### 7. MPRA done on the great examples? ####

## Thought about:
# a. overlap with eQTL, but caQTL is directly linked to our study on diffATAC while eQTL not.
# b. TF identification with motifbreakR, but the TF binding changes is likely secondary to (ie. explains) genetic variation which directly cause ATAC/GE changes 
##############     
### Script ###
##############  

#### 1. Load 6200 brain caQTLs in Bryois 2018 Nat Commun ####
#### 2. Get ASD GWAS Grove 2019 sumstats of the caQTLs ####
# Sections 1 and 2 were performed in 16_2_v1_caQTLBryois_plot_EffectOnATAC_vs_ASDgwasZ_ColorByPromDistUpDown.R

#### 3. Adjust the alleles ####
## so that the effect allele of the caQTLs on ATAC signal should be consistent with ATAC signal changes

## Load dataset generated by 16_2_v1_caQTLBryois_plot_EffectOnATAC_vs_ASDgwasZ_ColorByPromDistUpDown.R

lnames  = load("16_2_v1_03_brain_caQTL_wASDorSCZgwasInfo_wDiffATACanno_PromLabeled.rda") # caQTL_gwas_ATAC, comes with the column Is_promATAC
dim(caQTL_gwas_ATAC) # 3177 rows x 28 columns
colnames(caQTL_gwas_ATAC)

## Check the dataset 
all(! is.na(caQTL_gwas_ATAC$ATACpeak)) # T
all(! is.na(caQTL_gwas_ATAC$ATAC_logFC)) # F, my differential analysis lm couldn't get result

all(caQTL_gwas_ATAC$ASD_GWAS_A1 == caQTL_gwas_ATAC$alt_allele, na.rm = T) # T
all(caQTL_gwas_ATAC$SCZ_GWAS_A1 == caQTL_gwas_ATAC$alt_allele, na.rm = T) # T
# Right now all GWAS effect allele is the alt_allele. Need to make it consistent with the caQTL_A1

## Process the data
df = caQTL_gwas_ATAC[! is.na(caQTL_gwas_ATAC$ATAC_logFC),] # 3176 rows
df$effect_allele = df$alt_allele # allele of caQTL whose effect is consistent with ASD ATAC changes. Default to use alt_allele
df$non_effect_allele = df$ref_allele # Default to use ref_allele

idx1 = which(df$ATAC_logFC * df$SLOPE > 0) # 1635 rows have alt_allele changing ATAC intensity in the same direction as ATAC dysregulation direction in ASD.
idx2 = which(df$ATAC_logFC * df$SLOPE < 0) # 1541 rows need to switch the caQTL_A1/A2 alleles

df$effect_allele[idx2] = df$ref_allele[idx2] # allele of caQTL whose effect is consistent with ASD ATAC changes. Default to use alt_allele
df$non_effect_allele[idx2] = df$alt_allele[idx2] # Default to use ref_allele
df$SLOPE[idx2] = -df$SLOPE[idx2]
df$ASD_GWAS_Z[idx2] = -df$ASD_GWAS_Z[idx2]
df$SCZ_GWAS_Z[idx2] = -df$SCZ_GWAS_Z[idx2]

# Check
# all(df$SLOPE * df$ATAC_logFC > 0) # T

## Order the columns, remove GWAS_A1/A2 columns as they are represented by (non_)effect_allele
colnames(df)
# [1] "rsid_new"          "Bryois_PEAK"       "PEAK_START"        "Bryois_PEAK_END"  
# [5] "Bryois_rsid"       "Bryois_DISTANCE"   "SLOPE"             "BPVAL"            
# [9] "QVAL"              "SNP_id"            "ref_allele"        "alt_allele"       
# [13] "ASD_GWAS_A1"       "ASD_GWAS_A2"       "ASD_GWAS_Z"        "ASD_GWAS_N"       
# [17] "SCZ_GWAS_A1"       "SCZ_GWAS_A2"       "SCZ_GWAS_Z"        "SCZ_GWAS_N"       
# [21] "chr"               "start"             "end"               "ATAC_logFC"       
# [25] "ATAC_p"            "ATAC_FDR"          "ATACpeak"          "Is_promATAC"      
# [29] "effect_allele"     "non_effect_allele"
df = df[,c(1,10:12,29:30, 2:9, 15:16,19:20, 21:28)]
## In df, ref_allele and alt_allele is from dbSNP. effect_allele and non_effect_allele is for both caQTL effect on ATAC signal and on GWAS disease risk

caQTL_gwas_ATAC = df
save(caQTL_gwas_ATAC, file = "16_2_v2_03_brain_caQTL_wASDorSCZgwasInfo_wDiffATACanno_PromLabeled_EffectAlleleConsistentWithATACchangesInASD.rda")

#### 4. Plot the effect of caQTLs on ATAC signal vs. disease risk (promoter vs distal, all vs. dysreg) ####
rm(list = ls())
lnames = load("16_2_v2_03_brain_caQTL_wASDorSCZgwasInfo_wDiffATACanno_PromLabeled_EffectAlleleConsistentWithATACchangesInASD.rda") # caQTL_gwas_ATAC

### 1) Calculate linear regression coef and p and R2
## A. all caQTLs with GWAS info
df1 = unique(caQTL_gwas_ATAC[,c("SLOPE", "ASD_GWAS_Z", "Is_promATAC")]) # 3176 rows, same as caQTL_gwas_ATAC
lm_res1 = summary(lm(ASD_GWAS_Z ~ 0 + SLOPE, data = df1))
lm_coef1 = round(lm_res1$coefficients[1], 2) # 0.03
lm_p1 = round(lm_res1$coefficients[4], 2) # 0.56
lm_r2_1 = formatC(lm_res1$r.squared, format = "e", digits = 1) # 1.2e-4

## B. limit caQTLs to those associated with ASD dysregulated ATAC peaks
df2 = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR < 0.05), c("SLOPE", "ASD_GWAS_Z", "Is_promATAC", "ATAC_logFC")]) # 153 rows
# df2 = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR < 0.1 & abs(caQTL_gwas_ATAC$ATAC_logFC) > 0.2), c("SLOPE", "ASD_GWAS_Z", "Is_promATAC", "ATAC_logFC")]) # 280 rows

lm_res2 = summary(lm(ASD_GWAS_Z ~ 0 + SLOPE, data = df2))
lm_coef2 = round(lm_res2$coefficients[1], 2) # -0.44 -> -0.04 (FDR < 0.05 -> 0.1)
lm_p2 = round(lm_res2$coefficients[4], 2) # 0.06 -> 0.76 (FDR < 0.05 -> 0.1)
lm_r2_2 = formatC(lm_res2$r.squared, format = "e", digits = 1) # 2.5e-2 -> 2.4e-4

cor_res2 = cor.test(df2$SLOPE, df2$ASD_GWAS_Z) # cor = -0.17, p=0.04
cor2 = round(cor_res2$estimate, 2) # -0.17 (FDR < 0.05) -> 0 (FDR < 0.1) -> -0.07 (FDR < 0.1 & |logFC| > 0.2)
cor_p2 = round(cor_res2$p.value, 2) # 0.04 (FDR < 0.05)-> 0.99 (FDR < 0.1) -> 0.28 (FDR < 0.1 & |logFC| > 0.2)

# lm of promoter ATAC caQTLs
df2b = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR < 0.05 & caQTL_gwas_ATAC$Is_promATAC == T), c("SLOPE", "ASD_GWAS_Z", "Is_promATAC")]) # 43 rows
# df2b = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR < 0.1 & abs(caQTL_gwas_ATAC$ATAC_logFC) > 0.2 & caQTL_gwas_ATAC$Is_promATAC == T), c("SLOPE", "ASD_GWAS_Z", "Is_promATAC")]) # 66 rows

lm_res2b = summary(lm(ASD_GWAS_Z ~ 0 + SLOPE, data = df2b))
lm_coef2b = round(lm_res2b$coefficients[1], 2) # 0.13 -> 0.8 (FDR < 0.05 -> 0.1)
lm_p2b = formatC(lm_res2b$coefficients[4], format = "e", digits = 1) # 0.79 -> 4.8e-3 * significant! (FDR < 0.05 -> 0.1)
lm_r2_2b = formatC(lm_res2b$r.squared, format = "e", digits = 1) # 1.7e-3 -> 6.5e-2

cor_res2b = cor.test(df2b$SLOPE, df2b$ASD_GWAS_Z) # cor = 0.09, p=0.57
cor2b = round(cor_res2b$estimate, 2) # 0.09 -> 0.28 -> 0.22
cor_p2b = ifelse(cor_res2b$p.value > 0.05, round(cor_res2b$p.value, 2), formatC(cor_res2b$p.value, format = "e", digits = 1)) # 0.57 -> 0.002 -> 0.09

# lm of distal ATAC caQTLs
df2c = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR < 0.05 & caQTL_gwas_ATAC$Is_promATAC == F), c("SLOPE", "ASD_GWAS_Z", "Is_promATAC")]) # 110 rows
# df2c = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR < 0.1 & abs(caQTL_gwas_ATAC$ATAC_logFC) > 0.2 & caQTL_gwas_ATAC$Is_promATAC == F), c("SLOPE", "ASD_GWAS_Z", "Is_promATAC")]) # 214 rows

lm_res2c = summary(lm(ASD_GWAS_Z ~ 0 + SLOPE, data = df2c))
lm_coef2c = round(lm_res2c$coefficients[1], 2) # -0.59 -> -0.3 (FDR < 0.05 -> 0.1)
lm_p2c = round(lm_res2c$coefficients[4], 2) # 0.03 * significant! -> 0.06  (FDR < 0.05 -> 0.1)
lm_r2_2c = formatC(lm_res2c$r.squared, format = "e", digits = 1) # 4.6e-2 -> 1.3e-2

cor_res2c = cor.test(df2c$SLOPE, df2c$ASD_GWAS_Z) # cor = -0.23, p=0.02
cor2c = round(cor_res2c$estimate, 2) # -0.23 -> -0.06 -> -0.12
cor_p2c = round(cor_res2c$p.value, 2) # 0.02 (FDR < 0.05) -> 0.3 (FDR < 0.1) -> 0.08 (FDR < 0.1 & |logFC| > 0.2)

## FDR < 0.1 with or wo |logFC| > 0.2 gives no significant correlations.

### 2) Plot
pdf("16_2_v2_04_AB_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_ColorByPromoterATACorNot_DiffATACfdr005.pdf", height = 4, width = 6)
# pdf("16_2_v2_04_AB_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_ColorByPromoterATACorNot_DiffATACfdr01.pdf", height = 5, width = 8)

## A. all caQTLs with GWAS info
df1 %>%
  arrange(desc(Is_promATAC)) %>%
  ggplot(aes(x = SLOPE, y = ASD_GWAS_Z)) +
  #geom_smooth(method = "lm") +
  geom_point(aes(col = Is_promATAC)) +
  theme_bw() +
  ggtitle("Brain caQTLs (Bryois et al 2018) associated with\nASD/CTL consensus ATAC peaks") +
  xlab("Effect on ATAC signal") +
  ylab("Effect on ASD risk") +
  # set the same x and y axis range to compare effect size
  #xlim(-10,10) +
  #ylim(-10,10) +
  geom_abline(intercept = 0, slope = lm_coef1, col = "black") +
  annotate("text", x = -1.1, y = 3.75, label = paste0("slope = ", lm_coef1, "\np = ", lm_p1, "\nR2 = ", lm_r2_1), col = "black")
## Observation:
# There is a no correlation between caQTL effect on ATAC vs ASD disease risk.

## B. limit caQTLs to those associated with ASD dysregulated ATAC peaks
df2 %>%
  arrange(desc(Is_promATAC)) %>%
  ggplot(aes(x = SLOPE, y = ASD_GWAS_Z)) +
  #geom_smooth(method = "lm") +
  geom_point(aes(col = Is_promATAC)) +
  theme_bw() +
  ggtitle("Brain caQTLs associated with\nASD dysregulated ATAC peaks (FDR < 0.05)") + # or FDR < 0.1
  xlab("Effect on ATAC signal") +
  ylab("Effect on ASD risk") +
  # set the same x and y axis range to compare effect size
  #xlim(-10,10) +
  #ylim(-10,10) +
  geom_abline(intercept = 0, slope = lm_coef2, col = "black") +
  annotate("text", x = 0, y = 2, label = paste0("slope = ", lm_coef2, "\np = ", lm_p2, "\nR2 = ", lm_r2_2), col = "black") # y = 3.75 for FDR < 0.1

## Observation:
# There is a no overall correlation between caQTL effect on ATAC vs ASD disease risk.
# Looks like caQTLs of ASD down-reg distal ATAC peaks increase ASD disease risk, and caQTLs of ASD down-reg promoter ATAC peaks decrease ASD disease risk. - Plot in the next page.
## Thoughts:
# This finding supports that promoter ATAC up-reg is driven by TF up-reg, while distal down-reg ATAC is driven by SNPs.
# Try define ASD dysreg ATAC peaks using FDR < 0.05
# Try limit distal ATAC to those with target genes

# separate caQTLs of promoter and distal ATAC
df2$Is_promATAC = factor(df2$Is_promATAC, levels = c(F,T)) # To show distal ATAC in red
df2 %>%
  arrange(desc(Is_promATAC)) %>%
  ggplot(aes(x = SLOPE, y = ASD_GWAS_Z)) +
  #geom_smooth(method = "lm") +
  geom_point(aes(col = Is_promATAC)) + 
  theme_bw() +
  ggtitle("Brain caQTLs associated with\nASD dysregulated ATAC peaks (FDR < 0.05)") +  # or FDR < 0.1
  xlab("Effect on ATAC signal") +
  ylab("Effect on ASD risk") +
  # set the same x and y axis range to compare effect size
  #xlim(-10,10) +
  #ylim(-10,10) +
  
  # report slope, p and r2:
  # geom_abline(intercept = 0, slope = lm_coef2, col = "black") +
  # annotate("text", x = 0, y = -2, label = paste0("Combined:\nslope = ", lm_coef2, "\np = ", lm_p2, "\nR2 = ", lm_r2_2), col = "black") + # y = 3.75 for FDR < 0.1
  # geom_abline(intercept = 0, slope = lm_coef2b, col = "dodgerblue") +
  # annotate("text", x = 0.7, y = -2, label = paste0("Promoter:\nslope = ", lm_coef2b, "\np = ", lm_p2b, "\nR2 = ", lm_r2_2b), col = "dodgerblue") +  # x = 0.5, y = 3.75 for FDR < 0.1
  # geom_abline(intercept = 0, slope = lm_coef2c, col = "red") +
  # annotate("text", x = -0.7, y = -2, label = paste0("Distal:\nslope = ", lm_coef2c, "\np = ", lm_p2c, "\nR2 = ", lm_r2_2c), col = "red") +  # x = -0.5, y = 3.75 for FDR < 0.1
  # 
  # report cor and cor_p:
  geom_abline(intercept = 0, slope = cor2, col = "black") +
  annotate("text", x = 0, y = -2, label = paste0("Combined:\ncor = ", cor2, "\np = ", cor_p2), col = "black") + # y = 3.75 for FDR < 0.1
  geom_abline(intercept = 0, slope = cor2b, col = "dodgerblue") +
  annotate("text", x = 0.7, y = -2, label = paste0("Promoter:\ncor = ", cor2b, "\np = ", cor_p2b), col = "dodgerblue") +  # x = 0.5, y = 3.75 for FDR < 0.1
  geom_abline(intercept = 0, slope = cor2c, col = "red") +
  annotate("text", x = -0.7, y = -2, label = paste0("Distal:\ncor = ", cor2c, "\np = ", cor_p2c), col = "red") +  # x = -0.5, y = 3.75 for FDR < 0.1
  scale_color_manual(values = c("FALSE" = "#F8766D", "TRUE" = "dodgerblue")) # Default blue #00BFC4 too faint

  # Shall I use correlation or linear model?
# ChatGPT: Correlation is useful when you want to know whether two variables are related and how strong the relationship is. However, it does not tell you anything about causation or the direction of the relationship. Linear regression slope is useful when you want to predict the value of one variable based on the value of another variable, or when you want to test whether one variable is a significant predictor of another variable. In summary, correlation is useful for understanding the strength and direction of the relationship between two variables, while linear regression slope is useful for modeling and predicting the relationship between two variables.
 
# Only show caQTLs of ASD dysreg promoter ATAC 
df2b %>%
  arrange(desc(Is_promATAC)) %>%
  ggplot(aes(x = SLOPE, y = ASD_GWAS_Z)) +
  geom_point() +
  theme_bw() +
  ggtitle("Brain caQTLs associated with\nASD dysregulated promoter ATAC peaks (FDR < 0.05)") +  # or FDR < 0.1
  xlab("Effect on ATAC signal") +
  ylab("Effect on ASD risk") +
  # set the same x and y axis range to compare effect size
  #xlim(-10,10) +
  #ylim(-10,10) +
  geom_abline(intercept = 0, slope = lm_coef2b, col = "red") +
  annotate("text", x = 0, y = 1, label = paste0("slope = ", lm_coef2b, "\np = ", lm_p2b, "\nR2 = ", lm_r2_2b), col = "red") # y = 2 for FDR < 0.1

# Only show caQTLs of ASD dysreg distal ATAC 
df2c %>%
  arrange(desc(Is_promATAC)) %>%
  ggplot(aes(x = SLOPE, y = ASD_GWAS_Z)) +
  geom_point() +
  theme_bw() +
  ggtitle("Brain caQTLs associated with\nASD dysregulated distal ATAC peaks (FDR < 0.05)") + # or FDR < 0.1
  xlab("Effect on ATAC signal") +
  ylab("Effect on ASD risk") +
  # set the same x and y axis range to compare effect size
  #xlim(-10,10) +
  #ylim(-10,10) +
  geom_abline(intercept = 0, slope = lm_coef2c, col = "red") +
  annotate("text", x = 0, y = 1, label = paste0("slope = ", lm_coef2c, "\np = ", lm_p2c, "\nR2 = ", lm_r2_2c), col = "red") # y = 3.75 for FDR < 0.1

## Observation:
# Page 5 distal ATAC caQTLs only shows more clearly the dots in Q4, some of which were masked by promoter ATAC caQTLs on Page 3.
## Thoughts:
# Shall highlight Page 5 distal ATAC peaks with target genes

dev.off()

save(list = ls(), file = "16_2_v2_04_AB_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_ColorByPromoterATACorNot_DiffATACfdr005.rda")

# DiffATAC defined as ATAC_FDR < 0.05:
# Page 2-5 are the key plots in this pdf file
# Page 2 shows that caQTLs of ASD down-reg ATAC peaks tend to increase ASD risk.
# Page 3 shows that this increase of ASD risk mainly come from caQTLs of distal down-reg ATAC (lm p = 0.03)

## How many dots in Q2 vs Q3 on Page 5?
length(which(caQTL_gwas_ATAC$Is_promATAC == F & caQTL_gwas_ATAC$ATAC_FDR < 0.05 & caQTL_gwas_ATAC$SLOPE < 0 & caQTL_gwas_ATAC$ASD_GWAS_Z > 0)) # Q2: 47 dots (decreased distal ATAC with increased ASD risk)
length(which(caQTL_gwas_ATAC$Is_promATAC == F & caQTL_gwas_ATAC$ATAC_FDR < 0.05 & caQTL_gwas_ATAC$SLOPE < 0 & caQTL_gwas_ATAC$ASD_GWAS_Z < 0)) # Q3: 37 dots

## C. Make sure that caQTLs at n.s. distal ATAC peaks do not matter
df3 = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR > 0.05 & caQTL_gwas_ATAC$Is_promATAC == F), c("SLOPE", "ASD_GWAS_Z", "Is_promATAC")]) # 2279 rows
lm_res3 = summary(lm(ASD_GWAS_Z ~ 0 + SLOPE, data = df3))
lm_coef3 = round(lm_res3$coefficients[1], 2) # 0.04
lm_p3 = round(lm_res3$coefficients[4], 2) # 0.47
lm_r2_3 = formatC(lm_res3$r.squared, format = "e", digits = 1) # 2.6e-4

cor_res3 = cor.test(df3$SLOPE, df3$ASD_GWAS_Z) # cor = 0.01, p=0.51
cor3 = round(cor_res3$estimate, 2) # 0.01
cor_p3 = round(cor_res3$p.value, 2) # 0.51

pdf("16_2_v2_04_C_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_nsDistalATACfdr005.pdf", height = 4, width = 6) # as CTL for the distal down-reg ATAC findings
df3 %>%
  ggplot(aes(x = SLOPE, y = ASD_GWAS_Z)) +
  geom_point() +
  theme_bw() +
  ggtitle("Brain caQTLs associated with\nASD non-differential distal ATAC peaks (FDR > 0.05)") +
  xlab("Effect on ATAC signal") +
  ylab("Effect on ASD risk") +
  # set the same x and y axis range to compare effect size
  #xlim(-10,10) +
  #ylim(-10,10) +
  
  # report lm results:
  # geom_abline(intercept = 0, slope = lm_coef3, col = "red") +
  # annotate("text", x = 0, y = 3.75, label = paste0("slope = ", lm_coef3, "\np = ", lm_p3, "\nR2 = ", lm_r2_3), col = "red") +
  # report cor results:
  geom_abline(intercept = 0, slope = cor3, col = "red") +
  annotate("text", x = -1.1, y = -2.75, label = paste0("slope = ", cor3, "\np = ", cor_p3), col = "red")

dev.off()
# Great control!

#### 5. Plot the effect of caQTLs on ATAC signal vs. disease risk (distal dysreg with target genes) ####

### 1) Label whether caQTLs are associated with distal ATAC that are linked to target genes

# Load ATAC-gene pairs (cor FDR < 0.1)
lnames = load("../10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC01.rda") # sig_CorATAC, sig_CorATAC_uniq, promATAC

caQTL_gwas_ATAC$Is_distATACwTargetGenes_ATACcorFDR01 = ifelse(caQTL_gwas_ATAC$ATACpeak %in% sig_CorATAC_uniq$distal_ATAC, T, F)
caQTL_gwas_ATAC$Is_distATACwTargetGenes_ATACcorFDR01 = factor(caQTL_gwas_ATAC$Is_distATACwTargetGenes_ATACcorFDR01, levels = c(T, F)) # So that T is colored in red

table(caQTL_gwas_ATAC$Is_distATACwTargetGenes_ATACcorFDR01) # 383 rows T, 2793 rows F
length(unique(caQTL_gwas_ATAC$rsid_new[caQTL_gwas_ATAC$Is_distATACwTargetGenes_ATACcorFDR01 == T])) # 380 unique caQTLs are associated with my distal ATAC peaks that are linked to target genes (ATAC cor FDR < 0.1)

## Save dataset
save(caQTL_gwas_ATAC, file = "16_2_v2_05_brain_caQTL_wASDorSCZgwasInfo_wDiffATACanno_PromDistLabeled.rda")

pdf("16_2_v2_05_ABCD_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_DistalDysregATACwTargetGenesOnly.pdf", height = 5, width = 8)

### 3) Highlight Section4-b3 ASD down-reg distal ATAC peaks with target genes
rm(list = ls())
lnames = load("16_2_v2_05_brain_caQTL_wASDorSCZgwasInfo_wDiffATACanno_PromDistLabeled.rda") # caQTL_gwas_ATAC

df2c = unique(caQTL_gwas_ATAC[which(caQTL_gwas_ATAC$ATAC_FDR < 0.05 & caQTL_gwas_ATAC$Is_promATAC == F), ]) # 110 rows

lm_res2c = summary(lm(ASD_GWAS_Z ~ 0 + SLOPE, data = df2c))
lm_coef2c = round(lm_res2c$coefficients[1], 2) # -0.59 -> -0.3 (FDR < 0.05 -> 0.1)
lm_p2c = round(lm_res2c$coefficients[4], 2) # 0.03 * significant! -> 0.06  (FDR < 0.05 -> 0.1)
lm_r2_2c = formatC(lm_res2c$r.squared, format = "e", digits = 1) # 4.6e-2 -> 1.3e-2

cor_res2c = cor.test(df2c$SLOPE, df2c$ASD_GWAS_Z) # cor = -0.23, p=0.02
cor2c = round(cor_res2c$estimate, 2) # -0.23
cor_p2c = round(cor_res2c$p.value, 2) # 0.02

## How many caQTLs of distal down-reg ATAC that increase ASD risk have target genes?
length(which(df2c$SLOPE < 0 & df2c$ASD_GWAS_Z > 0 & df2c$Is_distATACwTargetGenes_ATACcorFDR01 == T)) # Only 6 caQTLs have target genes (ATAC cor FDR < 0.1)
length(which(df2c$SLOPE < 0 & df2c$ASD_GWAS_Z > 0 & df2c$Is_distATACwTargetGenes_ATACcorFDR015 == T)) # Only 11 caQTLs have target genes (ATAC cor FDR < 0.15)

## Get the target genes (FDR < 0.15)
Jill_DEG = read_excel("/Users/dhglab/Documents/Documents/Geschwind_lab/LAB/Database_download/31_Jill_ASD_pancortical_RNAseq_datasets/logFC_SupplementaryTable3.xlsx")

SFARI = read.csv("~/Documents/Documents/Geschwind_lab/LAB/Database_download/SFARI_human_genes/SFARI-Gene_genes_01-11-2022release_03-03-2022export.csv")
SFARI_S12genes = SFARI$ensembl.id[SFARI$gene.score %in% c("S", "1", "2")] # 554 genes, not all in Jill's DEG. use SFARI$ensembl.id gets the same 554 genes.

# ATAC-gene pairs with ATAC cor FDR < 0.1
lnames = load("../10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC01.rda") # sig_CorATAC, sig_CorATAC_uniq, promATAC
colnames(sig_CorATAC_uniq)[1] = "ATACpeak"
sig_CorATAC_uniq$external_gene_name = Jill_DEG$external_gene_name[match(sig_CorATAC_uniq$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]

# Alternatively, ATAC-gene pairs with ATAC cor FDR < 0.15
# lnames = load("../10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC015.rda") # sig_CorATAC, sig_CorATAC_uniq, promATAC
# colnames(sig_CorATAC_uniq)[1] = "ATACpeak"
# sig_CorATAC_uniq$external_gene_name = Jill_DEG$external_gene_name[match(sig_CorATAC_uniq$ensembl_gene_id, Jill_DEG$ensembl_gene_id)]

# What are the target genes and their RNA expression?
df2c = left_join(df2c, sig_CorATAC_uniq[,c("ATACpeak", "ensembl_gene_id", "external_gene_name", "WholeCortex_ASD_logFC", "WholeCortex_ASD_FDR")]) # 116 -> 126 rows (ATAC cor FDR < 0.1 -> 0.15)
df2c$SFARIgene = ifelse(df2c$ensembl_gene_id %in% SFARI_S12genes, T, F)
df2c$external_gene_name[which(df2c$SFARIgene == T)] # 2 genes: NFIX and NACC1, associated with the same caQTL! -> 3 genes: added PER2 (ATAC cor FDR < 0.1 -> 0.15)
df2c$external_gene_name[which(df2c$SFARIgene == T & df2c$ASD_GWAS_Z > 0)] # The same 2 gnes - Yay! -> PER2 is not in Q2 but in Q3 - not good (ATAC cor FDR < 0.1 -> 0.15)
df2c[which(df2c$SFARIgene == T & df2c$ASD_GWAS_Z > 0),] # Both NFIX and NACC1 have WholeCortex_ASD_logFC < 0, with NACC1 WholeCortex_ASD_FDR = 0.004! (NFIX WholeCortex_ASD_FDR = 0.4).
df2c[which(df2c$ATACpeak == "chr19_13093993_13097128"),] # Among the 4 genes linked to this caQTL associated distal ATAC peaks, only NACC1 shows significant GE reduction. The other 3 genes all had WholeCortex_ASD_FDR > 0.38

save(df2c, file = "16_2_v2_06_df2c_brain_caQTL_DistalDysregATAC_wTargetGenesATACcorFDR01.rda")

## Plot with highlight
pdf("16_2_v2_05_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_DistalDysregATAC_LabelTargetGenesATACcorFDR01.pdf", height = 5, width = 8)
# pdf("16_2_v2_05_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_DistalDysregATAC_LabelTargetGenesATACcorFDR015.pdf", height = 5, width = 8)

df2c %>%
  arrange(desc(Is_promATAC)) %>%
  ggplot(aes(x = SLOPE, y = ASD_GWAS_Z)) +
  geom_point(aes(col = Is_distATACwTargetGenes_ATACcorFDR01)) +
  # geom_point(aes(col = Is_distATACwTargetGenes_ATACcorFDR015)) +
  theme_bw() +
  ggtitle("Brain caQTLs associated with ASD dysregulated distal ATAC peaks (FDR < 0.05)") + # or FDR < 0.1
  xlab("Effect on ATAC signal") +
  ylab("Effect on ASD risk") +
  # set the same x and y axis range to compare effect size
  #xlim(-10,10) +
  #ylim(-10,10) +
  geom_abline(intercept = 0, slope = lm_coef2c, col = "darkgrey") +
  annotate("text", x = 0.7, y = 2.5, label = paste0("slope = ", lm_coef2c, "\np = ", lm_p2c, "\nR2 = ", lm_r2_2c), col = "black") + # y = 3.75 for FDR < 0.1
  geom_text_repel(aes(label = external_gene_name), box.padding = 0.5, max.overlaps = Inf, size = 3, col = ifelse(df2c$ensembl_gene_id %in% SFARI_S12genes, "red", "black")) + # run a few times, as the positions of the tags will change each time. Settle on the plot that nice labels of the SFARI genes.
  labs(col = "Target genes\nassigned")
  
dev.off()

# Note: Many distal down-reg ATAC peaks that increase ASD disease risk do not have assigned target genes. 

#### 6. Plotgardner of great examples ####
rm(list = ls())
lnames = load("16_2_v2_06_df2c_brain_caQTL_DistalDysregATAC_wTargetGenesATACcorFDR01.rda") # df2c

### 1) Rules of example finding:
# caQTL of distal down-reg ATAC peaks (FDR < 0.05) -> Associated with target genes -> Target gene expression show significant changes or is a SFARI gene

## A. Section 5 part 3) already found SFARI gene NACC1. 16_v7_6_NACC1_Loopchr19/13095000_13225000_Window_12860to13460kb_CombineCt_CUTOFF1500_plotgardener.pdf was generated by 16_v7_identify_DiseaseRiskIncreasing_BryoiscaQTLinDiffATAC.R, but it did not notice NFIX
# SLC6A1 wasn't among the SFARI genes here, because its distal (intronic) ATAC peak has ATAC_FDR = 0.065, while dysreg ATAC was defined with FDR < 0.05

## B. Now look for examples with DEGs (use ATAC cor < 0.1 to link distal ATAC to target genes)
df2c$external_gene_name[which(df2c$WholeCortex_ASD_FDR < 0.05 & df2c$WholeCortex_ASD_logFC < 0)] # "ATP6V0A1" "PVRL1"    "SEMA7A"   "NACC1", all in Q3 except for NACC1 :-(
df2c$external_gene_name[which(df2c$WholeCortex_ASD_FDR < 0.1 & df2c$WholeCortex_ASD_logFC < 0)] # the same 4 genes
# -> Consider expanding dysreg ATAC to FDR < 0.1 with or wo |logFC| > 0.2 -> no significant cor between distal down-reg ATAC and effect on ASD disease risk

# How's expression of the genes in Q2 of 16_2_v2_05_brain_caQTL_EffectOn_ATACsignal_vs_ASDrisk_DistalDysregATAC_LabelTargetGenesATACcorFDR01.pdf?
df2c[which(df2c$SLOPE < 0 & df2c$ASD_GWAS_Z > 0 & !is.na(df2c$external_gene_name)), c("external_gene_name", "WholeCortex_ASD_logFC", "WholeCortex_ASD_FDR")]
# external_gene_name WholeCortex_ASD_logFC WholeCortex_ASD_FDR
# 25               DAAM2               -0.1130             0.52700 # nephrotic syndrome, type 24
# 40       RP11-552C15.1               -0.1270             0.73300
# 51               PAQR6               -0.0895             0.67100
# 68                NFIX               -0.0721             0.38700
# 69               TRMT1                0.0242             0.63400
# 70               NACC1               -0.1480             0.00395 * Good candidate
# 71          AC007787.2                0.2280             0.44600
# 78               COPRS               -0.0632             0.21900
# 109            CAMK2N1               -0.0849             0.30600
# Nice to see that the gene expression of almost all these genes are reduced, although not significant. It may be that an additive effect of all the genes contribute to autism in the end.
# PAQR6 was reported significantly down-reg with drug-induced repetitive behaviors (Table 4 of Crittenden 2022 Eur J Neurosci).
# CaMK2N1 and CaMK2N2 are endogenous inhibitors of calcium/calmodulin-dependent protein kinase II (CaMKII), a key synaptic signaling molecule for learning and memory. Reduced CaMK2N1 expression does not affect contextual fear long-term memory (LTM) formation. However, we show that it impairs maintenance of established LTM, but only if retrieval occurs (Vigil 2017 Scientific Reports).

### 2) Plotgardner showing caQTL of NACC1 distal ATAC peak link to the gene promoter in NeuNp?
# Modify script from 13_5_v4_TFBS_disrupted_by_ProbandSNVsInASDdownregDistalATAC_UseResultsFrom13_2_v4fdr015_ExampleDEGfdr01.R

## Attach loop info
# Get all ATAC within consensus promoter Hi-C loops (union of Bulk, NeuNp, NeuNn)
lnames = load("../../../../../Hi-C/2nd_batch_20samples/data_analysis/results/25_nlme_DiffLoopAnalysis/Consensus_promoter_loops_8Bulk7NeuNn9NeuNp_LoopBySample_logCPM_includingOutlier.rda") # "Bulk_logCPM"  "NeuNp_logCPM" "NeuNn_logCPM"

# ATAC-gene pairs with ATAC cor FDR < 0.1
lnames = load("../10_3_8_LinkATACtoGene/v5_ATACatacCor_PL_PromoterAsTSSminus2kbplus100bp_corrected20230227/Distal_And_Promoter_ATAC_GE_pairs_FDRcorATAC01.rda") # sig_CorATAC, sig_CorATAC_uniq, promATAC
sig_CorATAC$external_gene_name = df2c$external_gene_name[match(sig_CorATAC$ensembl_gene_id, df2c$ensembl_gene_id)]
sig_CorATAC = sig_CorATAC[! is.na(sig_CorATAC$external_gene_name),] # Reduce the dataframe just for this example.
colnames(sig_CorATAC)[which(colnames(sig_CorATAC) == "distal_ATAC")] = "ATACpeak"

# Subset for NACC1 entry
df2c$SNP_id = paste0(df2c$SNP_id, ":", df2c$ref_allele, ":", df2c$alt_allele)
df_cur = df2c[which(df2c$external_gene_name == "NACC1"),] # effect_allele is the alt_allele, great.
SNV_cur = unique(df_cur$SNP_id)
ATACpeak_cur = unique(df_cur$ATACpeak)

df_cur = left_join(df_cur, sig_CorATAC) # Added loop info now
ATACbin_cur = unique(df_cur$Distal_bin)
cur_Loop = unique(df_cur$Loop) # chr19_13095000_13225000
cur_Loop %in% rownames(Bulk_logCPM) # T
cur_Loop %in% rownames(NeuNp_logCPM) # T
cur_Loop %in% rownames(NeuNn_logCPM) # T

# Check whether loops of the other target genes of this distal ATAC peak show up in the three cell types. - plot the most specific cell type (best only contain NACC1 loop)
df_atg = df2c[which(df2c$SNP_id == SNV_cur),] # atg as "all target genes"
df_atg = left_join(df_atg, sig_CorATAC) # Added loop info now
unique(df_atg[, c("external_gene_name", "Loop", "promoter_ATAC", "cor")]) # NFIX have 3 alternative promoters, 2 linked by loop, one within 30kb of distal ATAC. TRMT1 share the loop and promoter ATAC with NACC1. AC007787.2 share the loop with one of NFIX's. All ATAC cor > 0.75
# external_gene_name                    Loop           promoter_ATAC       cor
# 1               NFIX chr19_13095000_13135000 chr19_13135222_13136187 0.7945437
# 2               NFIX chr19_13095000_13185000 chr19_13178743_13179815 0.7612681
# 3               NFIX chr19_13095000_13185000 chr19_13180867_13183614 0.9108068
# 4               NFIX              Within30kb chr19_13105734_13108152 0.8510038
# 5              TRMT1 chr19_13095000_13225000 chr19_13226953_13229516 0.8393454
# 6              NACC1 chr19_13095000_13225000 chr19_13226953_13229516 0.8393454
# 7         AC007787.2 chr19_13095000_13185000 chr19_13180867_13183614 0.9108068
atg_Loops = unique(df_atg$Loop) # "chr19_13095000_13135000" "chr19_13095000_13185000" "Within30kb" "chr19_13095000_13225000"
atg_Loops %in% rownames(Bulk_logCPM) # T,T,F,T
atg_Loops %in% rownames(NeuNp_logCPM) # T,T,F,T
atg_Loops %in% rownames(NeuNn_logCPM) # T,T,F,T
# All the loops of this caQTL are present in all 3 cell types.

rownames(Bulk_logCPM)[which(grepl(df_cur$chr, rownames(Bulk_logCPM)) & grepl(ATACbin_cur, rownames(Bulk_logCPM)))] # 7
rownames(NeuNp_logCPM)[which(grepl(df_cur$chr, rownames(NeuNp_logCPM)) & grepl(ATACbin_cur, rownames(NeuNp_logCPM)))] # 7
rownames(NeuNn_logCPM)[which(grepl(df_cur$chr, rownames(NeuNn_logCPM)) & grepl(ATACbin_cur, rownames(NeuNn_logCPM)))] # 7
# all 3 cell types have 7 loops anchoring at this caQTL -> Just use Bulk

candidate_clear = data.frame(
  chr = unlist(str_split(cur_Loop, "_"))[1],
  Loop_start = as.integer(unlist(str_split(cur_Loop, "_"))[2]),
  Loop_end = as.integer(unlist(str_split(cur_Loop, "_"))[3]),
  external_gene_name = unique(df_cur$external_gene_name),
  ensembl_gene_id = unique(df_cur$ensembl_gene_id),
  Loop = sub("_", ":", cur_Loop)
)

## Load function and directories for plotgardner
Dup15q_GENOVA_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_Dup15q/Hi-C/data_analysis/11_TADs/IS_GENOVA/"
Dup15q_TopDom_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_Dup15q/Hi-C/data_analysis/11_TADs/TopDom/11_10_AggregatedMatrix_TopDom2GENOVA_Domains/"
ASD_GENOVA_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/IS_GENOVA/6_9_aggregated_matrix_Batch1and2/W16_MinstrengthMinus1/"
ASD_TopDom_dir = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/Hi-C/2nd_batch_20samples/data_analysis/results/6_TADs/TopDom/6_9_aggregated_matrix_Batch1and2/"

# For now, use ATAC bigwig of sample CQ56-2_unique.bw
CTL_ATAC_bw = readBigwig(file = "~/Documents/Documents/Geschwind_lab/LAB/Projects/Project_ASD/ATAC-seq/8_ASDandCTL_batch2/data_analysis_20220727_startover/results/6_logFC_cor_DAR_DEG/IGV/bw/CQ56-2_unique.bw") 
colnames(CTL_ATAC_bw)[1] = "chrom"

for (ct in c("Bulk", "NeuNp", "NeuNn")) {
  ct_logCPM = get(paste0(ct, "_logCPM"))
  ct_bed = as.data.frame(str_split_fixed(rownames(ct_logCPM), "_", 3))
  ct_bed$V2 = as.integer(ct_bed$V2)
  ct_bed$V3 = as.integer(ct_bed$V3)
  ct_bed$Loop = rownames(ct_logCPM)
  assign(paste0(ct, "_logCPM_bed"), ct_bed)
}

# lnames = load("../13_SFARIgeneEnrichment/13_5_v4_TFBS_disrupted_by_SNVs/13_5_v4_plot_gdn_function.rda") # plot_gdn

save(list = ls(), file = "16_2_v2_06_plotgardener_NACC1_DataPrep.rda")

plot_gdn = function(i=1, HALF_window = 3e5, CUTOFF = 1500, DOMAIN_COL = "darkgrey", Loop_ct = "Bulk", SNP_label_pos, ATAC_plot_bs, candidate_clear = candidate_clear, df_cur = df_cur, ATACbin_cur = ATACbin_cur, cur_Loop = cur_Loop, SNV_cur = SNV_cur, geneOrder = NULL, pre_name = "16_2_v2_", ws = 5, Batch1and2_CTL_Domains = NULL, CTL_NeuNp_Domains = NULL, CTL_NeuNn_Domains = NULL) {
  print(paste0("Loop ", paste(candidate_clear$Loop)))
  CHR = candidate_clear$chr[i]
  Loop_center = (candidate_clear$Loop_start + candidate_clear$Loop_end)/2
  START = round((Loop_center - HALF_window)/40e3) * 40e3 # SLC6A1: 3e5, old: 1e6 
  END = round((Loop_center + HALF_window)/40e3) * 40e3 # SLC6A1: 3e5, old: 1e6 
  # print(paste0("Window start: ", START, ", end: ", END))
  
  if (candidate_clear$Loop_start[i] < START) {
    print(paste0("Loop",i , " ", candidate_clear$Loop[i]))
    START = candidate_clear$Loop_start[i] - 2e5
  }
  if (candidate_clear$Loop_end[i] > END) {
    print(paste0("Loop",i , " ", candidate_clear$Loop[i]))
    END = candidate_clear$Loop_end[i] + 2e5
  }
  SNP_HALFwidth = (END-START)/500 # 300bp for window size 600kb
  
  Loop_toLabel = data.frame(chrom1 = CHR, start1 = candidate_clear$Loop_start - 5e3, end1 = candidate_clear$Loop_start + 5e3, chrom2 = CHR, start2 = candidate_clear$Loop_end - 5e3, end2 = candidate_clear$Loop_end + 5e3)
  
  for (SampleName in c("Batch1and2_CTL", "CTL_NeuNp", "CTL_NeuNn")) {
    print(SampleName)
    if (SampleName == "Batch1and2_CTL") {
      load(paste0(ASD_GENOVA_dir, SampleName, "_loadcontacts.rda"))
      # load(paste0(ASD_GENOVA_dir, SampleName, "_TADcallsDomains.rda"))
      load(paste0(ASD_TopDom_dir, SampleName, "_TADcallsDomains_TopDom2GENOVA_windowsize",ws,".rda"))
    } else {
      load(paste0(Dup15q_GENOVA_dir, SampleName, "_loadcontacts.rda"))
      # load(paste0(Dup15q_GENOVA_dir, SampleName, "_TADcallsDomains.rda"))
      load(paste0(Dup15q_TopDom_dir, SampleName, "_TADcallsDomains_TopDom2GENOVA_windowsize",ws,".rda"))
    }
    
    if (! is.null(get(paste0(SampleName, "_Domains"))) ) {Domains = get(paste0(SampleName, "_Domains"))}

    ABS = SampleName_40kb$IDX
    chr_range = range(ABS$V4[ABS$V1 == CHR])
    ABS_subset = ABS %>%
      filter(V1 == CHR, V3 >= START, V2 <= END)
    
    SampleName_40kb_MAT = SampleName_40kb$MAT
    
    SampleName_40kb_chr = SampleName_40kb_MAT %>%
      filter(V1 >= chr_range[1], V2 <= chr_range[2], V1 != V2)
    # Clean up Diagonal
    SampleName_40kb_chr$V3[which(SampleName_40kb_chr$V1 == SampleName_40kb_chr$V2)] = 0
    
    SampleName_40kb_subset = SampleName_40kb_chr %>%
      filter(V1 >= min(ABS_subset$V4), V2 <= max(ABS_subset$V4))
    colnames(SampleName_40kb_subset)[3] = "counts"
    # Set diagonal as max
    Diagonal_subset = data.frame(V1 = seq(min(ABS_subset$V4), max(ABS_subset$V4), 1), V2 = seq(min(ABS_subset$V4), max(ABS_subset$V4), 1), counts = max(SampleName_40kb_subset$counts))
    SampleName_40kb_subset = rbind(SampleName_40kb_subset, Diagonal_subset)
    # Add genomic coordinates
    SampleName_40kb_subset$V4 = ABS_subset$V2[match(SampleName_40kb_subset$V1, ABS_subset$V4)] # Note that I should use V2 instead of mid
    SampleName_40kb_subset$V5 = ABS_subset$V2[match(SampleName_40kb_subset$V2, ABS_subset$V4)]
    SampleName_40kb_subset = SampleName_40kb_subset[,c(4,5,3,1,2)]
    
    #Domains_relevant = Domains[Domains$chrom == CHR & Domains$end > START & Domains$start < END,]
    Domains_relevant = Domains[Domains$chrom == CHR & Domains$start > START & Domains$end < END,]
    
    tmp_list = list(MAT = SampleName_40kb_subset, Domains_relevant = Domains_relevant, SUM_CC = sum(SampleName_40kb_chr$V3))
    assign(paste0("list_", SampleName), tmp_list)
  }
  
  # Normalize for total contact count on this chr
  nf_Bulk = list_Batch1and2_CTL$SUM_CC/list_CTL_NeuNp$SUM_CC
  list_Batch1and2_CTL$MAT$counts = list_Batch1and2_CTL$MAT$counts/nf_Bulk
  nf_NeuNn = list_CTL_NeuNn$SUM_CC/list_CTL_NeuNp$SUM_CC
  list_CTL_NeuNn$MAT$counts = list_CTL_NeuNn$MAT$counts/nf_NeuNn
  
  # ATAC prep
  CTL_ATAC_bw_subset = CTL_ATAC_bw %>%
    filter(chrom == CHR, end > START, start < END)
  range(CTL_ATAC_bw_subset$score) # 0-2.77 for ASDL gene
  
  # SNP prep
  SNP_df = data.frame(chrom = CHR, start = as.integer(sapply(SNV_cur, function(x) unlist(str_split(x, ":"))[2])) - SNP_HALFwidth, end = as.integer(sapply(SNV_cur, function(x) unlist(str_split(x, ":"))[2])) + SNP_HALFwidth, strand = "+", rsid = df_cur$rsid_new) # SNP_HALFwidth = 1e2 for SLC6A1
  
  # Loop prep
  Ct_logCPM = get(paste0(Loop_ct, "_logCPM"))
  Ct_logCPM_bed = get(paste0(Loop_ct, "_logCPM_bed"))
  idx = which(grepl(CHR, rownames(Ct_logCPM)) & grepl(ATACbin_cur, rownames(Ct_logCPM)))
  Loop_df = Ct_logCPM_bed[idx,]
  Loop_df$chrom1 = Loop_df$chrom2 = CHR
  Loop_df$start1 = Loop_df$V2 - 5e3
  Loop_df$end1 = Loop_df$V2 + 5e3
  Loop_df$start2 = Loop_df$V3 - 5e3
  Loop_df$end2 = Loop_df$V3 + 5e3
  Loop_df$length = (Loop_df$start2 - Loop_df$start1) / 1000
  Loop_df = Loop_df[,c("chrom1", "start1", "end1", "chrom2", "start2", "end2", "length", "Loop")]
  Loop_df$col = ifelse(Loop_df$Loop == cur_Loop, "red", "dodgerblue")
  move_to_last <- function(df, n) df[c(setdiff(seq_len(nrow(df)), n), n), ]
  Loop_df = move_to_last(Loop_df, which(Loop_df$col == "red"))
  Loop_df = Loop_df[Loop_df$start1 > START & Loop_df$end2 < END,] # filter out loops out of the window
  
  # Hi-C heatmap color max
  CUTOFF_df = data.frame(SampleName = c("Batch1and2_CTL", "CTL_NeuNp", "CTL_NeuNn"),
                         Cutoff = CUTOFF) # SLC6A1: 1500, old: 850
  Gb_scale = "Mb"
  Loop_radias = 1 # 1.5
  FontSize = 14
  Gene_highlight = candidate_clear$external_gene_name[i]
  
  save(candidate_clear, i, CHR, START, END, list_Batch1and2_CTL, list_CTL_NeuNn, list_CTL_NeuNp, Loop_toLabel, CTL_ATAC_bw_subset, Gene_highlight, SNP_df, Loop_df, CUTOFF_df, Gb_scale, Loop_radias, FontSize, DOMAIN_COL, Loop_ct, file = paste0(pre_name, "plotgardner_",Gene_highlight,"_Loop",candidate_clear$Loop[i],"_Window_",START/1000,"to",END/1000,"kb_CombineCt_CUTOFF",CUTOFF_df$Cutoff[1],"_DomainTopDom2GENOVAws",ws,".rda")) # _DomainTopDom2GENOVAws5
  
  pdf(paste0(pre_name, "plotgardner_",Gene_highlight,"_Loop",candidate_clear$Loop[i],"_Window_",START/1000,"to",END/1000,"kb_CombineCt_CUTOFF",CUTOFF_df$Cutoff[1],"_DomainTopDom2GENOVAws",ws,".pdf"), height = 11.5, width = 6)  # _DomainTopDom2GENOVAws5
  pageCreate(width = 6, height = ATAC_plot_bs + 1.5, showGuides = F); # pageGuideHide(), height + 2.5 for Genes. height = 2.75*3 + 3.25 for SLC6A1
  
  region <- pgParams(
    chrom = CHR,
    chromstart = START, chromend = END,
    assembly = "hg19",
    width = 5
  )
  
  # CTL_Bulk
  hicPlot_Bulk = plotHicTriangle(
    data = list_Batch1and2_CTL$MAT[,1:3], resolution = 40000,
    zrange = c(0, CUTOFF_df$Cutoff[CUTOFF_df$SampleName == "Batch1and2_CTL"]),
    params = region,
    x = 0.5, y = 0.25, height = 2.5,
    just = c("left", "top"),
    default.units = "inches"
  )
  plotText(
    label = "Bulk", fontsize = FontSize, fontface = "bold",
    x = 1, y = 0.75
  )
  annoHeatmapLegend(
    plot = hicPlot_Bulk, x = 5.6, y = 0.25,
    width = 0.13, height = 1.5,
    just = c("left", "top"),
    fontcolor = "black",
    fontsize = FontSize
  )
  annoDomains(
    plot = hicPlot_Bulk, 
    data = list_Batch1and2_CTL$Domains_relevant,
    linecolor = DOMAIN_COL,  # darkgrey
    lwd = 3
  )
  # annoPixels(
  #   plot = hicPlot_Bulk, 
  #   data = Loop_toLabel,
  #   type = "circle", 
  #   col = "red",
  #   shift = Loop_radias,
  #   lwd = 1.5
  # )
  
  # CTL_NeuNn
  hicPlot_NeuNn = plotHicTriangle(
    data = list_CTL_NeuNn$MAT[,1:3], resolution = 40000,
    zrange = c(0, CUTOFF_df$Cutoff[CUTOFF_df$SampleName == "CTL_NeuNn"]),
    params = region,
    x = 0.5, y = 3, height = 2.5 # adjust y
  )
  plotText(
    label = "NeuNn", fontsize = FontSize, fontface = "bold",
    x = 1, y = 3.5
  )
  
  annoDomains(
    plot = hicPlot_NeuNn, 
    data = list_CTL_NeuNn$Domains_relevant,
    linecolor = DOMAIN_COL, 
    lwd = 3
  )
  # annoPixels(
  #   plot = hicPlot_NeuNn, 
  #   data = Loop_toLabel,
  #   type = "circle", 
  #   col = "red",
  #   shift = Loop_radias,
  #   lwd = 1.5
  # ) 
  
  # CTL_NeuNp - bring NeuNp closer to the gene
  hicPlot_NeuNp = plotHicTriangle(
    data = list_CTL_NeuNp$MAT[,1:3], resolution = 40000,
    zrange = c(0, CUTOFF_df$Cutoff[CUTOFF_df$SampleName == "CTL_NeuNp"]),
    params = region,
    x = 0.5, y = 5.75, height = 2.5
  )
  plotText(
    label = "NeuNp", fontsize = FontSize, fontface = "bold",
    x = 1, y = 6.25
  )
  
  annoDomains(
    plot = hicPlot_NeuNp, 
    data = list_CTL_NeuNp$Domains_relevant,
    linecolor = DOMAIN_COL, 
    lwd = 3
  )
  # annoPixels(
  #   plot = hicPlot_NeuNp, 
  #   data = Loop_toLabel,
  #   type = "circle", 
  #   col = "red",
  #   shift = Loop_radias,
  #   lwd = 1.5
  # )
  
  # Genome labels
  annoGenomeLabel(
    plot = hicPlot_Bulk, x = 0.5, y = 8.25,
    scale = Gb_scale, # If not pretty, remove this line to allow full expression of xxx,xxx,xxx bp
    fontsize = FontSize, 
    just = c("left", "top")
  )
  
  # Genes
  genesPlot <- plotGenes(
    params = region,
    fill = c("black", "black"),
    fontcolor = c("black", "black"),
    fontsize = FontSize, 
    x = 0.5, y = 8.5, height = 1, 
    # adjust y = 3.25 when Triangle baseline at 3
    # remember to adjust width to the same as Triangle Hi-C map
    geneHighlights = data.frame(gene = Gene_highlight, color = "red"), geneBackground = "black",
    geneOrder = geneOrder
  ) 
  
  # SNPs
  pileupPlot <- plotRanges(
    data = SNP_df,
    params = region,
    fill = "red",
    # fill = colorby("strand", palette =
    #                  colorRampPalette(c("steel blue", "light salmon"))),
    x = 0.5, y = 9.5, height = ifelse(length(SNP_df$rsid) == 2, 0.35, 0.17),
    boxHeight = unit(3, "mm"), spaceHeight = 0.4
  )
  plotText(
    label = SNP_df$rsid[1], fontcolor = "red", fontsize = FontSize,
    x = SNP_label_pos, y = 9.6 # SNP_label_pos = 2.2 for SLC6A1
  )
  
  # ATAC peaks
  signalPlot <- plotSignal(
    data = CTL_ATAC_bw_subset, params = region,
    range = c(0, max(CTL_ATAC_bw_subset$score)),  # this sets the range of the signal
    x = 0.5, y = ATAC_plot_bs, height = 0.75, # y=9.85 for SLC6A1
    linecolor = "black", baseline.color = "lightgrey"
  )
  plotText(
    label = "ATAC", fontsize = FontSize, fontface = "bold",
    x = 1, y = 9.95
  )
  
  # Loops
  #data("IMR90_DNAloops_pairs")
  heights <- sqrt(Loop_df$length) / sqrt(max(Loop_df$length)) * 0.5
  # colors <- mapColors(vector = IMR90_DNAloops_pairs$length,
  #                     palette = colorRampPalette(c("dodgerblue2", "firebrick2")))
  archPlot <- plotPairsArches(
    data = Loop_df, params = region,
    fill = Loop_df$col,
    linecolor = "fill",
    archHeight = heights, alpha = 1,
    x = 0.5, y = ATAC_plot_bs + 0.75, height = 0.5,
    flip = T
  )
  
  dev.off()
}

# save(plot_gdn, file = "16_2_v2_06_plot_gdn_function_AllowFilenamePrefix.rda")
save(plot_gdn, file = "16_2_v2_06_plot_gdn_function_AllowFilenamePrefix_DomainTopDom2GENOVA.rda")

## Actual plot
geneOrder = c("NACC1", "NFIX", "TRMT1")
manual_Domains = data.frame(chrom = "chr19", start = 13040000, end = 13400000)

plot_gdn(HALF_window = 3.1e5, SNP_label_pos = 1.7, ATAC_plot_bs = 9.85, DOMAIN_COL = "red", candidate_clear = candidate_clear, df_cur = df_cur, ATACbin_cur = ATACbin_cur, cur_Loop = cur_Loop, SNV_cur = SNV_cur, Loop_ct = "Bulk", geneOrder = geneOrder, ws = 5)
# adjust HALF_window to include all the relevant TAD boundaries

# Observation:
# The NeuNp TAD boundary marked in NeuNp still does not contain the loop. Manually mark? TopDom marks boundaries better than GENOVA.
# The difference between this pdf and the one generated previously with 16_v7_identify_DiseaseRiskIncreasing_BryoiscaQTLinDiffATAC.R is that: Here I have just the caQTL wo the LD friends

plot_gdn(HALF_window = 3.1e5, SNP_label_pos = 1.7, ATAC_plot_bs = 9.85, DOMAIN_COL = "red", candidate_clear = candidate_clear, df_cur = df_cur, ATACbin_cur = ATACbin_cur, cur_Loop = cur_Loop, SNV_cur = SNV_cur, Loop_ct = "Bulk", geneOrder = geneOrder, ws = 5, Batch1and2_CTL_Domains = manual_Domains, CTL_NeuNp_Domains = manual_Domains, CTL_NeuNn_Domains = manual_Domains, pre_name = "16_2_v2_ManualDomains_")


